// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/request/boards-request-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetBoardsRequest retrieves board information available to the aggregator.
type GetBoardsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Criteria describing which boards to fetch.
	Criteria *BoardQueryCriteria `protobuf:"bytes,1,opt,name=criteria,proto3" json:"criteria,omitempty"`
	// Execution settings shared across aggregator requests.
	Settings      *SettingsInput `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardsRequest) Reset() {
	*x = GetBoardsRequest{}
	mi := &file_domain_request_boards_request_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardsRequest) ProtoMessage() {}

func (x *GetBoardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_boards_request_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardsRequest.ProtoReflect.Descriptor instead.
func (*GetBoardsRequest) Descriptor() ([]byte, []int) {
	return file_domain_request_boards_request_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *GetBoardsRequest) GetCriteria() *BoardQueryCriteria {
	if x != nil {
		return x.Criteria
	}
	return nil
}

func (x *GetBoardsRequest) GetSettings() *SettingsInput {
	if x != nil {
		return x.Settings
	}
	return nil
}

// BoardQueryCriteria defines filters applied to board lookups.
type BoardQueryCriteria struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specific board codes to retrieve when the list is non-empty.
	BoardCodes []string `protobuf:"bytes,1,rep,name=boardCodes,proto3" json:"boardCodes,omitempty"`
	// ISO 639-1 language code for board descriptions.
	Language      string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardQueryCriteria) Reset() {
	*x = BoardQueryCriteria{}
	mi := &file_domain_request_boards_request_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardQueryCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardQueryCriteria) ProtoMessage() {}

func (x *BoardQueryCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_boards_request_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardQueryCriteria.ProtoReflect.Descriptor instead.
func (*BoardQueryCriteria) Descriptor() ([]byte, []int) {
	return file_domain_request_boards_request_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *BoardQueryCriteria) GetBoardCodes() []string {
	if x != nil {
		return x.BoardCodes
	}
	return nil
}

func (x *BoardQueryCriteria) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

var File_domain_request_boards_request_hotels_proto protoreflect.FileDescriptor

const file_domain_request_boards_request_hotels_proto_rawDesc = "" +
	"\n" +
	"*domain/request/boards-request-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a*domain/request/common-request-hotels.proto\"\xb7\x01\n" +
	"\x10GetBoardsRequest\x12S\n" +
	"\bcriteria\x18\x01 \x01(\v27.com_bundleport_connect_proto_hotels.BoardQueryCriteriaR\bcriteria\x12N\n" +
	"\bsettings\x18\x02 \x01(\v22.com_bundleport_connect_proto_hotels.SettingsInputR\bsettings\"P\n" +
	"\x12BoardQueryCriteria\x12\x1e\n" +
	"\n" +
	"boardCodes\x18\x01 \x03(\tR\n" +
	"boardCodes\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguageB\x81\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x13BoardsRequestProtosP\x01Z.github.com/bundleport/connect-go-schema/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_request_boards_request_hotels_proto_rawDescOnce sync.Once
	file_domain_request_boards_request_hotels_proto_rawDescData []byte
)

func file_domain_request_boards_request_hotels_proto_rawDescGZIP() []byte {
	file_domain_request_boards_request_hotels_proto_rawDescOnce.Do(func() {
		file_domain_request_boards_request_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_request_boards_request_hotels_proto_rawDesc), len(file_domain_request_boards_request_hotels_proto_rawDesc)))
	})
	return file_domain_request_boards_request_hotels_proto_rawDescData
}

var file_domain_request_boards_request_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_domain_request_boards_request_hotels_proto_goTypes = []any{
	(*GetBoardsRequest)(nil),   // 0: com_bundleport_connect_proto_hotels.GetBoardsRequest
	(*BoardQueryCriteria)(nil), // 1: com_bundleport_connect_proto_hotels.BoardQueryCriteria
	(*SettingsInput)(nil),      // 2: com_bundleport_connect_proto_hotels.SettingsInput
}
var file_domain_request_boards_request_hotels_proto_depIdxs = []int32{
	1, // 0: com_bundleport_connect_proto_hotels.GetBoardsRequest.criteria:type_name -> com_bundleport_connect_proto_hotels.BoardQueryCriteria
	2, // 1: com_bundleport_connect_proto_hotels.GetBoardsRequest.settings:type_name -> com_bundleport_connect_proto_hotels.SettingsInput
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_domain_request_boards_request_hotels_proto_init() }
func file_domain_request_boards_request_hotels_proto_init() {
	if File_domain_request_boards_request_hotels_proto != nil {
		return
	}
	file_domain_request_common_request_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_request_boards_request_hotels_proto_rawDesc), len(file_domain_request_boards_request_hotels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_request_boards_request_hotels_proto_goTypes,
		DependencyIndexes: file_domain_request_boards_request_hotels_proto_depIdxs,
		MessageInfos:      file_domain_request_boards_request_hotels_proto_msgTypes,
	}.Build()
	File_domain_request_boards_request_hotels_proto = out.File
	file_domain_request_boards_request_hotels_proto_goTypes = nil
	file_domain_request_boards_request_hotels_proto_depIdxs = nil
}
