// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/response/boards-response-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetBoardsResponse returns the board catalog for the requested scope.
type GetBoardsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request audit information and downstream trace ids.
	AuditData *AuditData `protobuf:"bytes,1,opt,name=auditData,proto3" json:"auditData,omitempty"`
	// Blocking errors encountered while fetching board data.
	Errors []*Error `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	// Non-blocking warnings returned alongside the board data.
	Warnings []*Warning `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	// Additional debug data for diagnostic purposes.
	DebugData []*TypeValue `protobuf:"bytes,4,rep,name=debugData,proto3" json:"debugData,omitempty"`
	// Collection of boards that match the request criteria.
	Boards *BoardConnection `protobuf:"bytes,5,opt,name=boards,proto3" json:"boards,omitempty"`
	// Pagination token to retrieve the next page of board data.
	Token         string `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardsResponse) Reset() {
	*x = GetBoardsResponse{}
	mi := &file_domain_response_boards_response_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardsResponse) ProtoMessage() {}

func (x *GetBoardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_boards_response_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardsResponse.ProtoReflect.Descriptor instead.
func (*GetBoardsResponse) Descriptor() ([]byte, []int) {
	return file_domain_response_boards_response_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *GetBoardsResponse) GetAuditData() *AuditData {
	if x != nil {
		return x.AuditData
	}
	return nil
}

func (x *GetBoardsResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *GetBoardsResponse) GetWarnings() []*Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *GetBoardsResponse) GetDebugData() []*TypeValue {
	if x != nil {
		return x.DebugData
	}
	return nil
}

func (x *GetBoardsResponse) GetBoards() *BoardConnection {
	if x != nil {
		return x.Boards
	}
	return nil
}

func (x *GetBoardsResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// BoardConnection encapsulates a set of board entries.
type BoardConnection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Boards returned in the current response page.
	Boards        []*Board `protobuf:"bytes,1,rep,name=boards,proto3" json:"boards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardConnection) Reset() {
	*x = BoardConnection{}
	mi := &file_domain_response_boards_response_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardConnection) ProtoMessage() {}

func (x *BoardConnection) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_boards_response_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardConnection.ProtoReflect.Descriptor instead.
func (*BoardConnection) Descriptor() ([]byte, []int) {
	return file_domain_response_boards_response_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *BoardConnection) GetBoards() []*Board {
	if x != nil {
		return x.Boards
	}
	return nil
}

// Board represents a single board entry in the catalog.
type Board struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Aggregator board identifier.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Rich metadata describing the board.
	BoardData *BoardData `protobuf:"bytes,2,opt,name=boardData,proto3" json:"boardData,omitempty"`
	// Creation timestamp for the board entry.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// Last update timestamp for the board entry.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_domain_response_boards_response_hotels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_boards_response_hotels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_domain_response_boards_response_hotels_proto_rawDescGZIP(), []int{2}
}

func (x *Board) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Board) GetBoardData() *BoardData {
	if x != nil {
		return x.BoardData
	}
	return nil
}

func (x *Board) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Board) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// BoardData contains descriptive information for a board.
type BoardData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Internal code used to identify the board entry.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Provider-specific board code.
	BoardCode string `protobuf:"bytes,2,opt,name=boardCode,proto3" json:"boardCode,omitempty"`
	// Localised texts describing the board.
	Texts         []*Text `protobuf:"bytes,3,rep,name=texts,proto3" json:"texts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardData) Reset() {
	*x = BoardData{}
	mi := &file_domain_response_boards_response_hotels_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardData) ProtoMessage() {}

func (x *BoardData) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_boards_response_hotels_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardData.ProtoReflect.Descriptor instead.
func (*BoardData) Descriptor() ([]byte, []int) {
	return file_domain_response_boards_response_hotels_proto_rawDescGZIP(), []int{3}
}

func (x *BoardData) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *BoardData) GetBoardCode() string {
	if x != nil {
		return x.BoardCode
	}
	return ""
}

func (x *BoardData) GetTexts() []*Text {
	if x != nil {
		return x.Texts
	}
	return nil
}

var File_domain_response_boards_response_hotels_proto protoreflect.FileDescriptor

const file_domain_response_boards_response_hotels_proto_rawDesc = "" +
	"\n" +
	",domain/response/boards-response-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a\x1fgoogle/protobuf/timestamp.proto\x1a,domain/response/common-response-hotels.proto\x1a-domain/response/content-response-hotels.proto\"\xa1\x03\n" +
	"\x11GetBoardsResponse\x12L\n" +
	"\tauditData\x18\x01 \x01(\v2..com_bundleport_connect_proto_hotels.AuditDataR\tauditData\x12B\n" +
	"\x06errors\x18\x02 \x03(\v2*.com_bundleport_connect_proto_hotels.ErrorR\x06errors\x12H\n" +
	"\bwarnings\x18\x03 \x03(\v2,.com_bundleport_connect_proto_hotels.WarningR\bwarnings\x12L\n" +
	"\tdebugData\x18\x04 \x03(\v2..com_bundleport_connect_proto_hotels.TypeValueR\tdebugData\x12L\n" +
	"\x06boards\x18\x05 \x01(\v24.com_bundleport_connect_proto_hotels.BoardConnectionR\x06boards\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\"U\n" +
	"\x0fBoardConnection\x12B\n" +
	"\x06boards\x18\x01 \x03(\v2*.com_bundleport_connect_proto_hotels.BoardR\x06boards\"\xdd\x01\n" +
	"\x05Board\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12L\n" +
	"\tboardData\x18\x02 \x01(\v2..com_bundleport_connect_proto_hotels.BoardDataR\tboardData\x128\n" +
	"\tcreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"~\n" +
	"\tBoardData\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1c\n" +
	"\tboardCode\x18\x02 \x01(\tR\tboardCode\x12?\n" +
	"\x05texts\x18\x03 \x03(\v2).com_bundleport_connect_proto_hotels.TextR\x05textsB\x82\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x14BoardsResponseProtosP\x01Z.github.com/bundleport/connect-go-schema/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_response_boards_response_hotels_proto_rawDescOnce sync.Once
	file_domain_response_boards_response_hotels_proto_rawDescData []byte
)

func file_domain_response_boards_response_hotels_proto_rawDescGZIP() []byte {
	file_domain_response_boards_response_hotels_proto_rawDescOnce.Do(func() {
		file_domain_response_boards_response_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_response_boards_response_hotels_proto_rawDesc), len(file_domain_response_boards_response_hotels_proto_rawDesc)))
	})
	return file_domain_response_boards_response_hotels_proto_rawDescData
}

var file_domain_response_boards_response_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_domain_response_boards_response_hotels_proto_goTypes = []any{
	(*GetBoardsResponse)(nil),     // 0: com_bundleport_connect_proto_hotels.GetBoardsResponse
	(*BoardConnection)(nil),       // 1: com_bundleport_connect_proto_hotels.BoardConnection
	(*Board)(nil),                 // 2: com_bundleport_connect_proto_hotels.Board
	(*BoardData)(nil),             // 3: com_bundleport_connect_proto_hotels.BoardData
	(*AuditData)(nil),             // 4: com_bundleport_connect_proto_hotels.AuditData
	(*Error)(nil),                 // 5: com_bundleport_connect_proto_hotels.Error
	(*Warning)(nil),               // 6: com_bundleport_connect_proto_hotels.Warning
	(*TypeValue)(nil),             // 7: com_bundleport_connect_proto_hotels.TypeValue
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*Text)(nil),                  // 9: com_bundleport_connect_proto_hotels.Text
}
var file_domain_response_boards_response_hotels_proto_depIdxs = []int32{
	4,  // 0: com_bundleport_connect_proto_hotels.GetBoardsResponse.auditData:type_name -> com_bundleport_connect_proto_hotels.AuditData
	5,  // 1: com_bundleport_connect_proto_hotels.GetBoardsResponse.errors:type_name -> com_bundleport_connect_proto_hotels.Error
	6,  // 2: com_bundleport_connect_proto_hotels.GetBoardsResponse.warnings:type_name -> com_bundleport_connect_proto_hotels.Warning
	7,  // 3: com_bundleport_connect_proto_hotels.GetBoardsResponse.debugData:type_name -> com_bundleport_connect_proto_hotels.TypeValue
	1,  // 4: com_bundleport_connect_proto_hotels.GetBoardsResponse.boards:type_name -> com_bundleport_connect_proto_hotels.BoardConnection
	2,  // 5: com_bundleport_connect_proto_hotels.BoardConnection.boards:type_name -> com_bundleport_connect_proto_hotels.Board
	3,  // 6: com_bundleport_connect_proto_hotels.Board.boardData:type_name -> com_bundleport_connect_proto_hotels.BoardData
	8,  // 7: com_bundleport_connect_proto_hotels.Board.createdAt:type_name -> google.protobuf.Timestamp
	8,  // 8: com_bundleport_connect_proto_hotels.Board.updatedAt:type_name -> google.protobuf.Timestamp
	9,  // 9: com_bundleport_connect_proto_hotels.BoardData.texts:type_name -> com_bundleport_connect_proto_hotels.Text
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_domain_response_boards_response_hotels_proto_init() }
func file_domain_response_boards_response_hotels_proto_init() {
	if File_domain_response_boards_response_hotels_proto != nil {
		return
	}
	file_domain_response_common_response_hotels_proto_init()
	file_domain_response_content_response_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_response_boards_response_hotels_proto_rawDesc), len(file_domain_response_boards_response_hotels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_response_boards_response_hotels_proto_goTypes,
		DependencyIndexes: file_domain_response_boards_response_hotels_proto_depIdxs,
		MessageInfos:      file_domain_response_boards_response_hotels_proto_msgTypes,
	}.Build()
	File_domain_response_boards_response_hotels_proto = out.File
	file_domain_response_boards_response_hotels_proto_goTypes = nil
	file_domain_response_boards_response_hotels_proto_depIdxs = nil
}
