// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/request/book-request-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BookRequest confirms a booking for a previously quoted option.
type BookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Booking inputs detailing travellers and payment.
	Input *BookInput `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	// Execution settings shared across aggregator requests.
	Settings      *SettingsInput `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookRequest) Reset() {
	*x = BookRequest{}
	mi := &file_domain_request_book_request_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookRequest) ProtoMessage() {}

func (x *BookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_book_request_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookRequest.ProtoReflect.Descriptor instead.
func (*BookRequest) Descriptor() ([]byte, []int) {
	return file_domain_request_book_request_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *BookRequest) GetInput() *BookInput {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *BookRequest) GetSettings() *SettingsInput {
	if x != nil {
		return x.Settings
	}
	return nil
}

// BookInput carries booking information for the selected option.
type BookInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Aggregator option identifier returned by the search flow.
	OptionRefId string `protobuf:"bytes,1,opt,name=optionRefId,proto3" json:"optionRefId,omitempty"`
	// ISO 639-1 language code used for provider communications.
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	// Client reference to correlate the booking in external systems.
	ClientReference string `protobuf:"bytes,3,opt,name=clientReference,proto3" json:"clientReference,omitempty"`
	// Expected price variation applied after the quote stage.
	PriceDelta float64 `protobuf:"fixed64,4,opt,name=priceDelta,proto3" json:"priceDelta,omitempty"`
	// Payment information when the provider requires card details.
	PaymentCard *PaymentCardInput `protobuf:"bytes,5,opt,name=paymentCard,proto3" json:"paymentCard,omitempty"`
	// Remarks transmitted to the provider without transformation.
	Remarks []*TypeValue `protobuf:"bytes,6,rep,name=remarks,proto3" json:"remarks,omitempty"`
	// Booking holder information.
	Holder *HolderInput `protobuf:"bytes,7,opt,name=holder,proto3" json:"holder,omitempty"`
	// Rooms and associated travellers to confirm.
	Rooms []*BookRoomInput `protobuf:"bytes,8,rep,name=rooms,proto3" json:"rooms,omitempty"`
	// Provider-specific parameters forwarded as part of the booking.
	AdditionalData map[string]string `protobuf:"bytes,9,rep,name=additionalData,proto3" json:"additionalData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BookInput) Reset() {
	*x = BookInput{}
	mi := &file_domain_request_book_request_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookInput) ProtoMessage() {}

func (x *BookInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_book_request_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookInput.ProtoReflect.Descriptor instead.
func (*BookInput) Descriptor() ([]byte, []int) {
	return file_domain_request_book_request_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *BookInput) GetOptionRefId() string {
	if x != nil {
		return x.OptionRefId
	}
	return ""
}

func (x *BookInput) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *BookInput) GetClientReference() string {
	if x != nil {
		return x.ClientReference
	}
	return ""
}

func (x *BookInput) GetPriceDelta() float64 {
	if x != nil {
		return x.PriceDelta
	}
	return 0
}

func (x *BookInput) GetPaymentCard() *PaymentCardInput {
	if x != nil {
		return x.PaymentCard
	}
	return nil
}

func (x *BookInput) GetRemarks() []*TypeValue {
	if x != nil {
		return x.Remarks
	}
	return nil
}

func (x *BookInput) GetHolder() *HolderInput {
	if x != nil {
		return x.Holder
	}
	return nil
}

func (x *BookInput) GetRooms() []*BookRoomInput {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *BookInput) GetAdditionalData() map[string]string {
	if x != nil {
		return x.AdditionalData
	}
	return nil
}

// BookRoomInput represents the allocation for a requested room.
type BookRoomInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference to the occupancy from the original search request.
	OccupancyRefId int32 `protobuf:"varint,1,opt,name=occupancyRefId,proto3" json:"occupancyRefId,omitempty"`
	// Travellers assigned to this room.
	Paxes         []*BookPaxInput `protobuf:"bytes,2,rep,name=paxes,proto3" json:"paxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookRoomInput) Reset() {
	*x = BookRoomInput{}
	mi := &file_domain_request_book_request_hotels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookRoomInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookRoomInput) ProtoMessage() {}

func (x *BookRoomInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_book_request_hotels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookRoomInput.ProtoReflect.Descriptor instead.
func (*BookRoomInput) Descriptor() ([]byte, []int) {
	return file_domain_request_book_request_hotels_proto_rawDescGZIP(), []int{2}
}

func (x *BookRoomInput) GetOccupancyRefId() int32 {
	if x != nil {
		return x.OccupancyRefId
	}
	return 0
}

func (x *BookRoomInput) GetPaxes() []*BookPaxInput {
	if x != nil {
		return x.Paxes
	}
	return nil
}

// BookPaxInput describes a traveller included in the booking.
type BookPaxInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Traveller given name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Traveller family name.
	Surname string `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	// Traveller age at check-in.
	Age int32 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	// Courtesy title for the traveller.
	Title         PersonalTitleType `protobuf:"varint,4,opt,name=title,proto3,enum=com_bundleport_connect_proto_hotels.PersonalTitleType" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookPaxInput) Reset() {
	*x = BookPaxInput{}
	mi := &file_domain_request_book_request_hotels_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookPaxInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookPaxInput) ProtoMessage() {}

func (x *BookPaxInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_book_request_hotels_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookPaxInput.ProtoReflect.Descriptor instead.
func (*BookPaxInput) Descriptor() ([]byte, []int) {
	return file_domain_request_book_request_hotels_proto_rawDescGZIP(), []int{3}
}

func (x *BookPaxInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BookPaxInput) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *BookPaxInput) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *BookPaxInput) GetTitle() PersonalTitleType {
	if x != nil {
		return x.Title
	}
	return PersonalTitleType_MR
}

var File_domain_request_book_request_hotels_proto protoreflect.FileDescriptor

const file_domain_request_book_request_hotels_proto_rawDesc = "" +
	"\n" +
	"(domain/request/book-request-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a*domain/request/common-request-hotels.proto\x1a-domain/response/payment-response-hotels.proto\x1a,domain/response/common-response-hotels.proto\"\xa3\x01\n" +
	"\vBookRequest\x12D\n" +
	"\x05input\x18\x01 \x01(\v2..com_bundleport_connect_proto_hotels.BookInputR\x05input\x12N\n" +
	"\bsettings\x18\x02 \x01(\v22.com_bundleport_connect_proto_hotels.SettingsInputR\bsettings\"\xf9\x04\n" +
	"\tBookInput\x12 \n" +
	"\voptionRefId\x18\x01 \x01(\tR\voptionRefId\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12(\n" +
	"\x0fclientReference\x18\x03 \x01(\tR\x0fclientReference\x12\x1e\n" +
	"\n" +
	"priceDelta\x18\x04 \x01(\x01R\n" +
	"priceDelta\x12W\n" +
	"\vpaymentCard\x18\x05 \x01(\v25.com_bundleport_connect_proto_hotels.PaymentCardInputR\vpaymentCard\x12H\n" +
	"\aremarks\x18\x06 \x03(\v2..com_bundleport_connect_proto_hotels.TypeValueR\aremarks\x12H\n" +
	"\x06holder\x18\a \x01(\v20.com_bundleport_connect_proto_hotels.HolderInputR\x06holder\x12H\n" +
	"\x05rooms\x18\b \x03(\v22.com_bundleport_connect_proto_hotels.BookRoomInputR\x05rooms\x12j\n" +
	"\x0eadditionalData\x18\t \x03(\v2B.com_bundleport_connect_proto_hotels.BookInput.AdditionalDataEntryR\x0eadditionalData\x1aA\n" +
	"\x13AdditionalDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x01\n" +
	"\rBookRoomInput\x12&\n" +
	"\x0eoccupancyRefId\x18\x01 \x01(\x05R\x0eoccupancyRefId\x12G\n" +
	"\x05paxes\x18\x02 \x03(\v21.com_bundleport_connect_proto_hotels.BookPaxInputR\x05paxes\"\x9c\x01\n" +
	"\fBookPaxInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x02 \x01(\tR\asurname\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12L\n" +
	"\x05title\x18\x04 \x01(\x0e26.com_bundleport_connect_proto_hotels.PersonalTitleTypeR\x05titleB\x7f\n" +
	"\x1ccom.bundleport.connect.protoB\x11BookRequestProtosP\x01Z.github.com/bundleport/connect-go-schema/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_request_book_request_hotels_proto_rawDescOnce sync.Once
	file_domain_request_book_request_hotels_proto_rawDescData []byte
)

func file_domain_request_book_request_hotels_proto_rawDescGZIP() []byte {
	file_domain_request_book_request_hotels_proto_rawDescOnce.Do(func() {
		file_domain_request_book_request_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_request_book_request_hotels_proto_rawDesc), len(file_domain_request_book_request_hotels_proto_rawDesc)))
	})
	return file_domain_request_book_request_hotels_proto_rawDescData
}

var file_domain_request_book_request_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_domain_request_book_request_hotels_proto_goTypes = []any{
	(*BookRequest)(nil),      // 0: com_bundleport_connect_proto_hotels.BookRequest
	(*BookInput)(nil),        // 1: com_bundleport_connect_proto_hotels.BookInput
	(*BookRoomInput)(nil),    // 2: com_bundleport_connect_proto_hotels.BookRoomInput
	(*BookPaxInput)(nil),     // 3: com_bundleport_connect_proto_hotels.BookPaxInput
	nil,                      // 4: com_bundleport_connect_proto_hotels.BookInput.AdditionalDataEntry
	(*SettingsInput)(nil),    // 5: com_bundleport_connect_proto_hotels.SettingsInput
	(*PaymentCardInput)(nil), // 6: com_bundleport_connect_proto_hotels.PaymentCardInput
	(*TypeValue)(nil),        // 7: com_bundleport_connect_proto_hotels.TypeValue
	(*HolderInput)(nil),      // 8: com_bundleport_connect_proto_hotels.HolderInput
	(PersonalTitleType)(0),   // 9: com_bundleport_connect_proto_hotels.PersonalTitleType
}
var file_domain_request_book_request_hotels_proto_depIdxs = []int32{
	1, // 0: com_bundleport_connect_proto_hotels.BookRequest.input:type_name -> com_bundleport_connect_proto_hotels.BookInput
	5, // 1: com_bundleport_connect_proto_hotels.BookRequest.settings:type_name -> com_bundleport_connect_proto_hotels.SettingsInput
	6, // 2: com_bundleport_connect_proto_hotels.BookInput.paymentCard:type_name -> com_bundleport_connect_proto_hotels.PaymentCardInput
	7, // 3: com_bundleport_connect_proto_hotels.BookInput.remarks:type_name -> com_bundleport_connect_proto_hotels.TypeValue
	8, // 4: com_bundleport_connect_proto_hotels.BookInput.holder:type_name -> com_bundleport_connect_proto_hotels.HolderInput
	2, // 5: com_bundleport_connect_proto_hotels.BookInput.rooms:type_name -> com_bundleport_connect_proto_hotels.BookRoomInput
	4, // 6: com_bundleport_connect_proto_hotels.BookInput.additionalData:type_name -> com_bundleport_connect_proto_hotels.BookInput.AdditionalDataEntry
	3, // 7: com_bundleport_connect_proto_hotels.BookRoomInput.paxes:type_name -> com_bundleport_connect_proto_hotels.BookPaxInput
	9, // 8: com_bundleport_connect_proto_hotels.BookPaxInput.title:type_name -> com_bundleport_connect_proto_hotels.PersonalTitleType
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_domain_request_book_request_hotels_proto_init() }
func file_domain_request_book_request_hotels_proto_init() {
	if File_domain_request_book_request_hotels_proto != nil {
		return
	}
	file_domain_request_common_request_hotels_proto_init()
	file_domain_response_payment_response_hotels_proto_init()
	file_domain_response_common_response_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_request_book_request_hotels_proto_rawDesc), len(file_domain_request_book_request_hotels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_request_book_request_hotels_proto_goTypes,
		DependencyIndexes: file_domain_request_book_request_hotels_proto_depIdxs,
		MessageInfos:      file_domain_request_book_request_hotels_proto_msgTypes,
	}.Build()
	File_domain_request_book_request_hotels_proto = out.File
	file_domain_request_book_request_hotels_proto_goTypes = nil
	file_domain_request_book_request_hotels_proto_depIdxs = nil
}
