// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/response/booking-detail-response-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BookingDetailResponse returns detailed information for a booking.
type BookingDetailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request audit information and downstream trace ids.
	AuditData *AuditData `protobuf:"bytes,1,opt,name=auditData,proto3" json:"auditData,omitempty"`
	// Blocking errors encountered while retrieving the booking.
	Errors []*Error `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	// Non-blocking warnings returned alongside the booking.
	Warnings []*Warning `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	// Additional debug data for diagnostic purposes.
	DebugData []*TypeValue `protobuf:"bytes,4,rep,name=debugData,proto3" json:"debugData,omitempty"`
	// Booking details as defined in BookResponse.
	Booking       *BookingDetail `protobuf:"bytes,5,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingDetailResponse) Reset() {
	*x = BookingDetailResponse{}
	mi := &file_domain_response_booking_detail_response_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingDetailResponse) ProtoMessage() {}

func (x *BookingDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_booking_detail_response_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingDetailResponse.ProtoReflect.Descriptor instead.
func (*BookingDetailResponse) Descriptor() ([]byte, []int) {
	return file_domain_response_booking_detail_response_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *BookingDetailResponse) GetAuditData() *AuditData {
	if x != nil {
		return x.AuditData
	}
	return nil
}

func (x *BookingDetailResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BookingDetailResponse) GetWarnings() []*Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *BookingDetailResponse) GetDebugData() []*TypeValue {
	if x != nil {
		return x.DebugData
	}
	return nil
}

func (x *BookingDetailResponse) GetBooking() *BookingDetail {
	if x != nil {
		return x.Booking
	}
	return nil
}

var File_domain_response_booking_detail_response_hotels_proto protoreflect.FileDescriptor

const file_domain_response_booking_detail_response_hotels_proto_rawDesc = "" +
	"\n" +
	"4domain/response/booking-detail-response-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a,domain/response/common-response-hotels.proto\x1a*domain/response/book-response-hotels.proto\"\x8f\x03\n" +
	"\x15BookingDetailResponse\x12L\n" +
	"\tauditData\x18\x01 \x01(\v2..com_bundleport_connect_proto_hotels.AuditDataR\tauditData\x12B\n" +
	"\x06errors\x18\x02 \x03(\v2*.com_bundleport_connect_proto_hotels.ErrorR\x06errors\x12H\n" +
	"\bwarnings\x18\x03 \x03(\v2,.com_bundleport_connect_proto_hotels.WarningR\bwarnings\x12L\n" +
	"\tdebugData\x18\x04 \x03(\v2..com_bundleport_connect_proto_hotels.TypeValueR\tdebugData\x12L\n" +
	"\abooking\x18\x05 \x01(\v22.com_bundleport_connect_proto_hotels.BookingDetailR\abookingB\x89\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x1bBookingDetailResponseProtosP\x01Z.github.com/bundleport/connect-hotels-go/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_response_booking_detail_response_hotels_proto_rawDescOnce sync.Once
	file_domain_response_booking_detail_response_hotels_proto_rawDescData []byte
)

func file_domain_response_booking_detail_response_hotels_proto_rawDescGZIP() []byte {
	file_domain_response_booking_detail_response_hotels_proto_rawDescOnce.Do(func() {
		file_domain_response_booking_detail_response_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_response_booking_detail_response_hotels_proto_rawDesc), len(file_domain_response_booking_detail_response_hotels_proto_rawDesc)))
	})
	return file_domain_response_booking_detail_response_hotels_proto_rawDescData
}

var file_domain_response_booking_detail_response_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_domain_response_booking_detail_response_hotels_proto_goTypes = []any{
	(*BookingDetailResponse)(nil), // 0: com_bundleport_connect_proto_hotels.BookingDetailResponse
	(*AuditData)(nil),             // 1: com_bundleport_connect_proto_hotels.AuditData
	(*Error)(nil),                 // 2: com_bundleport_connect_proto_hotels.Error
	(*Warning)(nil),               // 3: com_bundleport_connect_proto_hotels.Warning
	(*TypeValue)(nil),             // 4: com_bundleport_connect_proto_hotels.TypeValue
	(*BookingDetail)(nil),         // 5: com_bundleport_connect_proto_hotels.BookingDetail
}
var file_domain_response_booking_detail_response_hotels_proto_depIdxs = []int32{
	1, // 0: com_bundleport_connect_proto_hotels.BookingDetailResponse.auditData:type_name -> com_bundleport_connect_proto_hotels.AuditData
	2, // 1: com_bundleport_connect_proto_hotels.BookingDetailResponse.errors:type_name -> com_bundleport_connect_proto_hotels.Error
	3, // 2: com_bundleport_connect_proto_hotels.BookingDetailResponse.warnings:type_name -> com_bundleport_connect_proto_hotels.Warning
	4, // 3: com_bundleport_connect_proto_hotels.BookingDetailResponse.debugData:type_name -> com_bundleport_connect_proto_hotels.TypeValue
	5, // 4: com_bundleport_connect_proto_hotels.BookingDetailResponse.booking:type_name -> com_bundleport_connect_proto_hotels.BookingDetail
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_domain_response_booking_detail_response_hotels_proto_init() }
func file_domain_response_booking_detail_response_hotels_proto_init() {
	if File_domain_response_booking_detail_response_hotels_proto != nil {
		return
	}
	file_domain_response_common_response_hotels_proto_init()
	file_domain_response_book_response_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_response_booking_detail_response_hotels_proto_rawDesc), len(file_domain_response_booking_detail_response_hotels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_response_booking_detail_response_hotels_proto_goTypes,
		DependencyIndexes: file_domain_response_booking_detail_response_hotels_proto_depIdxs,
		MessageInfos:      file_domain_response_booking_detail_response_hotels_proto_msgTypes,
	}.Build()
	File_domain_response_booking_detail_response_hotels_proto = out.File
	file_domain_response_booking_detail_response_hotels_proto_goTypes = nil
	file_domain_response_booking_detail_response_hotels_proto_depIdxs = nil
}
