// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/response/booking-response-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CancelPenaltyType indicates how cancellation penalties are expressed.
type CancelPenaltyType int32

const (
	CancelPenaltyType_IMPORT  CancelPenaltyType = 0
	CancelPenaltyType_NIGHTS  CancelPenaltyType = 1
	CancelPenaltyType_PERCENT CancelPenaltyType = 2
)

// Enum value maps for CancelPenaltyType.
var (
	CancelPenaltyType_name = map[int32]string{
		0: "IMPORT",
		1: "NIGHTS",
		2: "PERCENT",
	}
	CancelPenaltyType_value = map[string]int32{
		"IMPORT":  0,
		"NIGHTS":  1,
		"PERCENT": 2,
	}
)

func (x CancelPenaltyType) Enum() *CancelPenaltyType {
	p := new(CancelPenaltyType)
	*p = x
	return p
}

func (x CancelPenaltyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CancelPenaltyType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_response_booking_response_hotels_proto_enumTypes[0].Descriptor()
}

func (CancelPenaltyType) Type() protoreflect.EnumType {
	return &file_domain_response_booking_response_hotels_proto_enumTypes[0]
}

func (x CancelPenaltyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CancelPenaltyType.Descriptor instead.
func (CancelPenaltyType) EnumDescriptor() ([]byte, []int) {
	return file_domain_response_booking_response_hotels_proto_rawDescGZIP(), []int{0}
}

// ChargeType indicates whether a surcharge is included in the price.
type ChargeType int32

const (
	ChargeType_INCLUDE ChargeType = 0
	ChargeType_EXCLUDE ChargeType = 1
)

// Enum value maps for ChargeType.
var (
	ChargeType_name = map[int32]string{
		0: "INCLUDE",
		1: "EXCLUDE",
	}
	ChargeType_value = map[string]int32{
		"INCLUDE": 0,
		"EXCLUDE": 1,
	}
)

func (x ChargeType) Enum() *ChargeType {
	p := new(ChargeType)
	*p = x
	return p
}

func (x ChargeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChargeType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_response_booking_response_hotels_proto_enumTypes[1].Descriptor()
}

func (ChargeType) Type() protoreflect.EnumType {
	return &file_domain_response_booking_response_hotels_proto_enumTypes[1]
}

func (x ChargeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChargeType.Descriptor instead.
func (ChargeType) EnumDescriptor() ([]byte, []int) {
	return file_domain_response_booking_response_hotels_proto_rawDescGZIP(), []int{1}
}

// Surcharge represents additional fees applied to an option or booking.
type Surcharge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Surcharge type identifier.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Human readable description of the surcharge.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Indicates whether the surcharge is mandatory.
	Mandatory bool `protobuf:"varint,3,opt,name=mandatory,proto3" json:"mandatory,omitempty"`
	// Indicates whether the surcharge is included in the displayed price.
	Included bool `protobuf:"varint,4,opt,name=included,proto3" json:"included,omitempty"`
	// Price associated with the surcharge.
	Price         *Price `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Surcharge) Reset() {
	*x = Surcharge{}
	mi := &file_domain_response_booking_response_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Surcharge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Surcharge) ProtoMessage() {}

func (x *Surcharge) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_booking_response_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Surcharge.ProtoReflect.Descriptor instead.
func (*Surcharge) Descriptor() ([]byte, []int) {
	return file_domain_response_booking_response_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *Surcharge) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Surcharge) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Surcharge) GetMandatory() bool {
	if x != nil {
		return x.Mandatory
	}
	return false
}

func (x *Surcharge) GetIncluded() bool {
	if x != nil {
		return x.Included
	}
	return false
}

func (x *Surcharge) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

// CancelPolicy describes the cancellation rules for an option or booking.
type CancelPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Penalties applicable when cancelling.
	CancelPenalties []*CancelPenalty `protobuf:"bytes,1,rep,name=cancelPenalties,proto3" json:"cancelPenalties,omitempty"`
	// Indicates whether the booking is refundable.
	Refundable    bool `protobuf:"varint,2,opt,name=refundable,proto3" json:"refundable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPolicy) Reset() {
	*x = CancelPolicy{}
	mi := &file_domain_response_booking_response_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPolicy) ProtoMessage() {}

func (x *CancelPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_booking_response_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPolicy.ProtoReflect.Descriptor instead.
func (*CancelPolicy) Descriptor() ([]byte, []int) {
	return file_domain_response_booking_response_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *CancelPolicy) GetCancelPenalties() []*CancelPenalty {
	if x != nil {
		return x.CancelPenalties
	}
	return nil
}

func (x *CancelPolicy) GetRefundable() bool {
	if x != nil {
		return x.Refundable
	}
	return false
}

// CancelPenalty represents a penalty applied when cancelling after a deadline.
type CancelPenalty struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Currency used for the penalty value.
	Currency string `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	// Deadline timestamp after which the penalty applies.
	Deadline *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// Hours before arrival when the penalty becomes effective.
	HoursBefore int32 `protobuf:"varint,3,opt,name=hoursBefore,proto3" json:"hoursBefore,omitempty"`
	// Type of penalty value.
	PenaltyType CancelPenaltyType `protobuf:"varint,4,opt,name=penaltyType,proto3,enum=com_bundleport_connect_proto_hotels.CancelPenaltyType" json:"penaltyType,omitempty"`
	// Penalty value interpreted according to penaltyType.
	Value         float64 `protobuf:"fixed64,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPenalty) Reset() {
	*x = CancelPenalty{}
	mi := &file_domain_response_booking_response_hotels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPenalty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPenalty) ProtoMessage() {}

func (x *CancelPenalty) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_booking_response_hotels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPenalty.ProtoReflect.Descriptor instead.
func (*CancelPenalty) Descriptor() ([]byte, []int) {
	return file_domain_response_booking_response_hotels_proto_rawDescGZIP(), []int{2}
}

func (x *CancelPenalty) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CancelPenalty) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *CancelPenalty) GetHoursBefore() int32 {
	if x != nil {
		return x.HoursBefore
	}
	return 0
}

func (x *CancelPenalty) GetPenaltyType() CancelPenaltyType {
	if x != nil {
		return x.PenaltyType
	}
	return CancelPenaltyType_IMPORT
}

func (x *CancelPenalty) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Occupancy associates travellers with a requested room.
type Occupancy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Occupancy identifier used to correlate rooms and travellers.
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Travellers assigned to this occupancy.
	Paxes         []*Pax `protobuf:"bytes,2,rep,name=paxes,proto3" json:"paxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Occupancy) Reset() {
	*x = Occupancy{}
	mi := &file_domain_response_booking_response_hotels_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Occupancy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Occupancy) ProtoMessage() {}

func (x *Occupancy) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_booking_response_hotels_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Occupancy.ProtoReflect.Descriptor instead.
func (*Occupancy) Descriptor() ([]byte, []int) {
	return file_domain_response_booking_response_hotels_proto_rawDescGZIP(), []int{3}
}

func (x *Occupancy) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Occupancy) GetPaxes() []*Pax {
	if x != nil {
		return x.Paxes
	}
	return nil
}

// Pax represents an individual traveller.
type Pax struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Traveller age at check-in.
	Age           int32 `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pax) Reset() {
	*x = Pax{}
	mi := &file_domain_response_booking_response_hotels_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pax) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pax) ProtoMessage() {}

func (x *Pax) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_booking_response_hotels_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pax.ProtoReflect.Descriptor instead.
func (*Pax) Descriptor() ([]byte, []int) {
	return file_domain_response_booking_response_hotels_proto_rawDescGZIP(), []int{4}
}

func (x *Pax) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

// BookingRoom summarises room details in booking responses.
type BookingRoom struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference to the occupancy from the request.
	OccupancyRefId int32 `protobuf:"varint,1,opt,name=occupancyRefId,proto3" json:"occupancyRefId,omitempty"`
	// Provider room code.
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Descriptive room name.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Price associated with the room.
	Price         *Price `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingRoom) Reset() {
	*x = BookingRoom{}
	mi := &file_domain_response_booking_response_hotels_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingRoom) ProtoMessage() {}

func (x *BookingRoom) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_booking_response_hotels_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingRoom.ProtoReflect.Descriptor instead.
func (*BookingRoom) Descriptor() ([]byte, []int) {
	return file_domain_response_booking_response_hotels_proto_rawDescGZIP(), []int{5}
}

func (x *BookingRoom) GetOccupancyRefId() int32 {
	if x != nil {
		return x.OccupancyRefId
	}
	return 0
}

func (x *BookingRoom) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *BookingRoom) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BookingRoom) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

var File_domain_response_booking_response_hotels_proto protoreflect.FileDescriptor

const file_domain_response_booking_response_hotels_proto_rawDesc = "" +
	"\n" +
	"-domain/response/booking-response-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a\x1fgoogle/protobuf/timestamp.proto\x1a,domain/response/common-response-hotels.proto\"\xbd\x01\n" +
	"\tSurcharge\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1c\n" +
	"\tmandatory\x18\x03 \x01(\bR\tmandatory\x12\x1a\n" +
	"\bincluded\x18\x04 \x01(\bR\bincluded\x12@\n" +
	"\x05price\x18\x05 \x01(\v2*.com_bundleport_connect_proto_hotels.PriceR\x05price\"\x8c\x01\n" +
	"\fCancelPolicy\x12\\\n" +
	"\x0fcancelPenalties\x18\x01 \x03(\v22.com_bundleport_connect_proto_hotels.CancelPenaltyR\x0fcancelPenalties\x12\x1e\n" +
	"\n" +
	"refundable\x18\x02 \x01(\bR\n" +
	"refundable\"\xf5\x01\n" +
	"\rCancelPenalty\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x126\n" +
	"\bdeadline\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12 \n" +
	"\vhoursBefore\x18\x03 \x01(\x05R\vhoursBefore\x12X\n" +
	"\vpenaltyType\x18\x04 \x01(\x0e26.com_bundleport_connect_proto_hotels.CancelPenaltyTypeR\vpenaltyType\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x01R\x05value\"[\n" +
	"\tOccupancy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12>\n" +
	"\x05paxes\x18\x02 \x03(\v2(.com_bundleport_connect_proto_hotels.PaxR\x05paxes\"\x17\n" +
	"\x03Pax\x12\x10\n" +
	"\x03age\x18\x01 \x01(\x05R\x03age\"\xad\x01\n" +
	"\vBookingRoom\x12&\n" +
	"\x0eoccupancyRefId\x18\x01 \x01(\x05R\x0eoccupancyRefId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12@\n" +
	"\x05price\x18\x04 \x01(\v2*.com_bundleport_connect_proto_hotels.PriceR\x05price*8\n" +
	"\x11CancelPenaltyType\x12\n" +
	"\n" +
	"\x06IMPORT\x10\x00\x12\n" +
	"\n" +
	"\x06NIGHTS\x10\x01\x12\v\n" +
	"\aPERCENT\x10\x02*&\n" +
	"\n" +
	"ChargeType\x12\v\n" +
	"\aINCLUDE\x10\x00\x12\v\n" +
	"\aEXCLUDE\x10\x01B\x83\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x15BookingResponseProtosP\x01Z.github.com/bundleport/connect-hotels-go/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_response_booking_response_hotels_proto_rawDescOnce sync.Once
	file_domain_response_booking_response_hotels_proto_rawDescData []byte
)

func file_domain_response_booking_response_hotels_proto_rawDescGZIP() []byte {
	file_domain_response_booking_response_hotels_proto_rawDescOnce.Do(func() {
		file_domain_response_booking_response_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_response_booking_response_hotels_proto_rawDesc), len(file_domain_response_booking_response_hotels_proto_rawDesc)))
	})
	return file_domain_response_booking_response_hotels_proto_rawDescData
}

var file_domain_response_booking_response_hotels_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_domain_response_booking_response_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_domain_response_booking_response_hotels_proto_goTypes = []any{
	(CancelPenaltyType)(0),        // 0: com_bundleport_connect_proto_hotels.CancelPenaltyType
	(ChargeType)(0),               // 1: com_bundleport_connect_proto_hotels.ChargeType
	(*Surcharge)(nil),             // 2: com_bundleport_connect_proto_hotels.Surcharge
	(*CancelPolicy)(nil),          // 3: com_bundleport_connect_proto_hotels.CancelPolicy
	(*CancelPenalty)(nil),         // 4: com_bundleport_connect_proto_hotels.CancelPenalty
	(*Occupancy)(nil),             // 5: com_bundleport_connect_proto_hotels.Occupancy
	(*Pax)(nil),                   // 6: com_bundleport_connect_proto_hotels.Pax
	(*BookingRoom)(nil),           // 7: com_bundleport_connect_proto_hotels.BookingRoom
	(*Price)(nil),                 // 8: com_bundleport_connect_proto_hotels.Price
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_domain_response_booking_response_hotels_proto_depIdxs = []int32{
	8, // 0: com_bundleport_connect_proto_hotels.Surcharge.price:type_name -> com_bundleport_connect_proto_hotels.Price
	4, // 1: com_bundleport_connect_proto_hotels.CancelPolicy.cancelPenalties:type_name -> com_bundleport_connect_proto_hotels.CancelPenalty
	9, // 2: com_bundleport_connect_proto_hotels.CancelPenalty.deadline:type_name -> google.protobuf.Timestamp
	0, // 3: com_bundleport_connect_proto_hotels.CancelPenalty.penaltyType:type_name -> com_bundleport_connect_proto_hotels.CancelPenaltyType
	6, // 4: com_bundleport_connect_proto_hotels.Occupancy.paxes:type_name -> com_bundleport_connect_proto_hotels.Pax
	8, // 5: com_bundleport_connect_proto_hotels.BookingRoom.price:type_name -> com_bundleport_connect_proto_hotels.Price
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_domain_response_booking_response_hotels_proto_init() }
func file_domain_response_booking_response_hotels_proto_init() {
	if File_domain_response_booking_response_hotels_proto != nil {
		return
	}
	file_domain_response_common_response_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_response_booking_response_hotels_proto_rawDesc), len(file_domain_response_booking_response_hotels_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_response_booking_response_hotels_proto_goTypes,
		DependencyIndexes: file_domain_response_booking_response_hotels_proto_depIdxs,
		EnumInfos:         file_domain_response_booking_response_hotels_proto_enumTypes,
		MessageInfos:      file_domain_response_booking_response_hotels_proto_msgTypes,
	}.Build()
	File_domain_response_booking_response_hotels_proto = out.File
	file_domain_response_booking_response_hotels_proto_goTypes = nil
	file_domain_response_booking_response_hotels_proto_depIdxs = nil
}
