// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/request/booking-list-request-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BookingListCriteriaType describes the booking list lookup strategy.
type BookingListCriteriaType int32

const (
	// Retrieve bookings using a date range.
	BookingListCriteriaType_BOOKING_LIST_CRITERIA_TYPE_DATES BookingListCriteriaType = 0
	// Retrieve bookings using explicit references.
	BookingListCriteriaType_BOOKING_LIST_CRITERIA_TYPE_REFERENCES BookingListCriteriaType = 1
)

// Enum value maps for BookingListCriteriaType.
var (
	BookingListCriteriaType_name = map[int32]string{
		0: "BOOKING_LIST_CRITERIA_TYPE_DATES",
		1: "BOOKING_LIST_CRITERIA_TYPE_REFERENCES",
	}
	BookingListCriteriaType_value = map[string]int32{
		"BOOKING_LIST_CRITERIA_TYPE_DATES":      0,
		"BOOKING_LIST_CRITERIA_TYPE_REFERENCES": 1,
	}
)

func (x BookingListCriteriaType) Enum() *BookingListCriteriaType {
	p := new(BookingListCriteriaType)
	*p = x
	return p
}

func (x BookingListCriteriaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookingListCriteriaType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_request_booking_list_request_hotels_proto_enumTypes[0].Descriptor()
}

func (BookingListCriteriaType) Type() protoreflect.EnumType {
	return &file_domain_request_booking_list_request_hotels_proto_enumTypes[0]
}

func (x BookingListCriteriaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookingListCriteriaType.Descriptor instead.
func (BookingListCriteriaType) EnumDescriptor() ([]byte, []int) {
	return file_domain_request_booking_list_request_hotels_proto_rawDescGZIP(), []int{0}
}

// BookingListCriteriaDateType specifies which booking date to filter on.
type BookingListCriteriaDateType int32

const (
	// Use the booking creation date.
	BookingListCriteriaDateType_BOOKING_LIST_CRITERIA_DATE_TYPE_BOOKING BookingListCriteriaDateType = 0
	// Use the arrival (check-in) date.
	BookingListCriteriaDateType_BOOKING_LIST_CRITERIA_DATE_TYPE_ARRIVAL BookingListCriteriaDateType = 1
)

// Enum value maps for BookingListCriteriaDateType.
var (
	BookingListCriteriaDateType_name = map[int32]string{
		0: "BOOKING_LIST_CRITERIA_DATE_TYPE_BOOKING",
		1: "BOOKING_LIST_CRITERIA_DATE_TYPE_ARRIVAL",
	}
	BookingListCriteriaDateType_value = map[string]int32{
		"BOOKING_LIST_CRITERIA_DATE_TYPE_BOOKING": 0,
		"BOOKING_LIST_CRITERIA_DATE_TYPE_ARRIVAL": 1,
	}
)

func (x BookingListCriteriaDateType) Enum() *BookingListCriteriaDateType {
	p := new(BookingListCriteriaDateType)
	*p = x
	return p
}

func (x BookingListCriteriaDateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookingListCriteriaDateType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_request_booking_list_request_hotels_proto_enumTypes[1].Descriptor()
}

func (BookingListCriteriaDateType) Type() protoreflect.EnumType {
	return &file_domain_request_booking_list_request_hotels_proto_enumTypes[1]
}

func (x BookingListCriteriaDateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookingListCriteriaDateType.Descriptor instead.
func (BookingListCriteriaDateType) EnumDescriptor() ([]byte, []int) {
	return file_domain_request_booking_list_request_hotels_proto_rawDescGZIP(), []int{1}
}

// BookingListRequest retrieves multiple bookings based on filters.
type BookingListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Criteria that define which bookings should be returned.
	Criteria *CriteriaBookingListInput `protobuf:"bytes,1,opt,name=criteria,proto3" json:"criteria,omitempty"`
	// Execution settings shared across aggregator requests.
	Settings      *SettingsInput `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingListRequest) Reset() {
	*x = BookingListRequest{}
	mi := &file_domain_request_booking_list_request_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingListRequest) ProtoMessage() {}

func (x *BookingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_booking_list_request_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingListRequest.ProtoReflect.Descriptor instead.
func (*BookingListRequest) Descriptor() ([]byte, []int) {
	return file_domain_request_booking_list_request_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *BookingListRequest) GetCriteria() *CriteriaBookingListInput {
	if x != nil {
		return x.Criteria
	}
	return nil
}

func (x *BookingListRequest) GetSettings() *SettingsInput {
	if x != nil {
		return x.Settings
	}
	return nil
}

// CriteriaBookingListInput supports filtering bookings by ids or dates.
type CriteriaBookingListInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Defines whether filtering is performed by dates or references.
	TypeSearch BookingListCriteriaType `protobuf:"varint,1,opt,name=typeSearch,proto3,enum=com_bundleport_connect_proto_hotels.BookingListCriteriaType" json:"typeSearch,omitempty"`
	// Booking references used when performing a reference lookup.
	References []*BookingListReferenceInput `protobuf:"bytes,2,rep,name=references,proto3" json:"references,omitempty"`
	// Date range used when filtering by time period.
	Dates *CriteriaBookingListDatesInput `protobuf:"bytes,3,opt,name=dates,proto3" json:"dates,omitempty"`
	// Additional provider-specific parameters.
	AdditionalParams map[string]string `protobuf:"bytes,4,rep,name=additionalParams,proto3" json:"additionalParams,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CriteriaBookingListInput) Reset() {
	*x = CriteriaBookingListInput{}
	mi := &file_domain_request_booking_list_request_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriteriaBookingListInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriteriaBookingListInput) ProtoMessage() {}

func (x *CriteriaBookingListInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_booking_list_request_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriteriaBookingListInput.ProtoReflect.Descriptor instead.
func (*CriteriaBookingListInput) Descriptor() ([]byte, []int) {
	return file_domain_request_booking_list_request_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *CriteriaBookingListInput) GetTypeSearch() BookingListCriteriaType {
	if x != nil {
		return x.TypeSearch
	}
	return BookingListCriteriaType_BOOKING_LIST_CRITERIA_TYPE_DATES
}

func (x *CriteriaBookingListInput) GetReferences() []*BookingListReferenceInput {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *CriteriaBookingListInput) GetDates() *CriteriaBookingListDatesInput {
	if x != nil {
		return x.Dates
	}
	return nil
}

func (x *CriteriaBookingListInput) GetAdditionalParams() map[string]string {
	if x != nil {
		return x.AdditionalParams
	}
	return nil
}

// BookingListReferenceInput contains identifiers for known bookings.
type BookingListReferenceInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Aggregator booking identifier.
	BookingID string `protobuf:"bytes,1,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	// Client reference provided at booking time.
	ClientReference string `protobuf:"bytes,2,opt,name=clientReference,proto3" json:"clientReference,omitempty"`
	// Provider booking reference.
	ProviderReference string `protobuf:"bytes,3,opt,name=providerReference,proto3" json:"providerReference,omitempty"`
	// Confirmation reference provided to the traveller.
	ConfirmationReference string `protobuf:"bytes,4,opt,name=confirmationReference,proto3" json:"confirmationReference,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BookingListReferenceInput) Reset() {
	*x = BookingListReferenceInput{}
	mi := &file_domain_request_booking_list_request_hotels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingListReferenceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingListReferenceInput) ProtoMessage() {}

func (x *BookingListReferenceInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_booking_list_request_hotels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingListReferenceInput.ProtoReflect.Descriptor instead.
func (*BookingListReferenceInput) Descriptor() ([]byte, []int) {
	return file_domain_request_booking_list_request_hotels_proto_rawDescGZIP(), []int{2}
}

func (x *BookingListReferenceInput) GetBookingID() string {
	if x != nil {
		return x.BookingID
	}
	return ""
}

func (x *BookingListReferenceInput) GetClientReference() string {
	if x != nil {
		return x.ClientReference
	}
	return ""
}

func (x *BookingListReferenceInput) GetProviderReference() string {
	if x != nil {
		return x.ProviderReference
	}
	return ""
}

func (x *BookingListReferenceInput) GetConfirmationReference() string {
	if x != nil {
		return x.ConfirmationReference
	}
	return ""
}

// CriteriaBookingListDatesInput defines a window to filter bookings.
type CriteriaBookingListDatesInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Date dimension used for the range filter.
	DateType BookingListCriteriaDateType `protobuf:"varint,1,opt,name=dateType,proto3,enum=com_bundleport_connect_proto_hotels.BookingListCriteriaDateType" json:"dateType,omitempty"`
	// Range start timestamp.
	Start *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	// Range end timestamp.
	End           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriteriaBookingListDatesInput) Reset() {
	*x = CriteriaBookingListDatesInput{}
	mi := &file_domain_request_booking_list_request_hotels_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriteriaBookingListDatesInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriteriaBookingListDatesInput) ProtoMessage() {}

func (x *CriteriaBookingListDatesInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_booking_list_request_hotels_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriteriaBookingListDatesInput.ProtoReflect.Descriptor instead.
func (*CriteriaBookingListDatesInput) Descriptor() ([]byte, []int) {
	return file_domain_request_booking_list_request_hotels_proto_rawDescGZIP(), []int{3}
}

func (x *CriteriaBookingListDatesInput) GetDateType() BookingListCriteriaDateType {
	if x != nil {
		return x.DateType
	}
	return BookingListCriteriaDateType_BOOKING_LIST_CRITERIA_DATE_TYPE_BOOKING
}

func (x *CriteriaBookingListDatesInput) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *CriteriaBookingListDatesInput) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

var File_domain_request_booking_list_request_hotels_proto protoreflect.FileDescriptor

const file_domain_request_booking_list_request_hotels_proto_rawDesc = "" +
	"\n" +
	"0domain/request/booking-list-request-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a\x1fgoogle/protobuf/timestamp.proto\x1a*domain/request/common-request-hotels.proto\"\xbf\x01\n" +
	"\x12BookingListRequest\x12Y\n" +
	"\bcriteria\x18\x01 \x01(\v2=.com_bundleport_connect_proto_hotels.CriteriaBookingListInputR\bcriteria\x12N\n" +
	"\bsettings\x18\x02 \x01(\v22.com_bundleport_connect_proto_hotels.SettingsInputR\bsettings\"\xf8\x03\n" +
	"\x18CriteriaBookingListInput\x12\\\n" +
	"\n" +
	"typeSearch\x18\x01 \x01(\x0e2<.com_bundleport_connect_proto_hotels.BookingListCriteriaTypeR\n" +
	"typeSearch\x12^\n" +
	"\n" +
	"references\x18\x02 \x03(\v2>.com_bundleport_connect_proto_hotels.BookingListReferenceInputR\n" +
	"references\x12X\n" +
	"\x05dates\x18\x03 \x01(\v2B.com_bundleport_connect_proto_hotels.CriteriaBookingListDatesInputR\x05dates\x12\x7f\n" +
	"\x10additionalParams\x18\x04 \x03(\v2S.com_bundleport_connect_proto_hotels.CriteriaBookingListInput.AdditionalParamsEntryR\x10additionalParams\x1aC\n" +
	"\x15AdditionalParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc7\x01\n" +
	"\x19BookingListReferenceInput\x12\x1c\n" +
	"\tbookingID\x18\x01 \x01(\tR\tbookingID\x12(\n" +
	"\x0fclientReference\x18\x02 \x01(\tR\x0fclientReference\x12,\n" +
	"\x11providerReference\x18\x03 \x01(\tR\x11providerReference\x124\n" +
	"\x15confirmationReference\x18\x04 \x01(\tR\x15confirmationReference\"\xdd\x01\n" +
	"\x1dCriteriaBookingListDatesInput\x12\\\n" +
	"\bdateType\x18\x01 \x01(\x0e2@.com_bundleport_connect_proto_hotels.BookingListCriteriaDateTypeR\bdateType\x120\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03end*j\n" +
	"\x17BookingListCriteriaType\x12$\n" +
	" BOOKING_LIST_CRITERIA_TYPE_DATES\x10\x00\x12)\n" +
	"%BOOKING_LIST_CRITERIA_TYPE_REFERENCES\x10\x01*w\n" +
	"\x1bBookingListCriteriaDateType\x12+\n" +
	"'BOOKING_LIST_CRITERIA_DATE_TYPE_BOOKING\x10\x00\x12+\n" +
	"'BOOKING_LIST_CRITERIA_DATE_TYPE_ARRIVAL\x10\x01B\x86\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x18BookingListRequestProtosP\x01Z.github.com/bundleport/connect-go-schema/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_request_booking_list_request_hotels_proto_rawDescOnce sync.Once
	file_domain_request_booking_list_request_hotels_proto_rawDescData []byte
)

func file_domain_request_booking_list_request_hotels_proto_rawDescGZIP() []byte {
	file_domain_request_booking_list_request_hotels_proto_rawDescOnce.Do(func() {
		file_domain_request_booking_list_request_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_request_booking_list_request_hotels_proto_rawDesc), len(file_domain_request_booking_list_request_hotels_proto_rawDesc)))
	})
	return file_domain_request_booking_list_request_hotels_proto_rawDescData
}

var file_domain_request_booking_list_request_hotels_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_domain_request_booking_list_request_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_domain_request_booking_list_request_hotels_proto_goTypes = []any{
	(BookingListCriteriaType)(0),          // 0: com_bundleport_connect_proto_hotels.BookingListCriteriaType
	(BookingListCriteriaDateType)(0),      // 1: com_bundleport_connect_proto_hotels.BookingListCriteriaDateType
	(*BookingListRequest)(nil),            // 2: com_bundleport_connect_proto_hotels.BookingListRequest
	(*CriteriaBookingListInput)(nil),      // 3: com_bundleport_connect_proto_hotels.CriteriaBookingListInput
	(*BookingListReferenceInput)(nil),     // 4: com_bundleport_connect_proto_hotels.BookingListReferenceInput
	(*CriteriaBookingListDatesInput)(nil), // 5: com_bundleport_connect_proto_hotels.CriteriaBookingListDatesInput
	nil,                                   // 6: com_bundleport_connect_proto_hotels.CriteriaBookingListInput.AdditionalParamsEntry
	(*SettingsInput)(nil),                 // 7: com_bundleport_connect_proto_hotels.SettingsInput
	(*timestamppb.Timestamp)(nil),         // 8: google.protobuf.Timestamp
}
var file_domain_request_booking_list_request_hotels_proto_depIdxs = []int32{
	3, // 0: com_bundleport_connect_proto_hotels.BookingListRequest.criteria:type_name -> com_bundleport_connect_proto_hotels.CriteriaBookingListInput
	7, // 1: com_bundleport_connect_proto_hotels.BookingListRequest.settings:type_name -> com_bundleport_connect_proto_hotels.SettingsInput
	0, // 2: com_bundleport_connect_proto_hotels.CriteriaBookingListInput.typeSearch:type_name -> com_bundleport_connect_proto_hotels.BookingListCriteriaType
	4, // 3: com_bundleport_connect_proto_hotels.CriteriaBookingListInput.references:type_name -> com_bundleport_connect_proto_hotels.BookingListReferenceInput
	5, // 4: com_bundleport_connect_proto_hotels.CriteriaBookingListInput.dates:type_name -> com_bundleport_connect_proto_hotels.CriteriaBookingListDatesInput
	6, // 5: com_bundleport_connect_proto_hotels.CriteriaBookingListInput.additionalParams:type_name -> com_bundleport_connect_proto_hotels.CriteriaBookingListInput.AdditionalParamsEntry
	1, // 6: com_bundleport_connect_proto_hotels.CriteriaBookingListDatesInput.dateType:type_name -> com_bundleport_connect_proto_hotels.BookingListCriteriaDateType
	8, // 7: com_bundleport_connect_proto_hotels.CriteriaBookingListDatesInput.start:type_name -> google.protobuf.Timestamp
	8, // 8: com_bundleport_connect_proto_hotels.CriteriaBookingListDatesInput.end:type_name -> google.protobuf.Timestamp
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_domain_request_booking_list_request_hotels_proto_init() }
func file_domain_request_booking_list_request_hotels_proto_init() {
	if File_domain_request_booking_list_request_hotels_proto != nil {
		return
	}
	file_domain_request_common_request_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_request_booking_list_request_hotels_proto_rawDesc), len(file_domain_request_booking_list_request_hotels_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_request_booking_list_request_hotels_proto_goTypes,
		DependencyIndexes: file_domain_request_booking_list_request_hotels_proto_depIdxs,
		EnumInfos:         file_domain_request_booking_list_request_hotels_proto_enumTypes,
		MessageInfos:      file_domain_request_booking_list_request_hotels_proto_msgTypes,
	}.Build()
	File_domain_request_booking_list_request_hotels_proto = out.File
	file_domain_request_booking_list_request_hotels_proto_goTypes = nil
	file_domain_request_booking_list_request_hotels_proto_depIdxs = nil
}
