// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/request/cancel-request-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CancelRequest asks providers to cancel an existing booking.
type CancelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cancellation criteria that identify the booking.
	Input *CancelInput `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	// Execution settings shared across aggregator requests.
	Settings      *SettingsInput `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_domain_request_cancel_request_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_cancel_request_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_domain_request_cancel_request_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *CancelRequest) GetInput() *CancelInput {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *CancelRequest) GetSettings() *SettingsInput {
	if x != nil {
		return x.Settings
	}
	return nil
}

// CancelInput identifies the booking to cancel and any additional metadata.
type CancelInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Booking identifier generated by the aggregator.
	BookingID string `protobuf:"bytes,1,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	// Client reference used to correlate the booking externally.
	ClientReference string `protobuf:"bytes,2,opt,name=clientReference,proto3" json:"clientReference,omitempty"`
	// Provider booking reference if already known.
	ProviderReference string `protobuf:"bytes,3,opt,name=providerReference,proto3" json:"providerReference,omitempty"`
	// Provider-specific parameters required to execute the cancellation.
	AdditionalData map[string]string `protobuf:"bytes,4,rep,name=additionalData,proto3" json:"additionalData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelInput) Reset() {
	*x = CancelInput{}
	mi := &file_domain_request_cancel_request_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelInput) ProtoMessage() {}

func (x *CancelInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_cancel_request_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelInput.ProtoReflect.Descriptor instead.
func (*CancelInput) Descriptor() ([]byte, []int) {
	return file_domain_request_cancel_request_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *CancelInput) GetBookingID() string {
	if x != nil {
		return x.BookingID
	}
	return ""
}

func (x *CancelInput) GetClientReference() string {
	if x != nil {
		return x.ClientReference
	}
	return ""
}

func (x *CancelInput) GetProviderReference() string {
	if x != nil {
		return x.ProviderReference
	}
	return ""
}

func (x *CancelInput) GetAdditionalData() map[string]string {
	if x != nil {
		return x.AdditionalData
	}
	return nil
}

var File_domain_request_cancel_request_hotels_proto protoreflect.FileDescriptor

const file_domain_request_cancel_request_hotels_proto_rawDesc = "" +
	"\n" +
	"*domain/request/cancel-request-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a*domain/request/common-request-hotels.proto\"\xa7\x01\n" +
	"\rCancelRequest\x12F\n" +
	"\x05input\x18\x01 \x01(\v20.com_bundleport_connect_proto_hotels.CancelInputR\x05input\x12N\n" +
	"\bsettings\x18\x02 \x01(\v22.com_bundleport_connect_proto_hotels.SettingsInputR\bsettings\"\xb4\x02\n" +
	"\vCancelInput\x12\x1c\n" +
	"\tbookingID\x18\x01 \x01(\tR\tbookingID\x12(\n" +
	"\x0fclientReference\x18\x02 \x01(\tR\x0fclientReference\x12,\n" +
	"\x11providerReference\x18\x03 \x01(\tR\x11providerReference\x12l\n" +
	"\x0eadditionalData\x18\x04 \x03(\v2D.com_bundleport_connect_proto_hotels.CancelInput.AdditionalDataEntryR\x0eadditionalData\x1aA\n" +
	"\x13AdditionalDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x81\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x13CancelRequestProtosP\x01Z.github.com/bundleport/connect-hotels-go/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_request_cancel_request_hotels_proto_rawDescOnce sync.Once
	file_domain_request_cancel_request_hotels_proto_rawDescData []byte
)

func file_domain_request_cancel_request_hotels_proto_rawDescGZIP() []byte {
	file_domain_request_cancel_request_hotels_proto_rawDescOnce.Do(func() {
		file_domain_request_cancel_request_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_request_cancel_request_hotels_proto_rawDesc), len(file_domain_request_cancel_request_hotels_proto_rawDesc)))
	})
	return file_domain_request_cancel_request_hotels_proto_rawDescData
}

var file_domain_request_cancel_request_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_domain_request_cancel_request_hotels_proto_goTypes = []any{
	(*CancelRequest)(nil), // 0: com_bundleport_connect_proto_hotels.CancelRequest
	(*CancelInput)(nil),   // 1: com_bundleport_connect_proto_hotels.CancelInput
	nil,                   // 2: com_bundleport_connect_proto_hotels.CancelInput.AdditionalDataEntry
	(*SettingsInput)(nil), // 3: com_bundleport_connect_proto_hotels.SettingsInput
}
var file_domain_request_cancel_request_hotels_proto_depIdxs = []int32{
	1, // 0: com_bundleport_connect_proto_hotels.CancelRequest.input:type_name -> com_bundleport_connect_proto_hotels.CancelInput
	3, // 1: com_bundleport_connect_proto_hotels.CancelRequest.settings:type_name -> com_bundleport_connect_proto_hotels.SettingsInput
	2, // 2: com_bundleport_connect_proto_hotels.CancelInput.additionalData:type_name -> com_bundleport_connect_proto_hotels.CancelInput.AdditionalDataEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_domain_request_cancel_request_hotels_proto_init() }
func file_domain_request_cancel_request_hotels_proto_init() {
	if File_domain_request_cancel_request_hotels_proto != nil {
		return
	}
	file_domain_request_common_request_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_request_cancel_request_hotels_proto_rawDesc), len(file_domain_request_cancel_request_hotels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_request_cancel_request_hotels_proto_goTypes,
		DependencyIndexes: file_domain_request_cancel_request_hotels_proto_depIdxs,
		MessageInfos:      file_domain_request_cancel_request_hotels_proto_msgTypes,
	}.Build()
	File_domain_request_cancel_request_hotels_proto = out.File
	file_domain_request_cancel_request_hotels_proto_goTypes = nil
	file_domain_request_cancel_request_hotels_proto_depIdxs = nil
}
