// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/response/cancel-response-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CancelStatusType represents the outcome of a cancellation request.
type CancelStatusType int32

const (
	// Cancellation executed successfully.
	CancelStatusType_CANCEL_STATUS_TYPE_OK CancelStatusType = 0
	// Cancellation failed.
	CancelStatusType_CANCEL_STATUS_TYPE_KO CancelStatusType = 1
	// Cancellation status could not be determined.
	CancelStatusType_CANCEL_STATUS_TYPE_UNKNOWN CancelStatusType = 2
)

// Enum value maps for CancelStatusType.
var (
	CancelStatusType_name = map[int32]string{
		0: "CANCEL_STATUS_TYPE_OK",
		1: "CANCEL_STATUS_TYPE_KO",
		2: "CANCEL_STATUS_TYPE_UNKNOWN",
	}
	CancelStatusType_value = map[string]int32{
		"CANCEL_STATUS_TYPE_OK":      0,
		"CANCEL_STATUS_TYPE_KO":      1,
		"CANCEL_STATUS_TYPE_UNKNOWN": 2,
	}
)

func (x CancelStatusType) Enum() *CancelStatusType {
	p := new(CancelStatusType)
	*p = x
	return p
}

func (x CancelStatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CancelStatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_response_cancel_response_hotels_proto_enumTypes[0].Descriptor()
}

func (CancelStatusType) Type() protoreflect.EnumType {
	return &file_domain_response_cancel_response_hotels_proto_enumTypes[0]
}

func (x CancelStatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CancelStatusType.Descriptor instead.
func (CancelStatusType) EnumDescriptor() ([]byte, []int) {
	return file_domain_response_cancel_response_hotels_proto_rawDescGZIP(), []int{0}
}

// CancelResponse returns details about a cancellation operation.
type CancelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request audit information and downstream trace ids.
	AuditData *AuditData `protobuf:"bytes,1,opt,name=auditData,proto3" json:"auditData,omitempty"`
	// Blocking errors encountered while cancelling the booking.
	Errors []*Error `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	// Non-blocking warnings returned alongside the cancellation.
	Warnings []*Warning `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	// Additional debug data for diagnostic purposes.
	DebugData []*TypeValue `protobuf:"bytes,4,rep,name=debugData,proto3" json:"debugData,omitempty"`
	// Provider cancellation reference when available.
	CancelReference string `protobuf:"bytes,5,opt,name=cancelReference,proto3" json:"cancelReference,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_domain_response_cancel_response_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_cancel_response_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_domain_response_cancel_response_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *CancelResponse) GetAuditData() *AuditData {
	if x != nil {
		return x.AuditData
	}
	return nil
}

func (x *CancelResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *CancelResponse) GetWarnings() []*Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *CancelResponse) GetDebugData() []*TypeValue {
	if x != nil {
		return x.DebugData
	}
	return nil
}

func (x *CancelResponse) GetCancelReference() string {
	if x != nil {
		return x.CancelReference
	}
	return ""
}

// CancelDetail summarises a cancellation status and related data.
type CancelDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resulting cancellation status.
	Status CancelStatusType `protobuf:"varint,1,opt,name=status,proto3,enum=com_bundleport_connect_proto_hotels.CancelStatusType" json:"status,omitempty"`
	// Booking references returned by the provider.
	Reference *Reference `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	// Refund amount when the provider supplies it.
	RefundAmount *Price `protobuf:"bytes,3,opt,name=refundAmount,proto3" json:"refundAmount,omitempty"`
	// Additional remarks from the provider.
	Remarks       []*TypeValue `protobuf:"bytes,4,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelDetail) Reset() {
	*x = CancelDetail{}
	mi := &file_domain_response_cancel_response_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelDetail) ProtoMessage() {}

func (x *CancelDetail) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_cancel_response_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelDetail.ProtoReflect.Descriptor instead.
func (*CancelDetail) Descriptor() ([]byte, []int) {
	return file_domain_response_cancel_response_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *CancelDetail) GetStatus() CancelStatusType {
	if x != nil {
		return x.Status
	}
	return CancelStatusType_CANCEL_STATUS_TYPE_OK
}

func (x *CancelDetail) GetReference() *Reference {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *CancelDetail) GetRefundAmount() *Price {
	if x != nil {
		return x.RefundAmount
	}
	return nil
}

func (x *CancelDetail) GetRemarks() []*TypeValue {
	if x != nil {
		return x.Remarks
	}
	return nil
}

var File_domain_response_cancel_response_hotels_proto protoreflect.FileDescriptor

const file_domain_response_cancel_response_hotels_proto_rawDesc = "" +
	"\n" +
	",domain/response/cancel-response-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a,domain/response/common-response-hotels.proto\"\xe4\x02\n" +
	"\x0eCancelResponse\x12L\n" +
	"\tauditData\x18\x01 \x01(\v2..com_bundleport_connect_proto_hotels.AuditDataR\tauditData\x12B\n" +
	"\x06errors\x18\x02 \x03(\v2*.com_bundleport_connect_proto_hotels.ErrorR\x06errors\x12H\n" +
	"\bwarnings\x18\x03 \x03(\v2,.com_bundleport_connect_proto_hotels.WarningR\bwarnings\x12L\n" +
	"\tdebugData\x18\x04 \x03(\v2..com_bundleport_connect_proto_hotels.TypeValueR\tdebugData\x12(\n" +
	"\x0fcancelReference\x18\x05 \x01(\tR\x0fcancelReference\"\xc5\x02\n" +
	"\fCancelDetail\x12M\n" +
	"\x06status\x18\x01 \x01(\x0e25.com_bundleport_connect_proto_hotels.CancelStatusTypeR\x06status\x12L\n" +
	"\treference\x18\x02 \x01(\v2..com_bundleport_connect_proto_hotels.ReferenceR\treference\x12N\n" +
	"\frefundAmount\x18\x03 \x01(\v2*.com_bundleport_connect_proto_hotels.PriceR\frefundAmount\x12H\n" +
	"\aremarks\x18\x04 \x03(\v2..com_bundleport_connect_proto_hotels.TypeValueR\aremarks*h\n" +
	"\x10CancelStatusType\x12\x19\n" +
	"\x15CANCEL_STATUS_TYPE_OK\x10\x00\x12\x19\n" +
	"\x15CANCEL_STATUS_TYPE_KO\x10\x01\x12\x1e\n" +
	"\x1aCANCEL_STATUS_TYPE_UNKNOWN\x10\x02B\x82\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x14CancelResponseProtosP\x01Z.github.com/bundleport/connect-hotels-go/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_response_cancel_response_hotels_proto_rawDescOnce sync.Once
	file_domain_response_cancel_response_hotels_proto_rawDescData []byte
)

func file_domain_response_cancel_response_hotels_proto_rawDescGZIP() []byte {
	file_domain_response_cancel_response_hotels_proto_rawDescOnce.Do(func() {
		file_domain_response_cancel_response_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_response_cancel_response_hotels_proto_rawDesc), len(file_domain_response_cancel_response_hotels_proto_rawDesc)))
	})
	return file_domain_response_cancel_response_hotels_proto_rawDescData
}

var file_domain_response_cancel_response_hotels_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_domain_response_cancel_response_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_domain_response_cancel_response_hotels_proto_goTypes = []any{
	(CancelStatusType)(0),  // 0: com_bundleport_connect_proto_hotels.CancelStatusType
	(*CancelResponse)(nil), // 1: com_bundleport_connect_proto_hotels.CancelResponse
	(*CancelDetail)(nil),   // 2: com_bundleport_connect_proto_hotels.CancelDetail
	(*AuditData)(nil),      // 3: com_bundleport_connect_proto_hotels.AuditData
	(*Error)(nil),          // 4: com_bundleport_connect_proto_hotels.Error
	(*Warning)(nil),        // 5: com_bundleport_connect_proto_hotels.Warning
	(*TypeValue)(nil),      // 6: com_bundleport_connect_proto_hotels.TypeValue
	(*Reference)(nil),      // 7: com_bundleport_connect_proto_hotels.Reference
	(*Price)(nil),          // 8: com_bundleport_connect_proto_hotels.Price
}
var file_domain_response_cancel_response_hotels_proto_depIdxs = []int32{
	3, // 0: com_bundleport_connect_proto_hotels.CancelResponse.auditData:type_name -> com_bundleport_connect_proto_hotels.AuditData
	4, // 1: com_bundleport_connect_proto_hotels.CancelResponse.errors:type_name -> com_bundleport_connect_proto_hotels.Error
	5, // 2: com_bundleport_connect_proto_hotels.CancelResponse.warnings:type_name -> com_bundleport_connect_proto_hotels.Warning
	6, // 3: com_bundleport_connect_proto_hotels.CancelResponse.debugData:type_name -> com_bundleport_connect_proto_hotels.TypeValue
	0, // 4: com_bundleport_connect_proto_hotels.CancelDetail.status:type_name -> com_bundleport_connect_proto_hotels.CancelStatusType
	7, // 5: com_bundleport_connect_proto_hotels.CancelDetail.reference:type_name -> com_bundleport_connect_proto_hotels.Reference
	8, // 6: com_bundleport_connect_proto_hotels.CancelDetail.refundAmount:type_name -> com_bundleport_connect_proto_hotels.Price
	6, // 7: com_bundleport_connect_proto_hotels.CancelDetail.remarks:type_name -> com_bundleport_connect_proto_hotels.TypeValue
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_domain_response_cancel_response_hotels_proto_init() }
func file_domain_response_cancel_response_hotels_proto_init() {
	if File_domain_response_cancel_response_hotels_proto != nil {
		return
	}
	file_domain_response_common_response_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_response_cancel_response_hotels_proto_rawDesc), len(file_domain_response_cancel_response_hotels_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_response_cancel_response_hotels_proto_goTypes,
		DependencyIndexes: file_domain_response_cancel_response_hotels_proto_depIdxs,
		EnumInfos:         file_domain_response_cancel_response_hotels_proto_enumTypes,
		MessageInfos:      file_domain_response_cancel_response_hotels_proto_msgTypes,
	}.Build()
	File_domain_response_cancel_response_hotels_proto = out.File
	file_domain_response_cancel_response_hotels_proto_goTypes = nil
	file_domain_response_cancel_response_hotels_proto_depIdxs = nil
}
