// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/response/categories-response-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetCategoriesResponse returns category metadata for the requested scope.
type GetCategoriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request audit information and downstream trace ids.
	AuditData *AuditData `protobuf:"bytes,1,opt,name=auditData,proto3" json:"auditData,omitempty"`
	// Blocking errors encountered while fetching categories.
	Errors []*Error `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	// Non-blocking warnings returned alongside the category data.
	Warnings []*Warning `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	// Additional debug data for diagnostic purposes.
	DebugData []*TypeValue `protobuf:"bytes,4,rep,name=debugData,proto3" json:"debugData,omitempty"`
	// Category entries that matched the request criteria.
	Categories []*CategoryData `protobuf:"bytes,5,rep,name=categories,proto3" json:"categories,omitempty"`
	// Pagination token to request the next category page.
	Token         string `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesResponse) Reset() {
	*x = GetCategoriesResponse{}
	mi := &file_domain_response_categories_response_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesResponse) ProtoMessage() {}

func (x *GetCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_categories_response_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_domain_response_categories_response_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *GetCategoriesResponse) GetAuditData() *AuditData {
	if x != nil {
		return x.AuditData
	}
	return nil
}

func (x *GetCategoriesResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *GetCategoriesResponse) GetWarnings() []*Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *GetCategoriesResponse) GetDebugData() []*TypeValue {
	if x != nil {
		return x.DebugData
	}
	return nil
}

func (x *GetCategoriesResponse) GetCategories() []*CategoryData {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *GetCategoriesResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// CategoryData contains basic descriptive information about a category.
type CategoryData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider or aggregator category code.
	CategoryCode string `protobuf:"bytes,2,opt,name=categoryCode,proto3" json:"categoryCode,omitempty"`
	// Category description in the specified language.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// ISO 639-1 language code for the description.
	Language      string `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryData) Reset() {
	*x = CategoryData{}
	mi := &file_domain_response_categories_response_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryData) ProtoMessage() {}

func (x *CategoryData) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_categories_response_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryData.ProtoReflect.Descriptor instead.
func (*CategoryData) Descriptor() ([]byte, []int) {
	return file_domain_response_categories_response_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *CategoryData) GetCategoryCode() string {
	if x != nil {
		return x.CategoryCode
	}
	return ""
}

func (x *CategoryData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CategoryData) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

var File_domain_response_categories_response_hotels_proto protoreflect.FileDescriptor

const file_domain_response_categories_response_hotels_proto_rawDesc = "" +
	"\n" +
	"0domain/response/categories-response-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a,domain/response/common-response-hotels.proto\"\xaa\x03\n" +
	"\x15GetCategoriesResponse\x12L\n" +
	"\tauditData\x18\x01 \x01(\v2..com_bundleport_connect_proto_hotels.AuditDataR\tauditData\x12B\n" +
	"\x06errors\x18\x02 \x03(\v2*.com_bundleport_connect_proto_hotels.ErrorR\x06errors\x12H\n" +
	"\bwarnings\x18\x03 \x03(\v2,.com_bundleport_connect_proto_hotels.WarningR\bwarnings\x12L\n" +
	"\tdebugData\x18\x04 \x03(\v2..com_bundleport_connect_proto_hotels.TypeValueR\tdebugData\x12Q\n" +
	"\n" +
	"categories\x18\x05 \x03(\v21.com_bundleport_connect_proto_hotels.CategoryDataR\n" +
	"categories\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\"p\n" +
	"\fCategoryData\x12\"\n" +
	"\fcategoryCode\x18\x02 \x01(\tR\fcategoryCode\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguageB\x86\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x18CategoriesResponseProtosP\x01Z.github.com/bundleport/connect-hotels-go/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_response_categories_response_hotels_proto_rawDescOnce sync.Once
	file_domain_response_categories_response_hotels_proto_rawDescData []byte
)

func file_domain_response_categories_response_hotels_proto_rawDescGZIP() []byte {
	file_domain_response_categories_response_hotels_proto_rawDescOnce.Do(func() {
		file_domain_response_categories_response_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_response_categories_response_hotels_proto_rawDesc), len(file_domain_response_categories_response_hotels_proto_rawDesc)))
	})
	return file_domain_response_categories_response_hotels_proto_rawDescData
}

var file_domain_response_categories_response_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_domain_response_categories_response_hotels_proto_goTypes = []any{
	(*GetCategoriesResponse)(nil), // 0: com_bundleport_connect_proto_hotels.GetCategoriesResponse
	(*CategoryData)(nil),          // 1: com_bundleport_connect_proto_hotels.CategoryData
	(*AuditData)(nil),             // 2: com_bundleport_connect_proto_hotels.AuditData
	(*Error)(nil),                 // 3: com_bundleport_connect_proto_hotels.Error
	(*Warning)(nil),               // 4: com_bundleport_connect_proto_hotels.Warning
	(*TypeValue)(nil),             // 5: com_bundleport_connect_proto_hotels.TypeValue
}
var file_domain_response_categories_response_hotels_proto_depIdxs = []int32{
	2, // 0: com_bundleport_connect_proto_hotels.GetCategoriesResponse.auditData:type_name -> com_bundleport_connect_proto_hotels.AuditData
	3, // 1: com_bundleport_connect_proto_hotels.GetCategoriesResponse.errors:type_name -> com_bundleport_connect_proto_hotels.Error
	4, // 2: com_bundleport_connect_proto_hotels.GetCategoriesResponse.warnings:type_name -> com_bundleport_connect_proto_hotels.Warning
	5, // 3: com_bundleport_connect_proto_hotels.GetCategoriesResponse.debugData:type_name -> com_bundleport_connect_proto_hotels.TypeValue
	1, // 4: com_bundleport_connect_proto_hotels.GetCategoriesResponse.categories:type_name -> com_bundleport_connect_proto_hotels.CategoryData
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_domain_response_categories_response_hotels_proto_init() }
func file_domain_response_categories_response_hotels_proto_init() {
	if File_domain_response_categories_response_hotels_proto != nil {
		return
	}
	file_domain_response_common_response_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_response_categories_response_hotels_proto_rawDesc), len(file_domain_response_categories_response_hotels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_response_categories_response_hotels_proto_goTypes,
		DependencyIndexes: file_domain_response_categories_response_hotels_proto_depIdxs,
		MessageInfos:      file_domain_response_categories_response_hotels_proto_msgTypes,
	}.Build()
	File_domain_response_categories_response_hotels_proto = out.File
	file_domain_response_categories_response_hotels_proto_goTypes = nil
	file_domain_response_categories_response_hotels_proto_depIdxs = nil
}
