// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/request/common-request-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PersonalTitleType enumerates supported courtesy titles.
type PersonalTitleType int32

const (
	// Courtesy title for male travellers.
	PersonalTitleType_MR PersonalTitleType = 0
	// Courtesy title for married female travellers.
	PersonalTitleType_MRS PersonalTitleType = 1
	// Courtesy title for unmarried female travellers.
	PersonalTitleType_MISS PersonalTitleType = 2
	// Courtesy title for female travellers where marital status is unknown.
	PersonalTitleType_MS PersonalTitleType = 3
	// Title not provided by the caller.
	PersonalTitleType_NOT_SPECIFIED PersonalTitleType = 4
)

// Enum value maps for PersonalTitleType.
var (
	PersonalTitleType_name = map[int32]string{
		0: "MR",
		1: "MRS",
		2: "MISS",
		3: "MS",
		4: "NOT_SPECIFIED",
	}
	PersonalTitleType_value = map[string]int32{
		"MR":            0,
		"MRS":           1,
		"MISS":          2,
		"MS":            3,
		"NOT_SPECIFIED": 4,
	}
)

func (x PersonalTitleType) Enum() *PersonalTitleType {
	p := new(PersonalTitleType)
	*p = x
	return p
}

func (x PersonalTitleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PersonalTitleType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_request_common_request_hotels_proto_enumTypes[0].Descriptor()
}

func (PersonalTitleType) Type() protoreflect.EnumType {
	return &file_domain_request_common_request_hotels_proto_enumTypes[0]
}

func (x PersonalTitleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PersonalTitleType.Descriptor instead.
func (PersonalTitleType) EnumDescriptor() ([]byte, []int) {
	return file_domain_request_common_request_hotels_proto_rawDescGZIP(), []int{0}
}

// SettingsInput captures the execution context used across aggregator requests.
type SettingsInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier used to correlate downstream provider calls and responses.
	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	// Provider access identifiers that the request should target.
	AccessIds []string `protobuf:"bytes,2,rep,name=accessIds,proto3" json:"accessIds,omitempty"`
	// Point of sale information for commercial routing.
	Pos *PointOfSale `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`
	// When true, raw provider transactions are collected for auditing.
	AuditTransactions bool `protobuf:"varint,4,opt,name=auditTransactions,proto3" json:"auditTransactions,omitempty"`
	// Maximum time in milliseconds allowed for the aggregator to respond.
	Timeout int32 `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Enables sandbox flows where providers expose dedicated mock behaviour.
	TestMode bool `protobuf:"varint,6,opt,name=testMode,proto3" json:"testMode,omitempty"`
	// Enables diagnostic payloads that surface debug data in responses.
	DebugData bool `protobuf:"varint,7,opt,name=debugData,proto3" json:"debugData,omitempty"`
	// Token that propagates caller authentication to downstream services.
	Token         string `protobuf:"bytes,8,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsInput) Reset() {
	*x = SettingsInput{}
	mi := &file_domain_request_common_request_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsInput) ProtoMessage() {}

func (x *SettingsInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_common_request_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsInput.ProtoReflect.Descriptor instead.
func (*SettingsInput) Descriptor() ([]byte, []int) {
	return file_domain_request_common_request_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *SettingsInput) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SettingsInput) GetAccessIds() []string {
	if x != nil {
		return x.AccessIds
	}
	return nil
}

func (x *SettingsInput) GetPos() *PointOfSale {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *SettingsInput) GetAuditTransactions() bool {
	if x != nil {
		return x.AuditTransactions
	}
	return false
}

func (x *SettingsInput) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *SettingsInput) GetTestMode() bool {
	if x != nil {
		return x.TestMode
	}
	return false
}

func (x *SettingsInput) GetDebugData() bool {
	if x != nil {
		return x.DebugData
	}
	return false
}

func (x *SettingsInput) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// PointOfSale represents the commercial point generating the request.
type PointOfSale struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Branch or office that originated the enquiry, when available.
	BranchOffice  string `protobuf:"bytes,1,opt,name=branchOffice,proto3" json:"branchOffice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointOfSale) Reset() {
	*x = PointOfSale{}
	mi := &file_domain_request_common_request_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointOfSale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointOfSale) ProtoMessage() {}

func (x *PointOfSale) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_common_request_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointOfSale.ProtoReflect.Descriptor instead.
func (*PointOfSale) Descriptor() ([]byte, []int) {
	return file_domain_request_common_request_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *PointOfSale) GetBranchOffice() string {
	if x != nil {
		return x.BranchOffice
	}
	return ""
}

// ContactInfoInput contains contact details for travellers or holders.
type ContactInfoInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Primary email address that providers can use for notifications.
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Traveller phone information for confirmations or alerts.
	Phone *PhoneInput `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	// Street address of the contact person.
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	// City associated with the contact address.
	City string `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	// Country ISO code associated with the contact address.
	Country string `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	// Postal or ZIP code associated with the contact address.
	PostalCode    string `protobuf:"bytes,6,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactInfoInput) Reset() {
	*x = ContactInfoInput{}
	mi := &file_domain_request_common_request_hotels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactInfoInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactInfoInput) ProtoMessage() {}

func (x *ContactInfoInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_common_request_hotels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactInfoInput.ProtoReflect.Descriptor instead.
func (*ContactInfoInput) Descriptor() ([]byte, []int) {
	return file_domain_request_common_request_hotels_proto_rawDescGZIP(), []int{2}
}

func (x *ContactInfoInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ContactInfoInput) GetPhone() *PhoneInput {
	if x != nil {
		return x.Phone
	}
	return nil
}

func (x *ContactInfoInput) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ContactInfoInput) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ContactInfoInput) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ContactInfoInput) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

// PhoneInput stores a structured phone number.
type PhoneInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// International country dialling prefix without the plus sign.
	CountryCode string `protobuf:"bytes,1,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	// Subscriber number excluding the country code.
	Number        string `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneInput) Reset() {
	*x = PhoneInput{}
	mi := &file_domain_request_common_request_hotels_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneInput) ProtoMessage() {}

func (x *PhoneInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_common_request_hotels_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneInput.ProtoReflect.Descriptor instead.
func (*PhoneInput) Descriptor() ([]byte, []int) {
	return file_domain_request_common_request_hotels_proto_rawDescGZIP(), []int{3}
}

func (x *PhoneInput) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *PhoneInput) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

// HolderInput identifies the booking holder entity.
type HolderInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Holder given name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Holder family name.
	Surname string `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	// Courtesy title for the holder.
	Title PersonalTitleType `protobuf:"varint,3,opt,name=title,proto3,enum=com_bundleport_connect_proto_hotels.PersonalTitleType" json:"title,omitempty"`
	// Contact details for the holder.
	ContactInfo   *ContactInfoInput `protobuf:"bytes,4,opt,name=contactInfo,proto3" json:"contactInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HolderInput) Reset() {
	*x = HolderInput{}
	mi := &file_domain_request_common_request_hotels_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderInput) ProtoMessage() {}

func (x *HolderInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_common_request_hotels_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolderInput.ProtoReflect.Descriptor instead.
func (*HolderInput) Descriptor() ([]byte, []int) {
	return file_domain_request_common_request_hotels_proto_rawDescGZIP(), []int{4}
}

func (x *HolderInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HolderInput) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *HolderInput) GetTitle() PersonalTitleType {
	if x != nil {
		return x.Title
	}
	return PersonalTitleType_MR
}

func (x *HolderInput) GetContactInfo() *ContactInfoInput {
	if x != nil {
		return x.ContactInfo
	}
	return nil
}

// ExpireDateInput represents a month/year expiry combination.
type ExpireDateInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Expiry month expressed from 1 to 12.
	Month int32 `protobuf:"varint,1,opt,name=month,proto3" json:"month,omitempty"`
	// Expiry year expressed with four digits.
	Year          int32 `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireDateInput) Reset() {
	*x = ExpireDateInput{}
	mi := &file_domain_request_common_request_hotels_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireDateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireDateInput) ProtoMessage() {}

func (x *ExpireDateInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_common_request_hotels_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireDateInput.ProtoReflect.Descriptor instead.
func (*ExpireDateInput) Descriptor() ([]byte, []int) {
	return file_domain_request_common_request_hotels_proto_rawDescGZIP(), []int{5}
}

func (x *ExpireDateInput) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *ExpireDateInput) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

// PaginationInput limits the range of requested results.
type PaginationInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Starting index (inclusive) of the result window.
	From int32 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	// Ending index (exclusive) of the result window.
	To            int32 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationInput) Reset() {
	*x = PaginationInput{}
	mi := &file_domain_request_common_request_hotels_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationInput) ProtoMessage() {}

func (x *PaginationInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_common_request_hotels_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationInput.ProtoReflect.Descriptor instead.
func (*PaginationInput) Descriptor() ([]byte, []int) {
	return file_domain_request_common_request_hotels_proto_rawDescGZIP(), []int{6}
}

func (x *PaginationInput) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *PaginationInput) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

// Exclusion points to hotel elements that must be filtered out by providers.
type Exclusion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of element being excluded (for example HOTEL or ROOM).
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Identifier or field associated with the exclusion type.
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Values that should be excluded for the given type/key combination.
	Values        []string `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exclusion) Reset() {
	*x = Exclusion{}
	mi := &file_domain_request_common_request_hotels_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exclusion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exclusion) ProtoMessage() {}

func (x *Exclusion) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_common_request_hotels_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exclusion.ProtoReflect.Descriptor instead.
func (*Exclusion) Descriptor() ([]byte, []int) {
	return file_domain_request_common_request_hotels_proto_rawDescGZIP(), []int{7}
}

func (x *Exclusion) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Exclusion) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Exclusion) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_domain_request_common_request_hotels_proto protoreflect.FileDescriptor

const file_domain_request_common_request_hotels_proto_rawDesc = "" +
	"\n" +
	"*domain/request/common-request-hotels.proto\x12#com_bundleport_connect_proto_hotels\"\xa7\x02\n" +
	"\rSettingsInput\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\taccessIds\x18\x02 \x03(\tR\taccessIds\x12B\n" +
	"\x03pos\x18\x03 \x01(\v20.com_bundleport_connect_proto_hotels.PointOfSaleR\x03pos\x12,\n" +
	"\x11auditTransactions\x18\x04 \x01(\bR\x11auditTransactions\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\x05R\atimeout\x12\x1a\n" +
	"\btestMode\x18\x06 \x01(\bR\btestMode\x12\x1c\n" +
	"\tdebugData\x18\a \x01(\bR\tdebugData\x12\x14\n" +
	"\x05token\x18\b \x01(\tR\x05token\"1\n" +
	"\vPointOfSale\x12\"\n" +
	"\fbranchOffice\x18\x01 \x01(\tR\fbranchOffice\"\xd7\x01\n" +
	"\x10ContactInfoInput\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12E\n" +
	"\x05phone\x18\x02 \x01(\v2/.com_bundleport_connect_proto_hotels.PhoneInputR\x05phone\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x1e\n" +
	"\n" +
	"postalCode\x18\x06 \x01(\tR\n" +
	"postalCode\"F\n" +
	"\n" +
	"PhoneInput\x12 \n" +
	"\vcountryCode\x18\x01 \x01(\tR\vcountryCode\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\"\xe2\x01\n" +
	"\vHolderInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x02 \x01(\tR\asurname\x12L\n" +
	"\x05title\x18\x03 \x01(\x0e26.com_bundleport_connect_proto_hotels.PersonalTitleTypeR\x05title\x12W\n" +
	"\vcontactInfo\x18\x04 \x01(\v25.com_bundleport_connect_proto_hotels.ContactInfoInputR\vcontactInfo\";\n" +
	"\x0fExpireDateInput\x12\x14\n" +
	"\x05month\x18\x01 \x01(\x05R\x05month\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\"5\n" +
	"\x0fPaginationInput\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x05R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x05R\x02to\"I\n" +
	"\tExclusion\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x03 \x03(\tR\x06values*I\n" +
	"\x11PersonalTitleType\x12\x06\n" +
	"\x02MR\x10\x00\x12\a\n" +
	"\x03MRS\x10\x01\x12\b\n" +
	"\x04MISS\x10\x02\x12\x06\n" +
	"\x02MS\x10\x03\x12\x11\n" +
	"\rNOT_SPECIFIED\x10\x04B\x81\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x13CommonRequestProtosP\x01Z.github.com/bundleport/connect-hotels-go/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_request_common_request_hotels_proto_rawDescOnce sync.Once
	file_domain_request_common_request_hotels_proto_rawDescData []byte
)

func file_domain_request_common_request_hotels_proto_rawDescGZIP() []byte {
	file_domain_request_common_request_hotels_proto_rawDescOnce.Do(func() {
		file_domain_request_common_request_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_request_common_request_hotels_proto_rawDesc), len(file_domain_request_common_request_hotels_proto_rawDesc)))
	})
	return file_domain_request_common_request_hotels_proto_rawDescData
}

var file_domain_request_common_request_hotels_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_domain_request_common_request_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_domain_request_common_request_hotels_proto_goTypes = []any{
	(PersonalTitleType)(0),   // 0: com_bundleport_connect_proto_hotels.PersonalTitleType
	(*SettingsInput)(nil),    // 1: com_bundleport_connect_proto_hotels.SettingsInput
	(*PointOfSale)(nil),      // 2: com_bundleport_connect_proto_hotels.PointOfSale
	(*ContactInfoInput)(nil), // 3: com_bundleport_connect_proto_hotels.ContactInfoInput
	(*PhoneInput)(nil),       // 4: com_bundleport_connect_proto_hotels.PhoneInput
	(*HolderInput)(nil),      // 5: com_bundleport_connect_proto_hotels.HolderInput
	(*ExpireDateInput)(nil),  // 6: com_bundleport_connect_proto_hotels.ExpireDateInput
	(*PaginationInput)(nil),  // 7: com_bundleport_connect_proto_hotels.PaginationInput
	(*Exclusion)(nil),        // 8: com_bundleport_connect_proto_hotels.Exclusion
}
var file_domain_request_common_request_hotels_proto_depIdxs = []int32{
	2, // 0: com_bundleport_connect_proto_hotels.SettingsInput.pos:type_name -> com_bundleport_connect_proto_hotels.PointOfSale
	4, // 1: com_bundleport_connect_proto_hotels.ContactInfoInput.phone:type_name -> com_bundleport_connect_proto_hotels.PhoneInput
	0, // 2: com_bundleport_connect_proto_hotels.HolderInput.title:type_name -> com_bundleport_connect_proto_hotels.PersonalTitleType
	3, // 3: com_bundleport_connect_proto_hotels.HolderInput.contactInfo:type_name -> com_bundleport_connect_proto_hotels.ContactInfoInput
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_domain_request_common_request_hotels_proto_init() }
func file_domain_request_common_request_hotels_proto_init() {
	if File_domain_request_common_request_hotels_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_request_common_request_hotels_proto_rawDesc), len(file_domain_request_common_request_hotels_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_request_common_request_hotels_proto_goTypes,
		DependencyIndexes: file_domain_request_common_request_hotels_proto_depIdxs,
		EnumInfos:         file_domain_request_common_request_hotels_proto_enumTypes,
		MessageInfos:      file_domain_request_common_request_hotels_proto_msgTypes,
	}.Build()
	File_domain_request_common_request_hotels_proto = out.File
	file_domain_request_common_request_hotels_proto_goTypes = nil
	file_domain_request_common_request_hotels_proto_depIdxs = nil
}
