// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/response/content-response-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Text stores localised text values.
type Text struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Translated text value.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// ISO 639-1 language code for the text.
	Language      string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_domain_response_content_response_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_content_response_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_domain_response_content_response_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *Text) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Text) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// Description represents localised descriptive content for a resource.
type Description struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of description such as short, long or location.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Localised texts for the description.
	Texts         []*Text `protobuf:"bytes,2,rep,name=texts,proto3" json:"texts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Description) Reset() {
	*x = Description{}
	mi := &file_domain_response_content_response_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Description) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Description) ProtoMessage() {}

func (x *Description) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_content_response_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Description.ProtoReflect.Descriptor instead.
func (*Description) Descriptor() ([]byte, []int) {
	return file_domain_response_content_response_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *Description) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Description) GetTexts() []*Text {
	if x != nil {
		return x.Texts
	}
	return nil
}

// Media contains metadata for images, videos or documents.
type Media struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider media code.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Display order used when rendering the media.
	Order string `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	// Media type (for example IMAGE or VIDEO).
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Timestamp of the last update.
	UpdatedAt string `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	// Public URL where the media can be downloaded.
	Url string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	// Localised captions or descriptions.
	Texts         []*Text `protobuf:"bytes,6,rep,name=texts,proto3" json:"texts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_domain_response_content_response_hotels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_content_response_hotels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_domain_response_content_response_hotels_proto_rawDescGZIP(), []int{2}
}

func (x *Media) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Media) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *Media) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Media) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Media) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Media) GetTexts() []*Text {
	if x != nil {
		return x.Texts
	}
	return nil
}

// GiataData stores references to Giata content when available.
type GiataData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Giata identifier associated with the resource.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Source type such as hotel or room.
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// Giata URL referencing the resource record.
	Href string `protobuf:"bytes,3,opt,name=href,proto3" json:"href,omitempty"`
	// Timestamp of the last update received from Giata.
	UpdatedAt     string `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GiataData) Reset() {
	*x = GiataData{}
	mi := &file_domain_response_content_response_hotels_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiataData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiataData) ProtoMessage() {}

func (x *GiataData) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_content_response_hotels_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiataData.ProtoReflect.Descriptor instead.
func (*GiataData) Descriptor() ([]byte, []int) {
	return file_domain_response_content_response_hotels_proto_rawDescGZIP(), []int{3}
}

func (x *GiataData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GiataData) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GiataData) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *GiataData) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_domain_response_content_response_hotels_proto protoreflect.FileDescriptor

const file_domain_response_content_response_hotels_proto_rawDesc = "" +
	"\n" +
	"-domain/response/content-response-hotels.proto\x12#com_bundleport_connect_proto_hotels\"6\n" +
	"\x04Text\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"b\n" +
	"\vDescription\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12?\n" +
	"\x05texts\x18\x02 \x03(\v2).com_bundleport_connect_proto_hotels.TextR\x05texts\"\xb6\x01\n" +
	"\x05Media\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05order\x18\x02 \x01(\tR\x05order\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1c\n" +
	"\tupdatedAt\x18\x04 \x01(\tR\tupdatedAt\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12?\n" +
	"\x05texts\x18\x06 \x03(\v2).com_bundleport_connect_proto_hotels.TextR\x05texts\"e\n" +
	"\tGiataData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x12\n" +
	"\x04href\x18\x03 \x01(\tR\x04href\x12\x1c\n" +
	"\tupdatedAt\x18\x04 \x01(\tR\tupdatedAtB\x83\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x15ContentResponseProtosP\x01Z.github.com/bundleport/connect-go-schema/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_response_content_response_hotels_proto_rawDescOnce sync.Once
	file_domain_response_content_response_hotels_proto_rawDescData []byte
)

func file_domain_response_content_response_hotels_proto_rawDescGZIP() []byte {
	file_domain_response_content_response_hotels_proto_rawDescOnce.Do(func() {
		file_domain_response_content_response_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_response_content_response_hotels_proto_rawDesc), len(file_domain_response_content_response_hotels_proto_rawDesc)))
	})
	return file_domain_response_content_response_hotels_proto_rawDescData
}

var file_domain_response_content_response_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_domain_response_content_response_hotels_proto_goTypes = []any{
	(*Text)(nil),        // 0: com_bundleport_connect_proto_hotels.Text
	(*Description)(nil), // 1: com_bundleport_connect_proto_hotels.Description
	(*Media)(nil),       // 2: com_bundleport_connect_proto_hotels.Media
	(*GiataData)(nil),   // 3: com_bundleport_connect_proto_hotels.GiataData
}
var file_domain_response_content_response_hotels_proto_depIdxs = []int32{
	0, // 0: com_bundleport_connect_proto_hotels.Description.texts:type_name -> com_bundleport_connect_proto_hotels.Text
	0, // 1: com_bundleport_connect_proto_hotels.Media.texts:type_name -> com_bundleport_connect_proto_hotels.Text
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_domain_response_content_response_hotels_proto_init() }
func file_domain_response_content_response_hotels_proto_init() {
	if File_domain_response_content_response_hotels_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_response_content_response_hotels_proto_rawDesc), len(file_domain_response_content_response_hotels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_response_content_response_hotels_proto_goTypes,
		DependencyIndexes: file_domain_response_content_response_hotels_proto_depIdxs,
		MessageInfos:      file_domain_response_content_response_hotels_proto_msgTypes,
	}.Build()
	File_domain_response_content_response_hotels_proto = out.File
	file_domain_response_content_response_hotels_proto_goTypes = nil
	file_domain_response_content_response_hotels_proto_depIdxs = nil
}
