// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/request/destinations-request-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetDestinationsRequest retrieves catalogued destinations.
type GetDestinationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filters describing which destinations to return.
	Criteria *DestinationQueryCriteria `protobuf:"bytes,1,opt,name=criteria,proto3" json:"criteria,omitempty"`
	// Execution settings shared across aggregator requests.
	Settings      *SettingsInput `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDestinationsRequest) Reset() {
	*x = GetDestinationsRequest{}
	mi := &file_domain_request_destinations_request_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDestinationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDestinationsRequest) ProtoMessage() {}

func (x *GetDestinationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_destinations_request_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDestinationsRequest.ProtoReflect.Descriptor instead.
func (*GetDestinationsRequest) Descriptor() ([]byte, []int) {
	return file_domain_request_destinations_request_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *GetDestinationsRequest) GetCriteria() *DestinationQueryCriteria {
	if x != nil {
		return x.Criteria
	}
	return nil
}

func (x *GetDestinationsRequest) GetSettings() *SettingsInput {
	if x != nil {
		return x.Settings
	}
	return nil
}

// SearchDestinationsRequest performs a text search on destinations.
type SearchDestinationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Search term criteria used to match destinations.
	Criteria *DestinationSearchCriteria `protobuf:"bytes,1,opt,name=criteria,proto3" json:"criteria,omitempty"`
	// Execution settings shared across aggregator requests.
	Settings      *SettingsInput `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchDestinationsRequest) Reset() {
	*x = SearchDestinationsRequest{}
	mi := &file_domain_request_destinations_request_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDestinationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDestinationsRequest) ProtoMessage() {}

func (x *SearchDestinationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_destinations_request_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDestinationsRequest.ProtoReflect.Descriptor instead.
func (*SearchDestinationsRequest) Descriptor() ([]byte, []int) {
	return file_domain_request_destinations_request_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *SearchDestinationsRequest) GetCriteria() *DestinationSearchCriteria {
	if x != nil {
		return x.Criteria
	}
	return nil
}

func (x *SearchDestinationsRequest) GetSettings() *SettingsInput {
	if x != nil {
		return x.Settings
	}
	return nil
}

// DestinationQueryCriteria narrows destination retrieval by codes and language.
type DestinationQueryCriteria struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Destination codes to include; empty to retrieve all.
	DestinationCodes []string `protobuf:"bytes,1,rep,name=destinationCodes,proto3" json:"destinationCodes,omitempty"`
	// ISO 639-1 language code for destination descriptions.
	Language      string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestinationQueryCriteria) Reset() {
	*x = DestinationQueryCriteria{}
	mi := &file_domain_request_destinations_request_hotels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestinationQueryCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestinationQueryCriteria) ProtoMessage() {}

func (x *DestinationQueryCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_destinations_request_hotels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestinationQueryCriteria.ProtoReflect.Descriptor instead.
func (*DestinationQueryCriteria) Descriptor() ([]byte, []int) {
	return file_domain_request_destinations_request_hotels_proto_rawDescGZIP(), []int{2}
}

func (x *DestinationQueryCriteria) GetDestinationCodes() []string {
	if x != nil {
		return x.DestinationCodes
	}
	return nil
}

func (x *DestinationQueryCriteria) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// DestinationSearchCriteria holds free-text filters for destination search.
type DestinationSearchCriteria struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Text query matched against destination names and aliases.
	Query         string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestinationSearchCriteria) Reset() {
	*x = DestinationSearchCriteria{}
	mi := &file_domain_request_destinations_request_hotels_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestinationSearchCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestinationSearchCriteria) ProtoMessage() {}

func (x *DestinationSearchCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_destinations_request_hotels_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestinationSearchCriteria.ProtoReflect.Descriptor instead.
func (*DestinationSearchCriteria) Descriptor() ([]byte, []int) {
	return file_domain_request_destinations_request_hotels_proto_rawDescGZIP(), []int{3}
}

func (x *DestinationSearchCriteria) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

var File_domain_request_destinations_request_hotels_proto protoreflect.FileDescriptor

const file_domain_request_destinations_request_hotels_proto_rawDesc = "" +
	"\n" +
	"0domain/request/destinations-request-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a*domain/request/common-request-hotels.proto\"\xc3\x01\n" +
	"\x16GetDestinationsRequest\x12Y\n" +
	"\bcriteria\x18\x01 \x01(\v2=.com_bundleport_connect_proto_hotels.DestinationQueryCriteriaR\bcriteria\x12N\n" +
	"\bsettings\x18\x02 \x01(\v22.com_bundleport_connect_proto_hotels.SettingsInputR\bsettings\"\xc7\x01\n" +
	"\x19SearchDestinationsRequest\x12Z\n" +
	"\bcriteria\x18\x01 \x01(\v2>.com_bundleport_connect_proto_hotels.DestinationSearchCriteriaR\bcriteria\x12N\n" +
	"\bsettings\x18\x02 \x01(\v22.com_bundleport_connect_proto_hotels.SettingsInputR\bsettings\"b\n" +
	"\x18DestinationQueryCriteria\x12*\n" +
	"\x10destinationCodes\x18\x01 \x03(\tR\x10destinationCodes\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"1\n" +
	"\x19DestinationSearchCriteria\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05queryB\x87\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x19DestinationsRequestProtosP\x01Z.github.com/bundleport/connect-hotels-go/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_request_destinations_request_hotels_proto_rawDescOnce sync.Once
	file_domain_request_destinations_request_hotels_proto_rawDescData []byte
)

func file_domain_request_destinations_request_hotels_proto_rawDescGZIP() []byte {
	file_domain_request_destinations_request_hotels_proto_rawDescOnce.Do(func() {
		file_domain_request_destinations_request_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_request_destinations_request_hotels_proto_rawDesc), len(file_domain_request_destinations_request_hotels_proto_rawDesc)))
	})
	return file_domain_request_destinations_request_hotels_proto_rawDescData
}

var file_domain_request_destinations_request_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_domain_request_destinations_request_hotels_proto_goTypes = []any{
	(*GetDestinationsRequest)(nil),    // 0: com_bundleport_connect_proto_hotels.GetDestinationsRequest
	(*SearchDestinationsRequest)(nil), // 1: com_bundleport_connect_proto_hotels.SearchDestinationsRequest
	(*DestinationQueryCriteria)(nil),  // 2: com_bundleport_connect_proto_hotels.DestinationQueryCriteria
	(*DestinationSearchCriteria)(nil), // 3: com_bundleport_connect_proto_hotels.DestinationSearchCriteria
	(*SettingsInput)(nil),             // 4: com_bundleport_connect_proto_hotels.SettingsInput
}
var file_domain_request_destinations_request_hotels_proto_depIdxs = []int32{
	2, // 0: com_bundleport_connect_proto_hotels.GetDestinationsRequest.criteria:type_name -> com_bundleport_connect_proto_hotels.DestinationQueryCriteria
	4, // 1: com_bundleport_connect_proto_hotels.GetDestinationsRequest.settings:type_name -> com_bundleport_connect_proto_hotels.SettingsInput
	3, // 2: com_bundleport_connect_proto_hotels.SearchDestinationsRequest.criteria:type_name -> com_bundleport_connect_proto_hotels.DestinationSearchCriteria
	4, // 3: com_bundleport_connect_proto_hotels.SearchDestinationsRequest.settings:type_name -> com_bundleport_connect_proto_hotels.SettingsInput
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_domain_request_destinations_request_hotels_proto_init() }
func file_domain_request_destinations_request_hotels_proto_init() {
	if File_domain_request_destinations_request_hotels_proto != nil {
		return
	}
	file_domain_request_common_request_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_request_destinations_request_hotels_proto_rawDesc), len(file_domain_request_destinations_request_hotels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_request_destinations_request_hotels_proto_goTypes,
		DependencyIndexes: file_domain_request_destinations_request_hotels_proto_depIdxs,
		MessageInfos:      file_domain_request_destinations_request_hotels_proto_msgTypes,
	}.Build()
	File_domain_request_destinations_request_hotels_proto = out.File
	file_domain_request_destinations_request_hotels_proto_goTypes = nil
	file_domain_request_destinations_request_hotels_proto_depIdxs = nil
}
