// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/response/destinations-response-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetDestinationsResponse returns destination catalog entries.
type GetDestinationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request audit information and downstream trace ids.
	AuditData *AuditData `protobuf:"bytes,1,opt,name=auditData,proto3" json:"auditData,omitempty"`
	// Blocking errors encountered while fetching destinations.
	Errors []*Error `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	// Non-blocking warnings returned alongside the destination data.
	Warnings []*Warning `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	// Additional debug data for diagnostic purposes.
	DebugData []*TypeValue `protobuf:"bytes,4,rep,name=debugData,proto3" json:"debugData,omitempty"`
	// Destination records that match the request criteria.
	Destinations []*Destination `protobuf:"bytes,5,rep,name=destinations,proto3" json:"destinations,omitempty"`
	// Pagination token to retrieve the next batch of destinations.
	Token         string `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDestinationsResponse) Reset() {
	*x = GetDestinationsResponse{}
	mi := &file_domain_response_destinations_response_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDestinationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDestinationsResponse) ProtoMessage() {}

func (x *GetDestinationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_destinations_response_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDestinationsResponse.ProtoReflect.Descriptor instead.
func (*GetDestinationsResponse) Descriptor() ([]byte, []int) {
	return file_domain_response_destinations_response_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *GetDestinationsResponse) GetAuditData() *AuditData {
	if x != nil {
		return x.AuditData
	}
	return nil
}

func (x *GetDestinationsResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *GetDestinationsResponse) GetWarnings() []*Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *GetDestinationsResponse) GetDebugData() []*TypeValue {
	if x != nil {
		return x.DebugData
	}
	return nil
}

func (x *GetDestinationsResponse) GetDestinations() []*Destination {
	if x != nil {
		return x.Destinations
	}
	return nil
}

func (x *GetDestinationsResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// SearchDestinationsResponse returns destinations that match the search term.
type SearchDestinationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request audit information and downstream trace ids.
	AuditData *AuditData `protobuf:"bytes,1,opt,name=auditData,proto3" json:"auditData,omitempty"`
	// Blocking errors encountered during the destination search.
	Errors []*Error `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	// Non-blocking warnings returned alongside the destination data.
	Warnings []*Warning `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	// Additional debug data for diagnostic purposes.
	DebugData []*TypeValue `protobuf:"bytes,4,rep,name=debugData,proto3" json:"debugData,omitempty"`
	// Destinations matched by the search criteria.
	Destinations  []*Destination `protobuf:"bytes,5,rep,name=destinations,proto3" json:"destinations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchDestinationsResponse) Reset() {
	*x = SearchDestinationsResponse{}
	mi := &file_domain_response_destinations_response_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDestinationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDestinationsResponse) ProtoMessage() {}

func (x *SearchDestinationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_destinations_response_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDestinationsResponse.ProtoReflect.Descriptor instead.
func (*SearchDestinationsResponse) Descriptor() ([]byte, []int) {
	return file_domain_response_destinations_response_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *SearchDestinationsResponse) GetAuditData() *AuditData {
	if x != nil {
		return x.AuditData
	}
	return nil
}

func (x *SearchDestinationsResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *SearchDestinationsResponse) GetWarnings() []*Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *SearchDestinationsResponse) GetDebugData() []*TypeValue {
	if x != nil {
		return x.DebugData
	}
	return nil
}

func (x *SearchDestinationsResponse) GetDestinations() []*Destination {
	if x != nil {
		return x.Destinations
	}
	return nil
}

// Destination summarises catalog information for a location.
type Destination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Aggregator destination identifier.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Provider-specific destination code.
	DestinationCode string `protobuf:"bytes,2,opt,name=destinationCode,proto3" json:"destinationCode,omitempty"`
	// Destination type, for example CITY or REGION.
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Destination name in the requested language.
	Name          string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Destination) Reset() {
	*x = Destination{}
	mi := &file_domain_response_destinations_response_hotels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Destination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination) ProtoMessage() {}

func (x *Destination) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_destinations_response_hotels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination.ProtoReflect.Descriptor instead.
func (*Destination) Descriptor() ([]byte, []int) {
	return file_domain_response_destinations_response_hotels_proto_rawDescGZIP(), []int{2}
}

func (x *Destination) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Destination) GetDestinationCode() string {
	if x != nil {
		return x.DestinationCode
	}
	return ""
}

func (x *Destination) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Destination) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_domain_response_destinations_response_hotels_proto protoreflect.FileDescriptor

const file_domain_response_destinations_response_hotels_proto_rawDesc = "" +
	"\n" +
	"2domain/response/destinations-response-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a,domain/response/common-response-hotels.proto\"\xaf\x03\n" +
	"\x17GetDestinationsResponse\x12L\n" +
	"\tauditData\x18\x01 \x01(\v2..com_bundleport_connect_proto_hotels.AuditDataR\tauditData\x12B\n" +
	"\x06errors\x18\x02 \x03(\v2*.com_bundleport_connect_proto_hotels.ErrorR\x06errors\x12H\n" +
	"\bwarnings\x18\x03 \x03(\v2,.com_bundleport_connect_proto_hotels.WarningR\bwarnings\x12L\n" +
	"\tdebugData\x18\x04 \x03(\v2..com_bundleport_connect_proto_hotels.TypeValueR\tdebugData\x12T\n" +
	"\fdestinations\x18\x05 \x03(\v20.com_bundleport_connect_proto_hotels.DestinationR\fdestinations\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\"\x9c\x03\n" +
	"\x1aSearchDestinationsResponse\x12L\n" +
	"\tauditData\x18\x01 \x01(\v2..com_bundleport_connect_proto_hotels.AuditDataR\tauditData\x12B\n" +
	"\x06errors\x18\x02 \x03(\v2*.com_bundleport_connect_proto_hotels.ErrorR\x06errors\x12H\n" +
	"\bwarnings\x18\x03 \x03(\v2,.com_bundleport_connect_proto_hotels.WarningR\bwarnings\x12L\n" +
	"\tdebugData\x18\x04 \x03(\v2..com_bundleport_connect_proto_hotels.TypeValueR\tdebugData\x12T\n" +
	"\fdestinations\x18\x05 \x03(\v20.com_bundleport_connect_proto_hotels.DestinationR\fdestinations\"s\n" +
	"\vDestination\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12(\n" +
	"\x0fdestinationCode\x18\x02 \x01(\tR\x0fdestinationCode\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04nameB\x88\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x1aDestinationsResponseProtosP\x01Z.github.com/bundleport/connect-hotels-go/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_response_destinations_response_hotels_proto_rawDescOnce sync.Once
	file_domain_response_destinations_response_hotels_proto_rawDescData []byte
)

func file_domain_response_destinations_response_hotels_proto_rawDescGZIP() []byte {
	file_domain_response_destinations_response_hotels_proto_rawDescOnce.Do(func() {
		file_domain_response_destinations_response_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_response_destinations_response_hotels_proto_rawDesc), len(file_domain_response_destinations_response_hotels_proto_rawDesc)))
	})
	return file_domain_response_destinations_response_hotels_proto_rawDescData
}

var file_domain_response_destinations_response_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_domain_response_destinations_response_hotels_proto_goTypes = []any{
	(*GetDestinationsResponse)(nil),    // 0: com_bundleport_connect_proto_hotels.GetDestinationsResponse
	(*SearchDestinationsResponse)(nil), // 1: com_bundleport_connect_proto_hotels.SearchDestinationsResponse
	(*Destination)(nil),                // 2: com_bundleport_connect_proto_hotels.Destination
	(*AuditData)(nil),                  // 3: com_bundleport_connect_proto_hotels.AuditData
	(*Error)(nil),                      // 4: com_bundleport_connect_proto_hotels.Error
	(*Warning)(nil),                    // 5: com_bundleport_connect_proto_hotels.Warning
	(*TypeValue)(nil),                  // 6: com_bundleport_connect_proto_hotels.TypeValue
}
var file_domain_response_destinations_response_hotels_proto_depIdxs = []int32{
	3,  // 0: com_bundleport_connect_proto_hotels.GetDestinationsResponse.auditData:type_name -> com_bundleport_connect_proto_hotels.AuditData
	4,  // 1: com_bundleport_connect_proto_hotels.GetDestinationsResponse.errors:type_name -> com_bundleport_connect_proto_hotels.Error
	5,  // 2: com_bundleport_connect_proto_hotels.GetDestinationsResponse.warnings:type_name -> com_bundleport_connect_proto_hotels.Warning
	6,  // 3: com_bundleport_connect_proto_hotels.GetDestinationsResponse.debugData:type_name -> com_bundleport_connect_proto_hotels.TypeValue
	2,  // 4: com_bundleport_connect_proto_hotels.GetDestinationsResponse.destinations:type_name -> com_bundleport_connect_proto_hotels.Destination
	3,  // 5: com_bundleport_connect_proto_hotels.SearchDestinationsResponse.auditData:type_name -> com_bundleport_connect_proto_hotels.AuditData
	4,  // 6: com_bundleport_connect_proto_hotels.SearchDestinationsResponse.errors:type_name -> com_bundleport_connect_proto_hotels.Error
	5,  // 7: com_bundleport_connect_proto_hotels.SearchDestinationsResponse.warnings:type_name -> com_bundleport_connect_proto_hotels.Warning
	6,  // 8: com_bundleport_connect_proto_hotels.SearchDestinationsResponse.debugData:type_name -> com_bundleport_connect_proto_hotels.TypeValue
	2,  // 9: com_bundleport_connect_proto_hotels.SearchDestinationsResponse.destinations:type_name -> com_bundleport_connect_proto_hotels.Destination
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_domain_response_destinations_response_hotels_proto_init() }
func file_domain_response_destinations_response_hotels_proto_init() {
	if File_domain_response_destinations_response_hotels_proto != nil {
		return
	}
	file_domain_response_common_response_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_response_destinations_response_hotels_proto_rawDesc), len(file_domain_response_destinations_response_hotels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_response_destinations_response_hotels_proto_goTypes,
		DependencyIndexes: file_domain_response_destinations_response_hotels_proto_depIdxs,
		MessageInfos:      file_domain_response_destinations_response_hotels_proto_msgTypes,
	}.Build()
	File_domain_response_destinations_response_hotels_proto = out.File
	file_domain_response_destinations_response_hotels_proto_goTypes = nil
	file_domain_response_destinations_response_hotels_proto_depIdxs = nil
}
