// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/response/hotels-response-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetHotelsResponse returns hotel catalog entries for the requested scope.
type GetHotelsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request audit information and downstream trace ids.
	AuditData *AuditData `protobuf:"bytes,1,opt,name=auditData,proto3" json:"auditData,omitempty"`
	// Blocking errors encountered while fetching hotel data.
	Errors []*Error `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	// Non-blocking warnings returned alongside the hotel data.
	Warnings []*Warning `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	// Additional debug data for diagnostic purposes.
	DebugData []*TypeValue `protobuf:"bytes,4,rep,name=debugData,proto3" json:"debugData,omitempty"`
	// Hotel records that matched the request criteria.
	Hotels []*Hotel `protobuf:"bytes,5,rep,name=hotels,proto3" json:"hotels,omitempty"`
	// Pagination token to retrieve the next batch of hotels.
	Token         string `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHotelsResponse) Reset() {
	*x = GetHotelsResponse{}
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelsResponse) ProtoMessage() {}

func (x *GetHotelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelsResponse.ProtoReflect.Descriptor instead.
func (*GetHotelsResponse) Descriptor() ([]byte, []int) {
	return file_domain_response_hotels_response_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *GetHotelsResponse) GetAuditData() *AuditData {
	if x != nil {
		return x.AuditData
	}
	return nil
}

func (x *GetHotelsResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *GetHotelsResponse) GetWarnings() []*Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *GetHotelsResponse) GetDebugData() []*TypeValue {
	if x != nil {
		return x.DebugData
	}
	return nil
}

func (x *GetHotelsResponse) GetHotels() []*Hotel {
	if x != nil {
		return x.Hotels
	}
	return nil
}

func (x *GetHotelsResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Hotel summarises descriptive content for a hotel property.
type Hotel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Aggregator hotel identifier.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Display name for the hotel.
	HotelName string `protobuf:"bytes,2,opt,name=hotelName,proto3" json:"hotelName,omitempty"`
	// Additional textual descriptions provided for the hotel.
	Descriptions []*HotelDescription `protobuf:"bytes,3,rep,name=descriptions,proto3" json:"descriptions,omitempty"`
	// Hotel category code such as star rating.
	Category string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	// Property type such as HOTEL, APARTMENT or HOSTEL.
	PropertyType string `protobuf:"bytes,5,opt,name=propertyType,proto3" json:"propertyType,omitempty"`
	// Chain code associated with the property.
	ChainCode string `protobuf:"bytes,6,opt,name=chainCode,proto3" json:"chainCode,omitempty"`
	// Board codes available for this hotel.
	BoardCodes []string `protobuf:"bytes,7,rep,name=boardCodes,proto3" json:"boardCodes,omitempty"`
	// Mandatory fees that apply to the property.
	MandatoryFee []*MandatoryFee `protobuf:"bytes,8,rep,name=mandatoryFee,proto3" json:"mandatoryFee,omitempty"`
	// Room metadata linked to the hotel.
	Rooms []*RoomData `protobuf:"bytes,9,rep,name=rooms,proto3" json:"rooms,omitempty"`
	// Amenities available at the hotel.
	Amenities []*Amenities `protobuf:"bytes,10,rep,name=amenities,proto3" json:"amenities,omitempty"`
	// Media assets that describe the hotel visually.
	Media []*MediaData `protobuf:"bytes,11,rep,name=media,proto3" json:"media,omitempty"`
	// Geographical information for the hotel.
	Location *Location `protobuf:"bytes,12,opt,name=location,proto3" json:"location,omitempty"`
	// Contact details for the property.
	Contact       *Contact `protobuf:"bytes,13,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hotel) Reset() {
	*x = Hotel{}
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hotel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hotel) ProtoMessage() {}

func (x *Hotel) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hotel.ProtoReflect.Descriptor instead.
func (*Hotel) Descriptor() ([]byte, []int) {
	return file_domain_response_hotels_response_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *Hotel) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Hotel) GetHotelName() string {
	if x != nil {
		return x.HotelName
	}
	return ""
}

func (x *Hotel) GetDescriptions() []*HotelDescription {
	if x != nil {
		return x.Descriptions
	}
	return nil
}

func (x *Hotel) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Hotel) GetPropertyType() string {
	if x != nil {
		return x.PropertyType
	}
	return ""
}

func (x *Hotel) GetChainCode() string {
	if x != nil {
		return x.ChainCode
	}
	return ""
}

func (x *Hotel) GetBoardCodes() []string {
	if x != nil {
		return x.BoardCodes
	}
	return nil
}

func (x *Hotel) GetMandatoryFee() []*MandatoryFee {
	if x != nil {
		return x.MandatoryFee
	}
	return nil
}

func (x *Hotel) GetRooms() []*RoomData {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *Hotel) GetAmenities() []*Amenities {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *Hotel) GetMedia() []*MediaData {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *Hotel) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Hotel) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

// HotelDescription contains supplementary hotel text information.
type HotelDescription struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Description text.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// ISO 639-1 language code for the description.
	Languaje      string `protobuf:"bytes,2,opt,name=languaje,proto3" json:"languaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotelDescription) Reset() {
	*x = HotelDescription{}
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotelDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotelDescription) ProtoMessage() {}

func (x *HotelDescription) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotelDescription.ProtoReflect.Descriptor instead.
func (*HotelDescription) Descriptor() ([]byte, []int) {
	return file_domain_response_hotels_response_hotels_proto_rawDescGZIP(), []int{2}
}

func (x *HotelDescription) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *HotelDescription) GetLanguaje() string {
	if x != nil {
		return x.Languaje
	}
	return ""
}

// MandatoryFee represents fees applicable to the booking.
type MandatoryFee struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the fee.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Detailed explanation of the fee.
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Fee amount.
	Price float32 `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	// Indicates whether the fee is already included in the price.
	Included      bool `protobuf:"varint,4,opt,name=included,proto3" json:"included,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MandatoryFee) Reset() {
	*x = MandatoryFee{}
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MandatoryFee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MandatoryFee) ProtoMessage() {}

func (x *MandatoryFee) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MandatoryFee.ProtoReflect.Descriptor instead.
func (*MandatoryFee) Descriptor() ([]byte, []int) {
	return file_domain_response_hotels_response_hotels_proto_rawDescGZIP(), []int{3}
}

func (x *MandatoryFee) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MandatoryFee) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MandatoryFee) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MandatoryFee) GetIncluded() bool {
	if x != nil {
		return x.Included
	}
	return false
}

// Amenities lists features available at the hotel.
type Amenities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Amenity code used to uniquely identify the feature.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Amenity type, for example ROOM or HOTEL.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Human readable description of the amenity.
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amenities) Reset() {
	*x = Amenities{}
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amenities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amenities) ProtoMessage() {}

func (x *Amenities) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amenities.ProtoReflect.Descriptor instead.
func (*Amenities) Descriptor() ([]byte, []int) {
	return file_domain_response_hotels_response_hotels_proto_rawDescGZIP(), []int{4}
}

func (x *Amenities) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Amenities) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Amenities) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// MediaData contains basic information for hotel media assets.
type MediaData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Media identifier.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Display order to render the media.
	Order string `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	// Public URL for the media asset.
	Url           string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaData) Reset() {
	*x = MediaData{}
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaData) ProtoMessage() {}

func (x *MediaData) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaData.ProtoReflect.Descriptor instead.
func (*MediaData) Descriptor() ([]byte, []int) {
	return file_domain_response_hotels_response_hotels_proto_rawDescGZIP(), []int{5}
}

func (x *MediaData) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MediaData) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *MediaData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Location describes the geographical details of the hotel.
type Location struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Street address of the hotel.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// City where the hotel is located.
	City string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	// Postal or ZIP code.
	ZipCode string `protobuf:"bytes,3,opt,name=zipCode,proto3" json:"zipCode,omitempty"`
	// ISO 3166 alpha-2 country code.
	Country string `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	// State or province name.
	State string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	// Geographical coordinates.
	Coordinates *Coordinates `protobuf:"bytes,6,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	// Destinations located near the hotel.
	ClosestDestination []*ClosestDestination `protobuf:"bytes,7,rep,name=closestDestination,proto3" json:"closestDestination,omitempty"`
	// Airports located near the hotel.
	Airports      []*Airport `protobuf:"bytes,8,rep,name=airports,proto3" json:"airports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_domain_response_hotels_response_hotels_proto_rawDescGZIP(), []int{6}
}

func (x *Location) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Location) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Location) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *Location) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Location) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Location) GetCoordinates() *Coordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *Location) GetClosestDestination() []*ClosestDestination {
	if x != nil {
		return x.ClosestDestination
	}
	return nil
}

func (x *Location) GetAirports() []*Airport {
	if x != nil {
		return x.Airports
	}
	return nil
}

// Coordinates represent a geographic point.
type Coordinates struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Longitude in decimal degrees.
	Longitude float32 `protobuf:"fixed32,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// Latitude in decimal degrees.
	Latitude      float32 `protobuf:"fixed32,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_domain_response_hotels_response_hotels_proto_rawDescGZIP(), []int{7}
}

func (x *Coordinates) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Coordinates) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

// ClosestDestination lists nearby points of interest.
type ClosestDestination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Destination code.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Destination name.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClosestDestination) Reset() {
	*x = ClosestDestination{}
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClosestDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosestDestination) ProtoMessage() {}

func (x *ClosestDestination) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosestDestination.ProtoReflect.Descriptor instead.
func (*ClosestDestination) Descriptor() ([]byte, []int) {
	return file_domain_response_hotels_response_hotels_proto_rawDescGZIP(), []int{8}
}

func (x *ClosestDestination) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ClosestDestination) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Airport describes a nearby airport reference.
type Airport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Airport code, typically IATA.
	Code          string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Airport) Reset() {
	*x = Airport{}
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Airport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Airport) ProtoMessage() {}

func (x *Airport) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Airport.ProtoReflect.Descriptor instead.
func (*Airport) Descriptor() ([]byte, []int) {
	return file_domain_response_hotels_response_hotels_proto_rawDescGZIP(), []int{9}
}

func (x *Airport) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// Contact contains contact details for the hotel.
type Contact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Primary contact email address.
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Primary contact phone number.
	PhoneNumber string `protobuf:"bytes,2,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	// Fax number when available.
	Fax string `protobuf:"bytes,3,opt,name=fax,proto3" json:"fax,omitempty"`
	// Website URL for the hotel.
	Web           string `protobuf:"bytes,4,opt,name=web,proto3" json:"web,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_hotels_response_hotels_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_domain_response_hotels_response_hotels_proto_rawDescGZIP(), []int{10}
}

func (x *Contact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Contact) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Contact) GetFax() string {
	if x != nil {
		return x.Fax
	}
	return ""
}

func (x *Contact) GetWeb() string {
	if x != nil {
		return x.Web
	}
	return ""
}

var File_domain_response_hotels_response_hotels_proto protoreflect.FileDescriptor

const file_domain_response_hotels_response_hotels_proto_rawDesc = "" +
	"\n" +
	",domain/response/hotels-response-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a,domain/response/common-response-hotels.proto\x1a+domain/response/rooms-response-hotels.proto\"\x97\x03\n" +
	"\x11GetHotelsResponse\x12L\n" +
	"\tauditData\x18\x01 \x01(\v2..com_bundleport_connect_proto_hotels.AuditDataR\tauditData\x12B\n" +
	"\x06errors\x18\x02 \x03(\v2*.com_bundleport_connect_proto_hotels.ErrorR\x06errors\x12H\n" +
	"\bwarnings\x18\x03 \x03(\v2,.com_bundleport_connect_proto_hotels.WarningR\bwarnings\x12L\n" +
	"\tdebugData\x18\x04 \x03(\v2..com_bundleport_connect_proto_hotels.TypeValueR\tdebugData\x12B\n" +
	"\x06hotels\x18\x05 \x03(\v2*.com_bundleport_connect_proto_hotels.HotelR\x06hotels\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\"\xd5\x05\n" +
	"\x05Hotel\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1c\n" +
	"\thotelName\x18\x02 \x01(\tR\thotelName\x12Y\n" +
	"\fdescriptions\x18\x03 \x03(\v25.com_bundleport_connect_proto_hotels.HotelDescriptionR\fdescriptions\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\"\n" +
	"\fpropertyType\x18\x05 \x01(\tR\fpropertyType\x12\x1c\n" +
	"\tchainCode\x18\x06 \x01(\tR\tchainCode\x12\x1e\n" +
	"\n" +
	"boardCodes\x18\a \x03(\tR\n" +
	"boardCodes\x12U\n" +
	"\fmandatoryFee\x18\b \x03(\v21.com_bundleport_connect_proto_hotels.MandatoryFeeR\fmandatoryFee\x12C\n" +
	"\x05rooms\x18\t \x03(\v2-.com_bundleport_connect_proto_hotels.RoomDataR\x05rooms\x12L\n" +
	"\tamenities\x18\n" +
	" \x03(\v2..com_bundleport_connect_proto_hotels.AmenitiesR\tamenities\x12D\n" +
	"\x05media\x18\v \x03(\v2..com_bundleport_connect_proto_hotels.MediaDataR\x05media\x12I\n" +
	"\blocation\x18\f \x01(\v2-.com_bundleport_connect_proto_hotels.LocationR\blocation\x12F\n" +
	"\acontact\x18\r \x01(\v2,.com_bundleport_connect_proto_hotels.ContactR\acontact\"B\n" +
	"\x10HotelDescription\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguaje\x18\x02 \x01(\tR\blanguaje\"h\n" +
	"\fMandatoryFee\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x1a\n" +
	"\bincluded\x18\x04 \x01(\bR\bincluded\"U\n" +
	"\tAmenities\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"G\n" +
	"\tMediaData\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05order\x18\x02 \x01(\tR\x05order\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\x89\x03\n" +
	"\bLocation\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x18\n" +
	"\azipCode\x18\x03 \x01(\tR\azipCode\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12R\n" +
	"\vcoordinates\x18\x06 \x01(\v20.com_bundleport_connect_proto_hotels.CoordinatesR\vcoordinates\x12g\n" +
	"\x12closestDestination\x18\a \x03(\v27.com_bundleport_connect_proto_hotels.ClosestDestinationR\x12closestDestination\x12H\n" +
	"\bairports\x18\b \x03(\v2,.com_bundleport_connect_proto_hotels.AirportR\bairports\"G\n" +
	"\vCoordinates\x12\x1c\n" +
	"\tlongitude\x18\x01 \x01(\x02R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x02R\blatitude\"<\n" +
	"\x12ClosestDestination\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x1d\n" +
	"\aAirport\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"e\n" +
	"\aContact\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12 \n" +
	"\vphoneNumber\x18\x02 \x01(\tR\vphoneNumber\x12\x10\n" +
	"\x03fax\x18\x03 \x01(\tR\x03fax\x12\x10\n" +
	"\x03web\x18\x04 \x01(\tR\x03webB\x82\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x14HotelsResponseProtosP\x01Z.github.com/bundleport/connect-go-schema/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_response_hotels_response_hotels_proto_rawDescOnce sync.Once
	file_domain_response_hotels_response_hotels_proto_rawDescData []byte
)

func file_domain_response_hotels_response_hotels_proto_rawDescGZIP() []byte {
	file_domain_response_hotels_response_hotels_proto_rawDescOnce.Do(func() {
		file_domain_response_hotels_response_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_response_hotels_response_hotels_proto_rawDesc), len(file_domain_response_hotels_response_hotels_proto_rawDesc)))
	})
	return file_domain_response_hotels_response_hotels_proto_rawDescData
}

var file_domain_response_hotels_response_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_domain_response_hotels_response_hotels_proto_goTypes = []any{
	(*GetHotelsResponse)(nil),  // 0: com_bundleport_connect_proto_hotels.GetHotelsResponse
	(*Hotel)(nil),              // 1: com_bundleport_connect_proto_hotels.Hotel
	(*HotelDescription)(nil),   // 2: com_bundleport_connect_proto_hotels.HotelDescription
	(*MandatoryFee)(nil),       // 3: com_bundleport_connect_proto_hotels.MandatoryFee
	(*Amenities)(nil),          // 4: com_bundleport_connect_proto_hotels.Amenities
	(*MediaData)(nil),          // 5: com_bundleport_connect_proto_hotels.MediaData
	(*Location)(nil),           // 6: com_bundleport_connect_proto_hotels.Location
	(*Coordinates)(nil),        // 7: com_bundleport_connect_proto_hotels.Coordinates
	(*ClosestDestination)(nil), // 8: com_bundleport_connect_proto_hotels.ClosestDestination
	(*Airport)(nil),            // 9: com_bundleport_connect_proto_hotels.Airport
	(*Contact)(nil),            // 10: com_bundleport_connect_proto_hotels.Contact
	(*AuditData)(nil),          // 11: com_bundleport_connect_proto_hotels.AuditData
	(*Error)(nil),              // 12: com_bundleport_connect_proto_hotels.Error
	(*Warning)(nil),            // 13: com_bundleport_connect_proto_hotels.Warning
	(*TypeValue)(nil),          // 14: com_bundleport_connect_proto_hotels.TypeValue
	(*RoomData)(nil),           // 15: com_bundleport_connect_proto_hotels.RoomData
}
var file_domain_response_hotels_response_hotels_proto_depIdxs = []int32{
	11, // 0: com_bundleport_connect_proto_hotels.GetHotelsResponse.auditData:type_name -> com_bundleport_connect_proto_hotels.AuditData
	12, // 1: com_bundleport_connect_proto_hotels.GetHotelsResponse.errors:type_name -> com_bundleport_connect_proto_hotels.Error
	13, // 2: com_bundleport_connect_proto_hotels.GetHotelsResponse.warnings:type_name -> com_bundleport_connect_proto_hotels.Warning
	14, // 3: com_bundleport_connect_proto_hotels.GetHotelsResponse.debugData:type_name -> com_bundleport_connect_proto_hotels.TypeValue
	1,  // 4: com_bundleport_connect_proto_hotels.GetHotelsResponse.hotels:type_name -> com_bundleport_connect_proto_hotels.Hotel
	2,  // 5: com_bundleport_connect_proto_hotels.Hotel.descriptions:type_name -> com_bundleport_connect_proto_hotels.HotelDescription
	3,  // 6: com_bundleport_connect_proto_hotels.Hotel.mandatoryFee:type_name -> com_bundleport_connect_proto_hotels.MandatoryFee
	15, // 7: com_bundleport_connect_proto_hotels.Hotel.rooms:type_name -> com_bundleport_connect_proto_hotels.RoomData
	4,  // 8: com_bundleport_connect_proto_hotels.Hotel.amenities:type_name -> com_bundleport_connect_proto_hotels.Amenities
	5,  // 9: com_bundleport_connect_proto_hotels.Hotel.media:type_name -> com_bundleport_connect_proto_hotels.MediaData
	6,  // 10: com_bundleport_connect_proto_hotels.Hotel.location:type_name -> com_bundleport_connect_proto_hotels.Location
	10, // 11: com_bundleport_connect_proto_hotels.Hotel.contact:type_name -> com_bundleport_connect_proto_hotels.Contact
	7,  // 12: com_bundleport_connect_proto_hotels.Location.coordinates:type_name -> com_bundleport_connect_proto_hotels.Coordinates
	8,  // 13: com_bundleport_connect_proto_hotels.Location.closestDestination:type_name -> com_bundleport_connect_proto_hotels.ClosestDestination
	9,  // 14: com_bundleport_connect_proto_hotels.Location.airports:type_name -> com_bundleport_connect_proto_hotels.Airport
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_domain_response_hotels_response_hotels_proto_init() }
func file_domain_response_hotels_response_hotels_proto_init() {
	if File_domain_response_hotels_response_hotels_proto != nil {
		return
	}
	file_domain_response_common_response_hotels_proto_init()
	file_domain_response_rooms_response_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_response_hotels_response_hotels_proto_rawDesc), len(file_domain_response_hotels_response_hotels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_response_hotels_response_hotels_proto_goTypes,
		DependencyIndexes: file_domain_response_hotels_response_hotels_proto_depIdxs,
		MessageInfos:      file_domain_response_hotels_response_hotels_proto_msgTypes,
	}.Build()
	File_domain_response_hotels_response_hotels_proto = out.File
	file_domain_response_hotels_response_hotels_proto_goTypes = nil
	file_domain_response_hotels_response_hotels_proto_depIdxs = nil
}
