// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/request/metadata-request-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetMetadataRequest retrieves static metadata exposed by the aggregator.
type GetMetadataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Criteria used to scope metadata retrieval.
	Criteria *MetadataQueryCriteria `protobuf:"bytes,1,opt,name=criteria,proto3" json:"criteria,omitempty"`
	// Execution settings shared across aggregator requests.
	Settings      *SettingsInput `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_domain_request_metadata_request_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_metadata_request_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_domain_request_metadata_request_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *GetMetadataRequest) GetCriteria() *MetadataQueryCriteria {
	if x != nil {
		return x.Criteria
	}
	return nil
}

func (x *GetMetadataRequest) GetSettings() *SettingsInput {
	if x != nil {
		return x.Settings
	}
	return nil
}

// MetadataQueryCriteria is reserved for future filters on metadata lookups.
type MetadataQueryCriteria struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataQueryCriteria) Reset() {
	*x = MetadataQueryCriteria{}
	mi := &file_domain_request_metadata_request_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataQueryCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataQueryCriteria) ProtoMessage() {}

func (x *MetadataQueryCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_metadata_request_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataQueryCriteria.ProtoReflect.Descriptor instead.
func (*MetadataQueryCriteria) Descriptor() ([]byte, []int) {
	return file_domain_request_metadata_request_hotels_proto_rawDescGZIP(), []int{1}
}

var File_domain_request_metadata_request_hotels_proto protoreflect.FileDescriptor

const file_domain_request_metadata_request_hotels_proto_rawDesc = "" +
	"\n" +
	",domain/request/metadata-request-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a*domain/request/common-request-hotels.proto\"\xbc\x01\n" +
	"\x12GetMetadataRequest\x12V\n" +
	"\bcriteria\x18\x01 \x01(\v2:.com_bundleport_connect_proto_hotels.MetadataQueryCriteriaR\bcriteria\x12N\n" +
	"\bsettings\x18\x02 \x01(\v22.com_bundleport_connect_proto_hotels.SettingsInputR\bsettings\"\x17\n" +
	"\x15MetadataQueryCriteriaB\x83\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x15MetadataRequestProtosP\x01Z.github.com/bundleport/connect-hotels-go/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_request_metadata_request_hotels_proto_rawDescOnce sync.Once
	file_domain_request_metadata_request_hotels_proto_rawDescData []byte
)

func file_domain_request_metadata_request_hotels_proto_rawDescGZIP() []byte {
	file_domain_request_metadata_request_hotels_proto_rawDescOnce.Do(func() {
		file_domain_request_metadata_request_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_request_metadata_request_hotels_proto_rawDesc), len(file_domain_request_metadata_request_hotels_proto_rawDesc)))
	})
	return file_domain_request_metadata_request_hotels_proto_rawDescData
}

var file_domain_request_metadata_request_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_domain_request_metadata_request_hotels_proto_goTypes = []any{
	(*GetMetadataRequest)(nil),    // 0: com_bundleport_connect_proto_hotels.GetMetadataRequest
	(*MetadataQueryCriteria)(nil), // 1: com_bundleport_connect_proto_hotels.MetadataQueryCriteria
	(*SettingsInput)(nil),         // 2: com_bundleport_connect_proto_hotels.SettingsInput
}
var file_domain_request_metadata_request_hotels_proto_depIdxs = []int32{
	1, // 0: com_bundleport_connect_proto_hotels.GetMetadataRequest.criteria:type_name -> com_bundleport_connect_proto_hotels.MetadataQueryCriteria
	2, // 1: com_bundleport_connect_proto_hotels.GetMetadataRequest.settings:type_name -> com_bundleport_connect_proto_hotels.SettingsInput
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_domain_request_metadata_request_hotels_proto_init() }
func file_domain_request_metadata_request_hotels_proto_init() {
	if File_domain_request_metadata_request_hotels_proto != nil {
		return
	}
	file_domain_request_common_request_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_request_metadata_request_hotels_proto_rawDesc), len(file_domain_request_metadata_request_hotels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_request_metadata_request_hotels_proto_goTypes,
		DependencyIndexes: file_domain_request_metadata_request_hotels_proto_depIdxs,
		MessageInfos:      file_domain_request_metadata_request_hotels_proto_msgTypes,
	}.Build()
	File_domain_request_metadata_request_hotels_proto = out.File
	file_domain_request_metadata_request_hotels_proto_goTypes = nil
	file_domain_request_metadata_request_hotels_proto_depIdxs = nil
}
