// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/response/metadata-response-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetMetadataResponse returns static metadata exposed by the aggregator.
type GetMetadataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request audit information and downstream trace ids.
	AuditData *AuditData `protobuf:"bytes,1,opt,name=auditData,proto3" json:"auditData,omitempty"`
	// Blocking errors encountered while retrieving metadata.
	Errors []*Error `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	// Non-blocking warnings returned alongside the metadata.
	Warnings []*Warning `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	// Additional debug data for diagnostic purposes.
	DebugData []*TypeValue `protobuf:"bytes,4,rep,name=debugData,proto3" json:"debugData,omitempty"`
	// Metadata payload requested by the caller.
	Metadata      *Metadata `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	mi := &file_domain_response_metadata_response_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_metadata_response_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return file_domain_response_metadata_response_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *GetMetadataResponse) GetAuditData() *AuditData {
	if x != nil {
		return x.AuditData
	}
	return nil
}

func (x *GetMetadataResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *GetMetadataResponse) GetWarnings() []*Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *GetMetadataResponse) GetDebugData() []*TypeValue {
	if x != nil {
		return x.DebugData
	}
	return nil
}

func (x *GetMetadataResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Metadata encapsulates access-scoped metadata.
type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Access identifier that provided the metadata.
	Access string `protobuf:"bytes,1,opt,name=access,proto3" json:"access,omitempty"`
	// Access specific metadata values.
	MetadataData *MetadataData `protobuf:"bytes,2,opt,name=metadataData,proto3" json:"metadataData,omitempty"`
	// Creation timestamp for the metadata entry.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// Last update timestamp for the metadata entry.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_domain_response_metadata_response_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_metadata_response_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_domain_response_metadata_response_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *Metadata) GetMetadataData() *MetadataData {
	if x != nil {
		return x.MetadataData
	}
	return nil
}

func (x *Metadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Metadata) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// MetadataData groups metadata values associated with an access.
type MetadataData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Access identifier used in the metadata source.
	Access string `protobuf:"bytes,1,opt,name=access,proto3" json:"access,omitempty"`
	// Arbitrary data entries supplied by the provider.
	Data          []*TypeValue `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataData) Reset() {
	*x = MetadataData{}
	mi := &file_domain_response_metadata_response_hotels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataData) ProtoMessage() {}

func (x *MetadataData) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_metadata_response_hotels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataData.ProtoReflect.Descriptor instead.
func (*MetadataData) Descriptor() ([]byte, []int) {
	return file_domain_response_metadata_response_hotels_proto_rawDescGZIP(), []int{2}
}

func (x *MetadataData) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *MetadataData) GetData() []*TypeValue {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_domain_response_metadata_response_hotels_proto protoreflect.FileDescriptor

const file_domain_response_metadata_response_hotels_proto_rawDesc = "" +
	"\n" +
	".domain/response/metadata-response-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a\x1fgoogle/protobuf/timestamp.proto\x1a,domain/response/common-response-hotels.proto\"\x8a\x03\n" +
	"\x13GetMetadataResponse\x12L\n" +
	"\tauditData\x18\x01 \x01(\v2..com_bundleport_connect_proto_hotels.AuditDataR\tauditData\x12B\n" +
	"\x06errors\x18\x02 \x03(\v2*.com_bundleport_connect_proto_hotels.ErrorR\x06errors\x12H\n" +
	"\bwarnings\x18\x03 \x03(\v2,.com_bundleport_connect_proto_hotels.WarningR\bwarnings\x12L\n" +
	"\tdebugData\x18\x04 \x03(\v2..com_bundleport_connect_proto_hotels.TypeValueR\tdebugData\x12I\n" +
	"\bmetadata\x18\x05 \x01(\v2-.com_bundleport_connect_proto_hotels.MetadataR\bmetadata\"\xed\x01\n" +
	"\bMetadata\x12\x16\n" +
	"\x06access\x18\x01 \x01(\tR\x06access\x12U\n" +
	"\fmetadataData\x18\x02 \x01(\v21.com_bundleport_connect_proto_hotels.MetadataDataR\fmetadataData\x128\n" +
	"\tcreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"j\n" +
	"\fMetadataData\x12\x16\n" +
	"\x06access\x18\x01 \x01(\tR\x06access\x12B\n" +
	"\x04data\x18\x02 \x03(\v2..com_bundleport_connect_proto_hotels.TypeValueR\x04dataB\x84\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x16MetadataResponseProtosP\x01Z.github.com/bundleport/connect-go-schema/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_response_metadata_response_hotels_proto_rawDescOnce sync.Once
	file_domain_response_metadata_response_hotels_proto_rawDescData []byte
)

func file_domain_response_metadata_response_hotels_proto_rawDescGZIP() []byte {
	file_domain_response_metadata_response_hotels_proto_rawDescOnce.Do(func() {
		file_domain_response_metadata_response_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_response_metadata_response_hotels_proto_rawDesc), len(file_domain_response_metadata_response_hotels_proto_rawDesc)))
	})
	return file_domain_response_metadata_response_hotels_proto_rawDescData
}

var file_domain_response_metadata_response_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_domain_response_metadata_response_hotels_proto_goTypes = []any{
	(*GetMetadataResponse)(nil),   // 0: com_bundleport_connect_proto_hotels.GetMetadataResponse
	(*Metadata)(nil),              // 1: com_bundleport_connect_proto_hotels.Metadata
	(*MetadataData)(nil),          // 2: com_bundleport_connect_proto_hotels.MetadataData
	(*AuditData)(nil),             // 3: com_bundleport_connect_proto_hotels.AuditData
	(*Error)(nil),                 // 4: com_bundleport_connect_proto_hotels.Error
	(*Warning)(nil),               // 5: com_bundleport_connect_proto_hotels.Warning
	(*TypeValue)(nil),             // 6: com_bundleport_connect_proto_hotels.TypeValue
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_domain_response_metadata_response_hotels_proto_depIdxs = []int32{
	3, // 0: com_bundleport_connect_proto_hotels.GetMetadataResponse.auditData:type_name -> com_bundleport_connect_proto_hotels.AuditData
	4, // 1: com_bundleport_connect_proto_hotels.GetMetadataResponse.errors:type_name -> com_bundleport_connect_proto_hotels.Error
	5, // 2: com_bundleport_connect_proto_hotels.GetMetadataResponse.warnings:type_name -> com_bundleport_connect_proto_hotels.Warning
	6, // 3: com_bundleport_connect_proto_hotels.GetMetadataResponse.debugData:type_name -> com_bundleport_connect_proto_hotels.TypeValue
	1, // 4: com_bundleport_connect_proto_hotels.GetMetadataResponse.metadata:type_name -> com_bundleport_connect_proto_hotels.Metadata
	2, // 5: com_bundleport_connect_proto_hotels.Metadata.metadataData:type_name -> com_bundleport_connect_proto_hotels.MetadataData
	7, // 6: com_bundleport_connect_proto_hotels.Metadata.createdAt:type_name -> google.protobuf.Timestamp
	7, // 7: com_bundleport_connect_proto_hotels.Metadata.updatedAt:type_name -> google.protobuf.Timestamp
	6, // 8: com_bundleport_connect_proto_hotels.MetadataData.data:type_name -> com_bundleport_connect_proto_hotels.TypeValue
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_domain_response_metadata_response_hotels_proto_init() }
func file_domain_response_metadata_response_hotels_proto_init() {
	if File_domain_response_metadata_response_hotels_proto != nil {
		return
	}
	file_domain_response_common_response_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_response_metadata_response_hotels_proto_rawDesc), len(file_domain_response_metadata_response_hotels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_response_metadata_response_hotels_proto_goTypes,
		DependencyIndexes: file_domain_response_metadata_response_hotels_proto_depIdxs,
		MessageInfos:      file_domain_response_metadata_response_hotels_proto_msgTypes,
	}.Build()
	File_domain_response_metadata_response_hotels_proto = out.File
	file_domain_response_metadata_response_hotels_proto_goTypes = nil
	file_domain_response_metadata_response_hotels_proto_depIdxs = nil
}
