// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/response/payment-response-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaymentCardType enumerates supported provider card codes.
type PaymentCardType int32

const (
	PaymentCardType_AX PaymentCardType = 0
	PaymentCardType_BC PaymentCardType = 1
	PaymentCardType_CA PaymentCardType = 2
	PaymentCardType_CB PaymentCardType = 3
	PaymentCardType_CU PaymentCardType = 4
	PaymentCardType_DC PaymentCardType = 5
	PaymentCardType_DS PaymentCardType = 6
	PaymentCardType_E  PaymentCardType = 7
	PaymentCardType_EC PaymentCardType = 8
	PaymentCardType_ER PaymentCardType = 9
	PaymentCardType_EU PaymentCardType = 10
	PaymentCardType_JC PaymentCardType = 11
	PaymentCardType_L  PaymentCardType = 12
	PaymentCardType_N  PaymentCardType = 13
	PaymentCardType_O  PaymentCardType = 14
	PaymentCardType_OP PaymentCardType = 15
	PaymentCardType_R  PaymentCardType = 16
	PaymentCardType_S  PaymentCardType = 17
	PaymentCardType_T  PaymentCardType = 18
	PaymentCardType_TO PaymentCardType = 19
	PaymentCardType_TP PaymentCardType = 20
	PaymentCardType_VI PaymentCardType = 21
	PaymentCardType_XS PaymentCardType = 22
)

// Enum value maps for PaymentCardType.
var (
	PaymentCardType_name = map[int32]string{
		0:  "AX",
		1:  "BC",
		2:  "CA",
		3:  "CB",
		4:  "CU",
		5:  "DC",
		6:  "DS",
		7:  "E",
		8:  "EC",
		9:  "ER",
		10: "EU",
		11: "JC",
		12: "L",
		13: "N",
		14: "O",
		15: "OP",
		16: "R",
		17: "S",
		18: "T",
		19: "TO",
		20: "TP",
		21: "VI",
		22: "XS",
	}
	PaymentCardType_value = map[string]int32{
		"AX": 0,
		"BC": 1,
		"CA": 2,
		"CB": 3,
		"CU": 4,
		"DC": 5,
		"DS": 6,
		"E":  7,
		"EC": 8,
		"ER": 9,
		"EU": 10,
		"JC": 11,
		"L":  12,
		"N":  13,
		"O":  14,
		"OP": 15,
		"R":  16,
		"S":  17,
		"T":  18,
		"TO": 19,
		"TP": 20,
		"VI": 21,
		"XS": 22,
	}
)

func (x PaymentCardType) Enum() *PaymentCardType {
	p := new(PaymentCardType)
	*p = x
	return p
}

func (x PaymentCardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentCardType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_response_payment_response_hotels_proto_enumTypes[0].Descriptor()
}

func (PaymentCardType) Type() protoreflect.EnumType {
	return &file_domain_response_payment_response_hotels_proto_enumTypes[0]
}

func (x PaymentCardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentCardType.Descriptor instead.
func (PaymentCardType) EnumDescriptor() ([]byte, []int) {
	return file_domain_response_payment_response_hotels_proto_rawDescGZIP(), []int{0}
}

// PaymentCardTypeRest enumerates a simplified set of card brands.
type PaymentCardTypeRest int32

const (
	PaymentCardTypeRest_PAYMENT_CARD_TYPE_UNSPECIFIED PaymentCardTypeRest = 0
	PaymentCardTypeRest_PAYMENT_CARD_TYPE_VISA        PaymentCardTypeRest = 1
	PaymentCardTypeRest_PAYMENT_CARD_TYPE_MASTERCARD  PaymentCardTypeRest = 2
	PaymentCardTypeRest_PAYMENT_CARD_TYPE_AMEX        PaymentCardTypeRest = 3
)

// Enum value maps for PaymentCardTypeRest.
var (
	PaymentCardTypeRest_name = map[int32]string{
		0: "PAYMENT_CARD_TYPE_UNSPECIFIED",
		1: "PAYMENT_CARD_TYPE_VISA",
		2: "PAYMENT_CARD_TYPE_MASTERCARD",
		3: "PAYMENT_CARD_TYPE_AMEX",
	}
	PaymentCardTypeRest_value = map[string]int32{
		"PAYMENT_CARD_TYPE_UNSPECIFIED": 0,
		"PAYMENT_CARD_TYPE_VISA":        1,
		"PAYMENT_CARD_TYPE_MASTERCARD":  2,
		"PAYMENT_CARD_TYPE_AMEX":        3,
	}
)

func (x PaymentCardTypeRest) Enum() *PaymentCardTypeRest {
	p := new(PaymentCardTypeRest)
	*p = x
	return p
}

func (x PaymentCardTypeRest) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentCardTypeRest) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_response_payment_response_hotels_proto_enumTypes[1].Descriptor()
}

func (PaymentCardTypeRest) Type() protoreflect.EnumType {
	return &file_domain_response_payment_response_hotels_proto_enumTypes[1]
}

func (x PaymentCardTypeRest) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentCardTypeRest.Descriptor instead.
func (PaymentCardTypeRest) EnumDescriptor() ([]byte, []int) {
	return file_domain_response_payment_response_hotels_proto_rawDescGZIP(), []int{1}
}

// PaymentType indicates how payment is handled for the booking.
type PaymentType int32

const (
	// Merchant of record collects the payment.
	PaymentType_MERCHANT PaymentType = 0
	// Provider charges the customer directly.
	PaymentType_DIRECT PaymentType = 1
	// Card is charged during booking confirmation.
	PaymentType_CARD_BOOKING PaymentType = 2
	// Card is charged at check-in.
	PaymentType_CARD_CHECK_IN PaymentType = 3
)

// Enum value maps for PaymentType.
var (
	PaymentType_name = map[int32]string{
		0: "MERCHANT",
		1: "DIRECT",
		2: "CARD_BOOKING",
		3: "CARD_CHECK_IN",
	}
	PaymentType_value = map[string]int32{
		"MERCHANT":      0,
		"DIRECT":        1,
		"CARD_BOOKING":  2,
		"CARD_CHECK_IN": 3,
	}
)

func (x PaymentType) Enum() *PaymentType {
	p := new(PaymentType)
	*p = x
	return p
}

func (x PaymentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_response_payment_response_hotels_proto_enumTypes[2].Descriptor()
}

func (PaymentType) Type() protoreflect.EnumType {
	return &file_domain_response_payment_response_hotels_proto_enumTypes[2]
}

func (x PaymentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentType.Descriptor instead.
func (PaymentType) EnumDescriptor() ([]byte, []int) {
	return file_domain_response_payment_response_hotels_proto_rawDescGZIP(), []int{2}
}

// PayerResponseStatusType represents 3DS payer authentication outcomes.
type PayerResponseStatusType int32

const (
	PayerResponseStatusType_AUTHENTICATION_SUCCESS        PayerResponseStatusType = 0
	PayerResponseStatusType_AUTHENTICATION_FAILED         PayerResponseStatusType = 1
	PayerResponseStatusType_AUTHENTICATION_INCOMPLETE     PayerResponseStatusType = 2
	PayerResponseStatusType_TRANSACTION_ATTEMPT_SUCCESS_A PayerResponseStatusType = 3
	PayerResponseStatusType_TRANSACTION_ATTEMPT_SUCCESS_B PayerResponseStatusType = 4
	PayerResponseStatusType_AUTHENTICATION_REJECTED       PayerResponseStatusType = 5
)

// Enum value maps for PayerResponseStatusType.
var (
	PayerResponseStatusType_name = map[int32]string{
		0: "AUTHENTICATION_SUCCESS",
		1: "AUTHENTICATION_FAILED",
		2: "AUTHENTICATION_INCOMPLETE",
		3: "TRANSACTION_ATTEMPT_SUCCESS_A",
		4: "TRANSACTION_ATTEMPT_SUCCESS_B",
		5: "AUTHENTICATION_REJECTED",
	}
	PayerResponseStatusType_value = map[string]int32{
		"AUTHENTICATION_SUCCESS":        0,
		"AUTHENTICATION_FAILED":         1,
		"AUTHENTICATION_INCOMPLETE":     2,
		"TRANSACTION_ATTEMPT_SUCCESS_A": 3,
		"TRANSACTION_ATTEMPT_SUCCESS_B": 4,
		"AUTHENTICATION_REJECTED":       5,
	}
)

func (x PayerResponseStatusType) Enum() *PayerResponseStatusType {
	p := new(PayerResponseStatusType)
	*p = x
	return p
}

func (x PayerResponseStatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayerResponseStatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_response_payment_response_hotels_proto_enumTypes[3].Descriptor()
}

func (PayerResponseStatusType) Type() protoreflect.EnumType {
	return &file_domain_response_payment_response_hotels_proto_enumTypes[3]
}

func (x PayerResponseStatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayerResponseStatusType.Descriptor instead.
func (PayerResponseStatusType) EnumDescriptor() ([]byte, []int) {
	return file_domain_response_payment_response_hotels_proto_rawDescGZIP(), []int{3}
}

// ThreeDSCardEnrolledStatusType indicates card enrolment state for 3DS.
type ThreeDSCardEnrolledStatusType int32

const (
	ThreeDSCardEnrolledStatusType_CARD_ENROLLED     ThreeDSCardEnrolledStatusType = 0
	ThreeDSCardEnrolledStatusType_CARD_NOT_ENROLLED ThreeDSCardEnrolledStatusType = 1
	ThreeDSCardEnrolledStatusType_CANT_AUTHENTICATE ThreeDSCardEnrolledStatusType = 2
)

// Enum value maps for ThreeDSCardEnrolledStatusType.
var (
	ThreeDSCardEnrolledStatusType_name = map[int32]string{
		0: "CARD_ENROLLED",
		1: "CARD_NOT_ENROLLED",
		2: "CANT_AUTHENTICATE",
	}
	ThreeDSCardEnrolledStatusType_value = map[string]int32{
		"CARD_ENROLLED":     0,
		"CARD_NOT_ENROLLED": 1,
		"CANT_AUTHENTICATE": 2,
	}
)

func (x ThreeDSCardEnrolledStatusType) Enum() *ThreeDSCardEnrolledStatusType {
	p := new(ThreeDSCardEnrolledStatusType)
	*p = x
	return p
}

func (x ThreeDSCardEnrolledStatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThreeDSCardEnrolledStatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_response_payment_response_hotels_proto_enumTypes[4].Descriptor()
}

func (ThreeDSCardEnrolledStatusType) Type() protoreflect.EnumType {
	return &file_domain_response_payment_response_hotels_proto_enumTypes[4]
}

func (x ThreeDSCardEnrolledStatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThreeDSCardEnrolledStatusType.Descriptor instead.
func (ThreeDSCardEnrolledStatusType) EnumDescriptor() ([]byte, []int) {
	return file_domain_response_payment_response_hotels_proto_rawDescGZIP(), []int{4}
}

// ThreeDSSignatureStatusType reflects the status of the 3DS signature.
type ThreeDSSignatureStatusType int32

const (
	ThreeDSSignatureStatusType_SIGNATURE_VALIDATED     ThreeDSSignatureStatusType = 0
	ThreeDSSignatureStatusType_SIGNATURE_NOT_VALIDATED ThreeDSSignatureStatusType = 1
)

// Enum value maps for ThreeDSSignatureStatusType.
var (
	ThreeDSSignatureStatusType_name = map[int32]string{
		0: "SIGNATURE_VALIDATED",
		1: "SIGNATURE_NOT_VALIDATED",
	}
	ThreeDSSignatureStatusType_value = map[string]int32{
		"SIGNATURE_VALIDATED":     0,
		"SIGNATURE_NOT_VALIDATED": 1,
	}
)

func (x ThreeDSSignatureStatusType) Enum() *ThreeDSSignatureStatusType {
	p := new(ThreeDSSignatureStatusType)
	*p = x
	return p
}

func (x ThreeDSSignatureStatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThreeDSSignatureStatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_response_payment_response_hotels_proto_enumTypes[5].Descriptor()
}

func (ThreeDSSignatureStatusType) Type() protoreflect.EnumType {
	return &file_domain_response_payment_response_hotels_proto_enumTypes[5]
}

func (x ThreeDSSignatureStatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThreeDSSignatureStatusType.Descriptor instead.
func (ThreeDSSignatureStatusType) EnumDescriptor() ([]byte, []int) {
	return file_domain_response_payment_response_hotels_proto_rawDescGZIP(), []int{5}
}

// PaymentCardInput contains payment card information supplied by the client.
type PaymentCardInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Card type as recognised by providers.
	Type PaymentCardType `protobuf:"varint,1,opt,name=type,proto3,enum=com_bundleport_connect_proto_hotels.PaymentCardType" json:"type,omitempty"`
	// Card holder information.
	Holder *HolderInput `protobuf:"bytes,2,opt,name=holder,proto3" json:"holder,omitempty"`
	// Card number with no separators.
	Number string `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	// Card verification code.
	CVC string `protobuf:"bytes,4,opt,name=CVC,proto3" json:"CVC,omitempty"`
	// Card expiry details.
	Expire *ExpireDateInput `protobuf:"bytes,5,opt,name=expire,proto3" json:"expire,omitempty"`
	// Indicates whether the card is virtual.
	IsVCC bool `protobuf:"varint,6,opt,name=isVCC,proto3" json:"isVCC,omitempty"`
	// Additional details for virtual credit cards.
	VirtualCreditCard *VirtualCreditCardInput `protobuf:"bytes,7,opt,name=virtualCreditCard,proto3" json:"virtualCreditCard,omitempty"`
	// 3DS authentication data captured during payment.
	ThreeDomainSecurity *ThreeDomainSecurityInput `protobuf:"bytes,8,opt,name=threeDomainSecurity,proto3" json:"threeDomainSecurity,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PaymentCardInput) Reset() {
	*x = PaymentCardInput{}
	mi := &file_domain_response_payment_response_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCardInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCardInput) ProtoMessage() {}

func (x *PaymentCardInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_payment_response_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCardInput.ProtoReflect.Descriptor instead.
func (*PaymentCardInput) Descriptor() ([]byte, []int) {
	return file_domain_response_payment_response_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentCardInput) GetType() PaymentCardType {
	if x != nil {
		return x.Type
	}
	return PaymentCardType_AX
}

func (x *PaymentCardInput) GetHolder() *HolderInput {
	if x != nil {
		return x.Holder
	}
	return nil
}

func (x *PaymentCardInput) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *PaymentCardInput) GetCVC() string {
	if x != nil {
		return x.CVC
	}
	return ""
}

func (x *PaymentCardInput) GetExpire() *ExpireDateInput {
	if x != nil {
		return x.Expire
	}
	return nil
}

func (x *PaymentCardInput) GetIsVCC() bool {
	if x != nil {
		return x.IsVCC
	}
	return false
}

func (x *PaymentCardInput) GetVirtualCreditCard() *VirtualCreditCardInput {
	if x != nil {
		return x.VirtualCreditCard
	}
	return nil
}

func (x *PaymentCardInput) GetThreeDomainSecurity() *ThreeDomainSecurityInput {
	if x != nil {
		return x.ThreeDomainSecurity
	}
	return nil
}

// VirtualCreditCardInput provides data for virtual card usage.
type VirtualCreditCardInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Activation timestamp for the virtual card.
	ActivationDate *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=activationDate,proto3" json:"activationDate,omitempty"`
	// Deactivation timestamp for the virtual card.
	DeactivationDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deactivationDate,proto3" json:"deactivationDate,omitempty"`
	// Current available balance.
	CurrentBalance float64 `protobuf:"fixed64,3,opt,name=currentBalance,proto3" json:"currentBalance,omitempty"`
	// ISO 4217 currency code for the balance.
	CurrencyCode  string `protobuf:"bytes,4,opt,name=currencyCode,proto3" json:"currencyCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualCreditCardInput) Reset() {
	*x = VirtualCreditCardInput{}
	mi := &file_domain_response_payment_response_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualCreditCardInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualCreditCardInput) ProtoMessage() {}

func (x *VirtualCreditCardInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_payment_response_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualCreditCardInput.ProtoReflect.Descriptor instead.
func (*VirtualCreditCardInput) Descriptor() ([]byte, []int) {
	return file_domain_response_payment_response_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *VirtualCreditCardInput) GetActivationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ActivationDate
	}
	return nil
}

func (x *VirtualCreditCardInput) GetDeactivationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DeactivationDate
	}
	return nil
}

func (x *VirtualCreditCardInput) GetCurrentBalance() float64 {
	if x != nil {
		return x.CurrentBalance
	}
	return 0
}

func (x *VirtualCreditCardInput) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

// ThreeDomainSecurityInput stores 3DS authentication context.
type ThreeDomainSecurityInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 3DS version used during authentication.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Directory server transaction identifier.
	DSTransactionID string `protobuf:"bytes,2,opt,name=DSTransactionID,proto3" json:"DSTransactionID,omitempty"`
	// Transaction identifier (XID).
	XID string `protobuf:"bytes,3,opt,name=XID,proto3" json:"XID,omitempty"`
	// Electronic commerce indicator.
	ECI string `protobuf:"bytes,4,opt,name=ECI,proto3" json:"ECI,omitempty"`
	// Cardholder authentication verification value.
	CAVV string `protobuf:"bytes,5,opt,name=CAVV,proto3" json:"CAVV,omitempty"`
	// Raw payer response returned by the authentication system.
	PayerResponse string `protobuf:"bytes,6,opt,name=payerResponse,proto3" json:"payerResponse,omitempty"`
	// Parsed status for the payer response.
	PayerResponseStatus PayerResponseStatusType `protobuf:"varint,7,opt,name=payerResponseStatus,proto3,enum=com_bundleport_connect_proto_hotels.PayerResponseStatusType" json:"payerResponseStatus,omitempty"`
	// Enrolment status of the card in 3DS.
	CardEnrolledStatus ThreeDSCardEnrolledStatusType `protobuf:"varint,8,opt,name=cardEnrolledStatus,proto3,enum=com_bundleport_connect_proto_hotels.ThreeDSCardEnrolledStatusType" json:"cardEnrolledStatus,omitempty"`
	// Merchant name presented during authentication.
	MerchantName string `protobuf:"bytes,9,opt,name=merchantName,proto3" json:"merchantName,omitempty"`
	// Signature validation result.
	SignatureStatus ThreeDSSignatureStatusType `protobuf:"varint,10,opt,name=signatureStatus,proto3,enum=com_bundleport_connect_proto_hotels.ThreeDSSignatureStatusType" json:"signatureStatus,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ThreeDomainSecurityInput) Reset() {
	*x = ThreeDomainSecurityInput{}
	mi := &file_domain_response_payment_response_hotels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreeDomainSecurityInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreeDomainSecurityInput) ProtoMessage() {}

func (x *ThreeDomainSecurityInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_payment_response_hotels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreeDomainSecurityInput.ProtoReflect.Descriptor instead.
func (*ThreeDomainSecurityInput) Descriptor() ([]byte, []int) {
	return file_domain_response_payment_response_hotels_proto_rawDescGZIP(), []int{2}
}

func (x *ThreeDomainSecurityInput) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ThreeDomainSecurityInput) GetDSTransactionID() string {
	if x != nil {
		return x.DSTransactionID
	}
	return ""
}

func (x *ThreeDomainSecurityInput) GetXID() string {
	if x != nil {
		return x.XID
	}
	return ""
}

func (x *ThreeDomainSecurityInput) GetECI() string {
	if x != nil {
		return x.ECI
	}
	return ""
}

func (x *ThreeDomainSecurityInput) GetCAVV() string {
	if x != nil {
		return x.CAVV
	}
	return ""
}

func (x *ThreeDomainSecurityInput) GetPayerResponse() string {
	if x != nil {
		return x.PayerResponse
	}
	return ""
}

func (x *ThreeDomainSecurityInput) GetPayerResponseStatus() PayerResponseStatusType {
	if x != nil {
		return x.PayerResponseStatus
	}
	return PayerResponseStatusType_AUTHENTICATION_SUCCESS
}

func (x *ThreeDomainSecurityInput) GetCardEnrolledStatus() ThreeDSCardEnrolledStatusType {
	if x != nil {
		return x.CardEnrolledStatus
	}
	return ThreeDSCardEnrolledStatusType_CARD_ENROLLED
}

func (x *ThreeDomainSecurityInput) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *ThreeDomainSecurityInput) GetSignatureStatus() ThreeDSSignatureStatusType {
	if x != nil {
		return x.SignatureStatus
	}
	return ThreeDSSignatureStatusType_SIGNATURE_VALIDATED
}

var File_domain_response_payment_response_hotels_proto protoreflect.FileDescriptor

const file_domain_response_payment_response_hotels_proto_rawDesc = "" +
	"\n" +
	"-domain/response/payment-response-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a\x1fgoogle/protobuf/timestamp.proto\x1a*domain/request/common-request-hotels.proto\"\x90\x04\n" +
	"\x10PaymentCardInput\x12H\n" +
	"\x04type\x18\x01 \x01(\x0e24.com_bundleport_connect_proto_hotels.PaymentCardTypeR\x04type\x12H\n" +
	"\x06holder\x18\x02 \x01(\v20.com_bundleport_connect_proto_hotels.HolderInputR\x06holder\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\x12\x10\n" +
	"\x03CVC\x18\x04 \x01(\tR\x03CVC\x12L\n" +
	"\x06expire\x18\x05 \x01(\v24.com_bundleport_connect_proto_hotels.ExpireDateInputR\x06expire\x12\x14\n" +
	"\x05isVCC\x18\x06 \x01(\bR\x05isVCC\x12i\n" +
	"\x11virtualCreditCard\x18\a \x01(\v2;.com_bundleport_connect_proto_hotels.VirtualCreditCardInputR\x11virtualCreditCard\x12o\n" +
	"\x13threeDomainSecurity\x18\b \x01(\v2=.com_bundleport_connect_proto_hotels.ThreeDomainSecurityInputR\x13threeDomainSecurity\"\xf0\x01\n" +
	"\x16VirtualCreditCardInput\x12B\n" +
	"\x0eactivationDate\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0eactivationDate\x12F\n" +
	"\x10deactivationDate\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x10deactivationDate\x12&\n" +
	"\x0ecurrentBalance\x18\x03 \x01(\x01R\x0ecurrentBalance\x12\"\n" +
	"\fcurrencyCode\x18\x04 \x01(\tR\fcurrencyCode\"\xaf\x04\n" +
	"\x18ThreeDomainSecurityInput\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12(\n" +
	"\x0fDSTransactionID\x18\x02 \x01(\tR\x0fDSTransactionID\x12\x10\n" +
	"\x03XID\x18\x03 \x01(\tR\x03XID\x12\x10\n" +
	"\x03ECI\x18\x04 \x01(\tR\x03ECI\x12\x12\n" +
	"\x04CAVV\x18\x05 \x01(\tR\x04CAVV\x12$\n" +
	"\rpayerResponse\x18\x06 \x01(\tR\rpayerResponse\x12n\n" +
	"\x13payerResponseStatus\x18\a \x01(\x0e2<.com_bundleport_connect_proto_hotels.PayerResponseStatusTypeR\x13payerResponseStatus\x12r\n" +
	"\x12cardEnrolledStatus\x18\b \x01(\x0e2B.com_bundleport_connect_proto_hotels.ThreeDSCardEnrolledStatusTypeR\x12cardEnrolledStatus\x12\"\n" +
	"\fmerchantName\x18\t \x01(\tR\fmerchantName\x12i\n" +
	"\x0fsignatureStatus\x18\n" +
	" \x01(\x0e2?.com_bundleport_connect_proto_hotels.ThreeDSSignatureStatusTypeR\x0fsignatureStatus*\xc2\x01\n" +
	"\x0fPaymentCardType\x12\x06\n" +
	"\x02AX\x10\x00\x12\x06\n" +
	"\x02BC\x10\x01\x12\x06\n" +
	"\x02CA\x10\x02\x12\x06\n" +
	"\x02CB\x10\x03\x12\x06\n" +
	"\x02CU\x10\x04\x12\x06\n" +
	"\x02DC\x10\x05\x12\x06\n" +
	"\x02DS\x10\x06\x12\x05\n" +
	"\x01E\x10\a\x12\x06\n" +
	"\x02EC\x10\b\x12\x06\n" +
	"\x02ER\x10\t\x12\x06\n" +
	"\x02EU\x10\n" +
	"\x12\x06\n" +
	"\x02JC\x10\v\x12\x05\n" +
	"\x01L\x10\f\x12\x05\n" +
	"\x01N\x10\r\x12\x05\n" +
	"\x01O\x10\x0e\x12\x06\n" +
	"\x02OP\x10\x0f\x12\x05\n" +
	"\x01R\x10\x10\x12\x05\n" +
	"\x01S\x10\x11\x12\x05\n" +
	"\x01T\x10\x12\x12\x06\n" +
	"\x02TO\x10\x13\x12\x06\n" +
	"\x02TP\x10\x14\x12\x06\n" +
	"\x02VI\x10\x15\x12\x06\n" +
	"\x02XS\x10\x16*\x92\x01\n" +
	"\x13PaymentCardTypeRest\x12!\n" +
	"\x1dPAYMENT_CARD_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_CARD_TYPE_VISA\x10\x01\x12 \n" +
	"\x1cPAYMENT_CARD_TYPE_MASTERCARD\x10\x02\x12\x1a\n" +
	"\x16PAYMENT_CARD_TYPE_AMEX\x10\x03*L\n" +
	"\vPaymentType\x12\f\n" +
	"\bMERCHANT\x10\x00\x12\n" +
	"\n" +
	"\x06DIRECT\x10\x01\x12\x10\n" +
	"\fCARD_BOOKING\x10\x02\x12\x11\n" +
	"\rCARD_CHECK_IN\x10\x03*\xd2\x01\n" +
	"\x17PayerResponseStatusType\x12\x1a\n" +
	"\x16AUTHENTICATION_SUCCESS\x10\x00\x12\x19\n" +
	"\x15AUTHENTICATION_FAILED\x10\x01\x12\x1d\n" +
	"\x19AUTHENTICATION_INCOMPLETE\x10\x02\x12!\n" +
	"\x1dTRANSACTION_ATTEMPT_SUCCESS_A\x10\x03\x12!\n" +
	"\x1dTRANSACTION_ATTEMPT_SUCCESS_B\x10\x04\x12\x1b\n" +
	"\x17AUTHENTICATION_REJECTED\x10\x05*`\n" +
	"\x1dThreeDSCardEnrolledStatusType\x12\x11\n" +
	"\rCARD_ENROLLED\x10\x00\x12\x15\n" +
	"\x11CARD_NOT_ENROLLED\x10\x01\x12\x15\n" +
	"\x11CANT_AUTHENTICATE\x10\x02*R\n" +
	"\x1aThreeDSSignatureStatusType\x12\x17\n" +
	"\x13SIGNATURE_VALIDATED\x10\x00\x12\x1b\n" +
	"\x17SIGNATURE_NOT_VALIDATED\x10\x01B\x83\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x15PaymentResponseProtosP\x01Z.github.com/bundleport/connect-hotels-go/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_response_payment_response_hotels_proto_rawDescOnce sync.Once
	file_domain_response_payment_response_hotels_proto_rawDescData []byte
)

func file_domain_response_payment_response_hotels_proto_rawDescGZIP() []byte {
	file_domain_response_payment_response_hotels_proto_rawDescOnce.Do(func() {
		file_domain_response_payment_response_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_response_payment_response_hotels_proto_rawDesc), len(file_domain_response_payment_response_hotels_proto_rawDesc)))
	})
	return file_domain_response_payment_response_hotels_proto_rawDescData
}

var file_domain_response_payment_response_hotels_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_domain_response_payment_response_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_domain_response_payment_response_hotels_proto_goTypes = []any{
	(PaymentCardType)(0),               // 0: com_bundleport_connect_proto_hotels.PaymentCardType
	(PaymentCardTypeRest)(0),           // 1: com_bundleport_connect_proto_hotels.PaymentCardTypeRest
	(PaymentType)(0),                   // 2: com_bundleport_connect_proto_hotels.PaymentType
	(PayerResponseStatusType)(0),       // 3: com_bundleport_connect_proto_hotels.PayerResponseStatusType
	(ThreeDSCardEnrolledStatusType)(0), // 4: com_bundleport_connect_proto_hotels.ThreeDSCardEnrolledStatusType
	(ThreeDSSignatureStatusType)(0),    // 5: com_bundleport_connect_proto_hotels.ThreeDSSignatureStatusType
	(*PaymentCardInput)(nil),           // 6: com_bundleport_connect_proto_hotels.PaymentCardInput
	(*VirtualCreditCardInput)(nil),     // 7: com_bundleport_connect_proto_hotels.VirtualCreditCardInput
	(*ThreeDomainSecurityInput)(nil),   // 8: com_bundleport_connect_proto_hotels.ThreeDomainSecurityInput
	(*HolderInput)(nil),                // 9: com_bundleport_connect_proto_hotels.HolderInput
	(*ExpireDateInput)(nil),            // 10: com_bundleport_connect_proto_hotels.ExpireDateInput
	(*timestamppb.Timestamp)(nil),      // 11: google.protobuf.Timestamp
}
var file_domain_response_payment_response_hotels_proto_depIdxs = []int32{
	0,  // 0: com_bundleport_connect_proto_hotels.PaymentCardInput.type:type_name -> com_bundleport_connect_proto_hotels.PaymentCardType
	9,  // 1: com_bundleport_connect_proto_hotels.PaymentCardInput.holder:type_name -> com_bundleport_connect_proto_hotels.HolderInput
	10, // 2: com_bundleport_connect_proto_hotels.PaymentCardInput.expire:type_name -> com_bundleport_connect_proto_hotels.ExpireDateInput
	7,  // 3: com_bundleport_connect_proto_hotels.PaymentCardInput.virtualCreditCard:type_name -> com_bundleport_connect_proto_hotels.VirtualCreditCardInput
	8,  // 4: com_bundleport_connect_proto_hotels.PaymentCardInput.threeDomainSecurity:type_name -> com_bundleport_connect_proto_hotels.ThreeDomainSecurityInput
	11, // 5: com_bundleport_connect_proto_hotels.VirtualCreditCardInput.activationDate:type_name -> google.protobuf.Timestamp
	11, // 6: com_bundleport_connect_proto_hotels.VirtualCreditCardInput.deactivationDate:type_name -> google.protobuf.Timestamp
	3,  // 7: com_bundleport_connect_proto_hotels.ThreeDomainSecurityInput.payerResponseStatus:type_name -> com_bundleport_connect_proto_hotels.PayerResponseStatusType
	4,  // 8: com_bundleport_connect_proto_hotels.ThreeDomainSecurityInput.cardEnrolledStatus:type_name -> com_bundleport_connect_proto_hotels.ThreeDSCardEnrolledStatusType
	5,  // 9: com_bundleport_connect_proto_hotels.ThreeDomainSecurityInput.signatureStatus:type_name -> com_bundleport_connect_proto_hotels.ThreeDSSignatureStatusType
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_domain_response_payment_response_hotels_proto_init() }
func file_domain_response_payment_response_hotels_proto_init() {
	if File_domain_response_payment_response_hotels_proto != nil {
		return
	}
	file_domain_request_common_request_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_response_payment_response_hotels_proto_rawDesc), len(file_domain_response_payment_response_hotels_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_response_payment_response_hotels_proto_goTypes,
		DependencyIndexes: file_domain_response_payment_response_hotels_proto_depIdxs,
		EnumInfos:         file_domain_response_payment_response_hotels_proto_enumTypes,
		MessageInfos:      file_domain_response_payment_response_hotels_proto_msgTypes,
	}.Build()
	File_domain_response_payment_response_hotels_proto = out.File
	file_domain_response_payment_response_hotels_proto_goTypes = nil
	file_domain_response_payment_response_hotels_proto_depIdxs = nil
}
