// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/response/quote-response-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QuoteResponse returns the result of repricing a specific option.
type QuoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request audit information and downstream trace ids.
	AuditData *AuditData `protobuf:"bytes,1,opt,name=auditData,proto3" json:"auditData,omitempty"`
	// Blocking errors encountered while quoting the option.
	Errors []*Error `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	// Non-blocking warnings returned alongside the quote data.
	Warnings []*Warning `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	// Additional debug data for diagnostic purposes.
	DebugData []*TypeValue `protobuf:"bytes,4,rep,name=debugData,proto3" json:"debugData,omitempty"`
	// Quote result with updated price and policies.
	OptionQuote   *OptionQuote `protobuf:"bytes,5,opt,name=optionQuote,proto3" json:"optionQuote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteResponse) Reset() {
	*x = QuoteResponse{}
	mi := &file_domain_response_quote_response_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteResponse) ProtoMessage() {}

func (x *QuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_quote_response_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteResponse.ProtoReflect.Descriptor instead.
func (*QuoteResponse) Descriptor() ([]byte, []int) {
	return file_domain_response_quote_response_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *QuoteResponse) GetAuditData() *AuditData {
	if x != nil {
		return x.AuditData
	}
	return nil
}

func (x *QuoteResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *QuoteResponse) GetWarnings() []*Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *QuoteResponse) GetDebugData() []*TypeValue {
	if x != nil {
		return x.DebugData
	}
	return nil
}

func (x *QuoteResponse) GetOptionQuote() *OptionQuote {
	if x != nil {
		return x.OptionQuote
	}
	return nil
}

// OptionQuote contains updated commercial details for an option.
type OptionQuote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the option that was repriced.
	OptionRefId string `protobuf:"bytes,1,opt,name=optionRefId,proto3" json:"optionRefId,omitempty"`
	// Status of the quote request.
	Status StatusType `protobuf:"varint,2,opt,name=status,proto3,enum=com_bundleport_connect_proto_hotels.StatusType" json:"status,omitempty"`
	// Updated price including all applicable charges.
	Price *Price `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	// Indicates whether virtual cards are accepted for payment.
	AcceptVCard bool `protobuf:"varint,4,opt,name=acceptVCard,proto3" json:"acceptVCard,omitempty"`
	// Additional surcharges applied during quoting.
	Surcharges []*Surcharge `protobuf:"bytes,5,rep,name=surcharges,proto3" json:"surcharges,omitempty"`
	// Cancellation policy associated with the quoted option.
	CancelPolicy *CancelPolicy `protobuf:"bytes,6,opt,name=cancelPolicy,proto3" json:"cancelPolicy,omitempty"`
	// Additional remarks from the provider.
	Remarks       []*TypeValue `protobuf:"bytes,7,rep,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionQuote) Reset() {
	*x = OptionQuote{}
	mi := &file_domain_response_quote_response_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionQuote) ProtoMessage() {}

func (x *OptionQuote) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_quote_response_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionQuote.ProtoReflect.Descriptor instead.
func (*OptionQuote) Descriptor() ([]byte, []int) {
	return file_domain_response_quote_response_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *OptionQuote) GetOptionRefId() string {
	if x != nil {
		return x.OptionRefId
	}
	return ""
}

func (x *OptionQuote) GetStatus() StatusType {
	if x != nil {
		return x.Status
	}
	return StatusType_STATUS_TYPE_OK
}

func (x *OptionQuote) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *OptionQuote) GetAcceptVCard() bool {
	if x != nil {
		return x.AcceptVCard
	}
	return false
}

func (x *OptionQuote) GetSurcharges() []*Surcharge {
	if x != nil {
		return x.Surcharges
	}
	return nil
}

func (x *OptionQuote) GetCancelPolicy() *CancelPolicy {
	if x != nil {
		return x.CancelPolicy
	}
	return nil
}

func (x *OptionQuote) GetRemarks() []*TypeValue {
	if x != nil {
		return x.Remarks
	}
	return nil
}

var File_domain_response_quote_response_hotels_proto protoreflect.FileDescriptor

const file_domain_response_quote_response_hotels_proto_rawDesc = "" +
	"\n" +
	"+domain/response/quote-response-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a,domain/response/common-response-hotels.proto\x1a-domain/response/booking-response-hotels.proto\"\x8d\x03\n" +
	"\rQuoteResponse\x12L\n" +
	"\tauditData\x18\x01 \x01(\v2..com_bundleport_connect_proto_hotels.AuditDataR\tauditData\x12B\n" +
	"\x06errors\x18\x02 \x03(\v2*.com_bundleport_connect_proto_hotels.ErrorR\x06errors\x12H\n" +
	"\bwarnings\x18\x03 \x03(\v2,.com_bundleport_connect_proto_hotels.WarningR\bwarnings\x12L\n" +
	"\tdebugData\x18\x04 \x03(\v2..com_bundleport_connect_proto_hotels.TypeValueR\tdebugData\x12R\n" +
	"\voptionQuote\x18\x05 \x01(\v20.com_bundleport_connect_proto_hotels.OptionQuoteR\voptionQuote\"\xcd\x03\n" +
	"\vOptionQuote\x12 \n" +
	"\voptionRefId\x18\x01 \x01(\tR\voptionRefId\x12G\n" +
	"\x06status\x18\x02 \x01(\x0e2/.com_bundleport_connect_proto_hotels.StatusTypeR\x06status\x12@\n" +
	"\x05price\x18\x03 \x01(\v2*.com_bundleport_connect_proto_hotels.PriceR\x05price\x12 \n" +
	"\vacceptVCard\x18\x04 \x01(\bR\vacceptVCard\x12N\n" +
	"\n" +
	"surcharges\x18\x05 \x03(\v2..com_bundleport_connect_proto_hotels.SurchargeR\n" +
	"surcharges\x12U\n" +
	"\fcancelPolicy\x18\x06 \x01(\v21.com_bundleport_connect_proto_hotels.CancelPolicyR\fcancelPolicy\x12H\n" +
	"\aremarks\x18\a \x03(\v2..com_bundleport_connect_proto_hotels.TypeValueR\aremarksB\x81\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x13QuoteResponseProtosP\x01Z.github.com/bundleport/connect-hotels-go/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_response_quote_response_hotels_proto_rawDescOnce sync.Once
	file_domain_response_quote_response_hotels_proto_rawDescData []byte
)

func file_domain_response_quote_response_hotels_proto_rawDescGZIP() []byte {
	file_domain_response_quote_response_hotels_proto_rawDescOnce.Do(func() {
		file_domain_response_quote_response_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_response_quote_response_hotels_proto_rawDesc), len(file_domain_response_quote_response_hotels_proto_rawDesc)))
	})
	return file_domain_response_quote_response_hotels_proto_rawDescData
}

var file_domain_response_quote_response_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_domain_response_quote_response_hotels_proto_goTypes = []any{
	(*QuoteResponse)(nil), // 0: com_bundleport_connect_proto_hotels.QuoteResponse
	(*OptionQuote)(nil),   // 1: com_bundleport_connect_proto_hotels.OptionQuote
	(*AuditData)(nil),     // 2: com_bundleport_connect_proto_hotels.AuditData
	(*Error)(nil),         // 3: com_bundleport_connect_proto_hotels.Error
	(*Warning)(nil),       // 4: com_bundleport_connect_proto_hotels.Warning
	(*TypeValue)(nil),     // 5: com_bundleport_connect_proto_hotels.TypeValue
	(StatusType)(0),       // 6: com_bundleport_connect_proto_hotels.StatusType
	(*Price)(nil),         // 7: com_bundleport_connect_proto_hotels.Price
	(*Surcharge)(nil),     // 8: com_bundleport_connect_proto_hotels.Surcharge
	(*CancelPolicy)(nil),  // 9: com_bundleport_connect_proto_hotels.CancelPolicy
}
var file_domain_response_quote_response_hotels_proto_depIdxs = []int32{
	2,  // 0: com_bundleport_connect_proto_hotels.QuoteResponse.auditData:type_name -> com_bundleport_connect_proto_hotels.AuditData
	3,  // 1: com_bundleport_connect_proto_hotels.QuoteResponse.errors:type_name -> com_bundleport_connect_proto_hotels.Error
	4,  // 2: com_bundleport_connect_proto_hotels.QuoteResponse.warnings:type_name -> com_bundleport_connect_proto_hotels.Warning
	5,  // 3: com_bundleport_connect_proto_hotels.QuoteResponse.debugData:type_name -> com_bundleport_connect_proto_hotels.TypeValue
	1,  // 4: com_bundleport_connect_proto_hotels.QuoteResponse.optionQuote:type_name -> com_bundleport_connect_proto_hotels.OptionQuote
	6,  // 5: com_bundleport_connect_proto_hotels.OptionQuote.status:type_name -> com_bundleport_connect_proto_hotels.StatusType
	7,  // 6: com_bundleport_connect_proto_hotels.OptionQuote.price:type_name -> com_bundleport_connect_proto_hotels.Price
	8,  // 7: com_bundleport_connect_proto_hotels.OptionQuote.surcharges:type_name -> com_bundleport_connect_proto_hotels.Surcharge
	9,  // 8: com_bundleport_connect_proto_hotels.OptionQuote.cancelPolicy:type_name -> com_bundleport_connect_proto_hotels.CancelPolicy
	5,  // 9: com_bundleport_connect_proto_hotels.OptionQuote.remarks:type_name -> com_bundleport_connect_proto_hotels.TypeValue
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_domain_response_quote_response_hotels_proto_init() }
func file_domain_response_quote_response_hotels_proto_init() {
	if File_domain_response_quote_response_hotels_proto != nil {
		return
	}
	file_domain_response_common_response_hotels_proto_init()
	file_domain_response_booking_response_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_response_quote_response_hotels_proto_rawDesc), len(file_domain_response_quote_response_hotels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_response_quote_response_hotels_proto_goTypes,
		DependencyIndexes: file_domain_response_quote_response_hotels_proto_depIdxs,
		MessageInfos:      file_domain_response_quote_response_hotels_proto_msgTypes,
	}.Build()
	File_domain_response_quote_response_hotels_proto = out.File
	file_domain_response_quote_response_hotels_proto_goTypes = nil
	file_domain_response_quote_response_hotels_proto_depIdxs = nil
}
