// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/request/quote-request-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QuoteRequest asks providers to confirm the price of a selected option.
type QuoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Quote criteria describing the option to be repriced.
	Criteria *CriteriaQuoteInput `protobuf:"bytes,1,opt,name=criteria,proto3" json:"criteria,omitempty"`
	// Execution settings shared across aggregator requests.
	Settings      *SettingsInput `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	mi := &file_domain_request_quote_request_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_quote_request_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return file_domain_request_quote_request_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *QuoteRequest) GetCriteria() *CriteriaQuoteInput {
	if x != nil {
		return x.Criteria
	}
	return nil
}

func (x *QuoteRequest) GetSettings() *SettingsInput {
	if x != nil {
		return x.Settings
	}
	return nil
}

// CriteriaQuoteInput identifies the option that must be confirmed.
type CriteriaQuoteInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Aggregator option identifier returned by the search response.
	OptionRefId string `protobuf:"bytes,1,opt,name=optionRefId,proto3" json:"optionRefId,omitempty"`
	// ISO 639-1 language code for textual content.
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	// Additional provider-specific parameters forwarded untouched.
	AdditionalData map[string]string `protobuf:"bytes,3,rep,name=additionalData,proto3" json:"additionalData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CriteriaQuoteInput) Reset() {
	*x = CriteriaQuoteInput{}
	mi := &file_domain_request_quote_request_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriteriaQuoteInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriteriaQuoteInput) ProtoMessage() {}

func (x *CriteriaQuoteInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_quote_request_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriteriaQuoteInput.ProtoReflect.Descriptor instead.
func (*CriteriaQuoteInput) Descriptor() ([]byte, []int) {
	return file_domain_request_quote_request_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *CriteriaQuoteInput) GetOptionRefId() string {
	if x != nil {
		return x.OptionRefId
	}
	return ""
}

func (x *CriteriaQuoteInput) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CriteriaQuoteInput) GetAdditionalData() map[string]string {
	if x != nil {
		return x.AdditionalData
	}
	return nil
}

var File_domain_request_quote_request_hotels_proto protoreflect.FileDescriptor

const file_domain_request_quote_request_hotels_proto_rawDesc = "" +
	"\n" +
	")domain/request/quote-request-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a*domain/request/common-request-hotels.proto\"\xb3\x01\n" +
	"\fQuoteRequest\x12S\n" +
	"\bcriteria\x18\x01 \x01(\v27.com_bundleport_connect_proto_hotels.CriteriaQuoteInputR\bcriteria\x12N\n" +
	"\bsettings\x18\x02 \x01(\v22.com_bundleport_connect_proto_hotels.SettingsInputR\bsettings\"\x8a\x02\n" +
	"\x12CriteriaQuoteInput\x12 \n" +
	"\voptionRefId\x18\x01 \x01(\tR\voptionRefId\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12s\n" +
	"\x0eadditionalData\x18\x03 \x03(\v2K.com_bundleport_connect_proto_hotels.CriteriaQuoteInput.AdditionalDataEntryR\x0eadditionalData\x1aA\n" +
	"\x13AdditionalDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x80\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x12QuoteRequestProtosP\x01Z.github.com/bundleport/connect-go-schema/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_request_quote_request_hotels_proto_rawDescOnce sync.Once
	file_domain_request_quote_request_hotels_proto_rawDescData []byte
)

func file_domain_request_quote_request_hotels_proto_rawDescGZIP() []byte {
	file_domain_request_quote_request_hotels_proto_rawDescOnce.Do(func() {
		file_domain_request_quote_request_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_request_quote_request_hotels_proto_rawDesc), len(file_domain_request_quote_request_hotels_proto_rawDesc)))
	})
	return file_domain_request_quote_request_hotels_proto_rawDescData
}

var file_domain_request_quote_request_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_domain_request_quote_request_hotels_proto_goTypes = []any{
	(*QuoteRequest)(nil),       // 0: com_bundleport_connect_proto_hotels.QuoteRequest
	(*CriteriaQuoteInput)(nil), // 1: com_bundleport_connect_proto_hotels.CriteriaQuoteInput
	nil,                        // 2: com_bundleport_connect_proto_hotels.CriteriaQuoteInput.AdditionalDataEntry
	(*SettingsInput)(nil),      // 3: com_bundleport_connect_proto_hotels.SettingsInput
}
var file_domain_request_quote_request_hotels_proto_depIdxs = []int32{
	1, // 0: com_bundleport_connect_proto_hotels.QuoteRequest.criteria:type_name -> com_bundleport_connect_proto_hotels.CriteriaQuoteInput
	3, // 1: com_bundleport_connect_proto_hotels.QuoteRequest.settings:type_name -> com_bundleport_connect_proto_hotels.SettingsInput
	2, // 2: com_bundleport_connect_proto_hotels.CriteriaQuoteInput.additionalData:type_name -> com_bundleport_connect_proto_hotels.CriteriaQuoteInput.AdditionalDataEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_domain_request_quote_request_hotels_proto_init() }
func file_domain_request_quote_request_hotels_proto_init() {
	if File_domain_request_quote_request_hotels_proto != nil {
		return
	}
	file_domain_request_common_request_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_request_quote_request_hotels_proto_rawDesc), len(file_domain_request_quote_request_hotels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_request_quote_request_hotels_proto_goTypes,
		DependencyIndexes: file_domain_request_quote_request_hotels_proto_depIdxs,
		MessageInfos:      file_domain_request_quote_request_hotels_proto_msgTypes,
	}.Build()
	File_domain_request_quote_request_hotels_proto = out.File
	file_domain_request_quote_request_hotels_proto_goTypes = nil
	file_domain_request_quote_request_hotels_proto_depIdxs = nil
}
