// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/response/rooms-response-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetRoomsResponse returns room metadata for the requested hotels.
type GetRoomsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request audit information and downstream trace ids.
	AuditData *AuditData `protobuf:"bytes,1,opt,name=auditData,proto3" json:"auditData,omitempty"`
	// Blocking errors encountered while fetching room data.
	Errors []*Error `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	// Non-blocking warnings returned alongside the room data.
	Warnings []*Warning `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	// Additional debug data for diagnostic purposes.
	DebugData []*TypeValue `protobuf:"bytes,4,rep,name=debugData,proto3" json:"debugData,omitempty"`
	// Room records that match the request criteria.
	Rooms []*RoomData `protobuf:"bytes,5,rep,name=rooms,proto3" json:"rooms,omitempty"`
	// Pagination token to retrieve the next batch of rooms.
	Token         string `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomsResponse) Reset() {
	*x = GetRoomsResponse{}
	mi := &file_domain_response_rooms_response_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsResponse) ProtoMessage() {}

func (x *GetRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_rooms_response_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsResponse.ProtoReflect.Descriptor instead.
func (*GetRoomsResponse) Descriptor() ([]byte, []int) {
	return file_domain_response_rooms_response_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *GetRoomsResponse) GetAuditData() *AuditData {
	if x != nil {
		return x.AuditData
	}
	return nil
}

func (x *GetRoomsResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *GetRoomsResponse) GetWarnings() []*Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *GetRoomsResponse) GetDebugData() []*TypeValue {
	if x != nil {
		return x.DebugData
	}
	return nil
}

func (x *GetRoomsResponse) GetRooms() []*RoomData {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *GetRoomsResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// RoomData contains descriptive information for a room type.
type RoomData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room identifier unique within the hotel.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Localised room descriptions.
	Descriptions []*Descriptions `protobuf:"bytes,3,rep,name=descriptions,proto3" json:"descriptions,omitempty"`
	// Occupancy limits for the room.
	Occupancies *OccupancyCount `protobuf:"bytes,4,opt,name=occupancies,proto3" json:"occupancies,omitempty"`
	// Media assets associated with the room.
	Images []*ImagesData `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	// Bed configuration information.
	Beds          []*BedsData `protobuf:"bytes,7,rep,name=beds,proto3" json:"beds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomData) Reset() {
	*x = RoomData{}
	mi := &file_domain_response_rooms_response_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomData) ProtoMessage() {}

func (x *RoomData) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_rooms_response_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomData.ProtoReflect.Descriptor instead.
func (*RoomData) Descriptor() ([]byte, []int) {
	return file_domain_response_rooms_response_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *RoomData) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RoomData) GetDescriptions() []*Descriptions {
	if x != nil {
		return x.Descriptions
	}
	return nil
}

func (x *RoomData) GetOccupancies() *OccupancyCount {
	if x != nil {
		return x.Occupancies
	}
	return nil
}

func (x *RoomData) GetImages() []*ImagesData {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *RoomData) GetBeds() []*BedsData {
	if x != nil {
		return x.Beds
	}
	return nil
}

// Descriptions holds textual content for a room.
type Descriptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Description text.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// ISO 639-1 language code for the description.
	Languaje      string `protobuf:"bytes,2,opt,name=languaje,proto3" json:"languaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Descriptions) Reset() {
	*x = Descriptions{}
	mi := &file_domain_response_rooms_response_hotels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Descriptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Descriptions) ProtoMessage() {}

func (x *Descriptions) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_rooms_response_hotels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Descriptions.ProtoReflect.Descriptor instead.
func (*Descriptions) Descriptor() ([]byte, []int) {
	return file_domain_response_rooms_response_hotels_proto_rawDescGZIP(), []int{2}
}

func (x *Descriptions) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Descriptions) GetLanguaje() string {
	if x != nil {
		return x.Languaje
	}
	return ""
}

// OccupancyCount describes the maximum occupancy for a room.
type OccupancyCount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of adults.
	Adults int32 `protobuf:"varint,1,opt,name=adults,proto3" json:"adults,omitempty"`
	// Maximum number of children.
	Childrens int32 `protobuf:"varint,2,opt,name=childrens,proto3" json:"childrens,omitempty"`
	// Maximum total occupancy, adults plus children.
	Total         int32 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OccupancyCount) Reset() {
	*x = OccupancyCount{}
	mi := &file_domain_response_rooms_response_hotels_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OccupancyCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OccupancyCount) ProtoMessage() {}

func (x *OccupancyCount) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_rooms_response_hotels_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OccupancyCount.ProtoReflect.Descriptor instead.
func (*OccupancyCount) Descriptor() ([]byte, []int) {
	return file_domain_response_rooms_response_hotels_proto_rawDescGZIP(), []int{3}
}

func (x *OccupancyCount) GetAdults() int32 {
	if x != nil {
		return x.Adults
	}
	return 0
}

func (x *OccupancyCount) GetChildrens() int32 {
	if x != nil {
		return x.Childrens
	}
	return 0
}

func (x *OccupancyCount) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ImagesData contains metadata for room media assets.
type ImagesData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Media identifier.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Display order for the image.
	Order string `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	// Public URL for the image asset.
	Url           string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagesData) Reset() {
	*x = ImagesData{}
	mi := &file_domain_response_rooms_response_hotels_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagesData) ProtoMessage() {}

func (x *ImagesData) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_rooms_response_hotels_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagesData.ProtoReflect.Descriptor instead.
func (*ImagesData) Descriptor() ([]byte, []int) {
	return file_domain_response_rooms_response_hotels_proto_rawDescGZIP(), []int{4}
}

func (x *ImagesData) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ImagesData) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *ImagesData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// BedsData describes the bed configuration in a room.
type BedsData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bed type such as KING or TWIN.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Number of beds of the specified type.
	Count         int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BedsData) Reset() {
	*x = BedsData{}
	mi := &file_domain_response_rooms_response_hotels_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BedsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedsData) ProtoMessage() {}

func (x *BedsData) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_rooms_response_hotels_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedsData.ProtoReflect.Descriptor instead.
func (*BedsData) Descriptor() ([]byte, []int) {
	return file_domain_response_rooms_response_hotels_proto_rawDescGZIP(), []int{5}
}

func (x *BedsData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BedsData) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_domain_response_rooms_response_hotels_proto protoreflect.FileDescriptor

const file_domain_response_rooms_response_hotels_proto_rawDesc = "" +
	"\n" +
	"+domain/response/rooms-response-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a,domain/response/common-response-hotels.proto\"\x97\x03\n" +
	"\x10GetRoomsResponse\x12L\n" +
	"\tauditData\x18\x01 \x01(\v2..com_bundleport_connect_proto_hotels.AuditDataR\tauditData\x12B\n" +
	"\x06errors\x18\x02 \x03(\v2*.com_bundleport_connect_proto_hotels.ErrorR\x06errors\x12H\n" +
	"\bwarnings\x18\x03 \x03(\v2,.com_bundleport_connect_proto_hotels.WarningR\bwarnings\x12L\n" +
	"\tdebugData\x18\x04 \x03(\v2..com_bundleport_connect_proto_hotels.TypeValueR\tdebugData\x12C\n" +
	"\x05rooms\x18\x05 \x03(\v2-.com_bundleport_connect_proto_hotels.RoomDataR\x05rooms\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\"\xd8\x02\n" +
	"\bRoomData\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12U\n" +
	"\fdescriptions\x18\x03 \x03(\v21.com_bundleport_connect_proto_hotels.DescriptionsR\fdescriptions\x12U\n" +
	"\voccupancies\x18\x04 \x01(\v23.com_bundleport_connect_proto_hotels.OccupancyCountR\voccupancies\x12G\n" +
	"\x06images\x18\x06 \x03(\v2/.com_bundleport_connect_proto_hotels.ImagesDataR\x06images\x12A\n" +
	"\x04beds\x18\a \x03(\v2-.com_bundleport_connect_proto_hotels.BedsDataR\x04beds\">\n" +
	"\fDescriptions\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguaje\x18\x02 \x01(\tR\blanguaje\"\\\n" +
	"\x0eOccupancyCount\x12\x16\n" +
	"\x06adults\x18\x01 \x01(\x05R\x06adults\x12\x1c\n" +
	"\tchildrens\x18\x02 \x01(\x05R\tchildrens\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\"H\n" +
	"\n" +
	"ImagesData\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05order\x18\x02 \x01(\tR\x05order\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"4\n" +
	"\bBedsData\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05countB\x81\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x13RoomsResponseProtosP\x01Z.github.com/bundleport/connect-hotels-go/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_response_rooms_response_hotels_proto_rawDescOnce sync.Once
	file_domain_response_rooms_response_hotels_proto_rawDescData []byte
)

func file_domain_response_rooms_response_hotels_proto_rawDescGZIP() []byte {
	file_domain_response_rooms_response_hotels_proto_rawDescOnce.Do(func() {
		file_domain_response_rooms_response_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_response_rooms_response_hotels_proto_rawDesc), len(file_domain_response_rooms_response_hotels_proto_rawDesc)))
	})
	return file_domain_response_rooms_response_hotels_proto_rawDescData
}

var file_domain_response_rooms_response_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_domain_response_rooms_response_hotels_proto_goTypes = []any{
	(*GetRoomsResponse)(nil), // 0: com_bundleport_connect_proto_hotels.GetRoomsResponse
	(*RoomData)(nil),         // 1: com_bundleport_connect_proto_hotels.RoomData
	(*Descriptions)(nil),     // 2: com_bundleport_connect_proto_hotels.Descriptions
	(*OccupancyCount)(nil),   // 3: com_bundleport_connect_proto_hotels.OccupancyCount
	(*ImagesData)(nil),       // 4: com_bundleport_connect_proto_hotels.ImagesData
	(*BedsData)(nil),         // 5: com_bundleport_connect_proto_hotels.BedsData
	(*AuditData)(nil),        // 6: com_bundleport_connect_proto_hotels.AuditData
	(*Error)(nil),            // 7: com_bundleport_connect_proto_hotels.Error
	(*Warning)(nil),          // 8: com_bundleport_connect_proto_hotels.Warning
	(*TypeValue)(nil),        // 9: com_bundleport_connect_proto_hotels.TypeValue
}
var file_domain_response_rooms_response_hotels_proto_depIdxs = []int32{
	6, // 0: com_bundleport_connect_proto_hotels.GetRoomsResponse.auditData:type_name -> com_bundleport_connect_proto_hotels.AuditData
	7, // 1: com_bundleport_connect_proto_hotels.GetRoomsResponse.errors:type_name -> com_bundleport_connect_proto_hotels.Error
	8, // 2: com_bundleport_connect_proto_hotels.GetRoomsResponse.warnings:type_name -> com_bundleport_connect_proto_hotels.Warning
	9, // 3: com_bundleport_connect_proto_hotels.GetRoomsResponse.debugData:type_name -> com_bundleport_connect_proto_hotels.TypeValue
	1, // 4: com_bundleport_connect_proto_hotels.GetRoomsResponse.rooms:type_name -> com_bundleport_connect_proto_hotels.RoomData
	2, // 5: com_bundleport_connect_proto_hotels.RoomData.descriptions:type_name -> com_bundleport_connect_proto_hotels.Descriptions
	3, // 6: com_bundleport_connect_proto_hotels.RoomData.occupancies:type_name -> com_bundleport_connect_proto_hotels.OccupancyCount
	4, // 7: com_bundleport_connect_proto_hotels.RoomData.images:type_name -> com_bundleport_connect_proto_hotels.ImagesData
	5, // 8: com_bundleport_connect_proto_hotels.RoomData.beds:type_name -> com_bundleport_connect_proto_hotels.BedsData
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_domain_response_rooms_response_hotels_proto_init() }
func file_domain_response_rooms_response_hotels_proto_init() {
	if File_domain_response_rooms_response_hotels_proto != nil {
		return
	}
	file_domain_response_common_response_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_response_rooms_response_hotels_proto_rawDesc), len(file_domain_response_rooms_response_hotels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_response_rooms_response_hotels_proto_goTypes,
		DependencyIndexes: file_domain_response_rooms_response_hotels_proto_depIdxs,
		MessageInfos:      file_domain_response_rooms_response_hotels_proto_msgTypes,
	}.Build()
	File_domain_response_rooms_response_hotels_proto = out.File
	file_domain_response_rooms_response_hotels_proto_goTypes = nil
	file_domain_response_rooms_response_hotels_proto_depIdxs = nil
}
