// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/response/search-response-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RateRulesType indicates special commercial rules applied by providers.
type RateRulesType int32

const (
	// No rule specified by the provider.
	RateRulesType_RATE_RULES_UNSPECIFIED RateRulesType = 0
	// Rate restricted to Balearic residents.
	RateRulesType_RATE_RULES_BALEARIC_RESIDENT RateRulesType = 1
	// Rate restricted to Canary residents.
	RateRulesType_RATE_RULES_CANARY_RESIDENT RateRulesType = 2
	// Custom rule defined by the provider.
	RateRulesType_RATE_RULES_CUSTOM RateRulesType = 3
	// Rate reserved for essential workers.
	RateRulesType_RATE_RULES_ESSENTIAL_WORKER RateRulesType = 4
	// Honeymoon promotion or inclusions.
	RateRulesType_RATE_RULES_HONEYMOON RateRulesType = 5
	// Large family discount or inclusions.
	RateRulesType_RATE_RULES_LARGE_FAMILY RateRulesType = 6
	// Mobile-only promotion.
	RateRulesType_RATE_RULES_MOBILE RateRulesType = 7
	// Negotiated contract.
	RateRulesType_RATE_RULES_NEGOTIATED RateRulesType = 8
	// Corporate agreement.
	RateRulesType_RATE_RULES_CORPORATE RateRulesType = 9
	// Discount for travellers aged 55 or older.
	RateRulesType_RATE_RULES_OLDER55 RateRulesType = 10
	// Discount for travellers aged 60 or older.
	RateRulesType_RATE_RULES_OLDER60 RateRulesType = 11
	// Discount for travellers aged 65 or older.
	RateRulesType_RATE_RULES_OLDER65 RateRulesType = 12
	// Package or bundled offer.
	RateRulesType_RATE_RULES_PACKAGE RateRulesType = 13
	// Public servant promotion.
	RateRulesType_RATE_RULES_PUBLIC_SERVANT RateRulesType = 14
	// Special rate for unemployed travellers.
	RateRulesType_RATE_RULES_UNEMPLOYED RateRulesType = 15
	// Rate subject to warranty terms.
	RateRulesType_RATE_RULES_WARRANTY RateRulesType = 16
)

// Enum value maps for RateRulesType.
var (
	RateRulesType_name = map[int32]string{
		0:  "RATE_RULES_UNSPECIFIED",
		1:  "RATE_RULES_BALEARIC_RESIDENT",
		2:  "RATE_RULES_CANARY_RESIDENT",
		3:  "RATE_RULES_CUSTOM",
		4:  "RATE_RULES_ESSENTIAL_WORKER",
		5:  "RATE_RULES_HONEYMOON",
		6:  "RATE_RULES_LARGE_FAMILY",
		7:  "RATE_RULES_MOBILE",
		8:  "RATE_RULES_NEGOTIATED",
		9:  "RATE_RULES_CORPORATE",
		10: "RATE_RULES_OLDER55",
		11: "RATE_RULES_OLDER60",
		12: "RATE_RULES_OLDER65",
		13: "RATE_RULES_PACKAGE",
		14: "RATE_RULES_PUBLIC_SERVANT",
		15: "RATE_RULES_UNEMPLOYED",
		16: "RATE_RULES_WARRANTY",
	}
	RateRulesType_value = map[string]int32{
		"RATE_RULES_UNSPECIFIED":       0,
		"RATE_RULES_BALEARIC_RESIDENT": 1,
		"RATE_RULES_CANARY_RESIDENT":   2,
		"RATE_RULES_CUSTOM":            3,
		"RATE_RULES_ESSENTIAL_WORKER":  4,
		"RATE_RULES_HONEYMOON":         5,
		"RATE_RULES_LARGE_FAMILY":      6,
		"RATE_RULES_MOBILE":            7,
		"RATE_RULES_NEGOTIATED":        8,
		"RATE_RULES_CORPORATE":         9,
		"RATE_RULES_OLDER55":           10,
		"RATE_RULES_OLDER60":           11,
		"RATE_RULES_OLDER65":           12,
		"RATE_RULES_PACKAGE":           13,
		"RATE_RULES_PUBLIC_SERVANT":    14,
		"RATE_RULES_UNEMPLOYED":        15,
		"RATE_RULES_WARRANTY":          16,
	}
)

func (x RateRulesType) Enum() *RateRulesType {
	p := new(RateRulesType)
	*p = x
	return p
}

func (x RateRulesType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RateRulesType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_response_search_response_hotels_proto_enumTypes[0].Descriptor()
}

func (RateRulesType) Type() protoreflect.EnumType {
	return &file_domain_response_search_response_hotels_proto_enumTypes[0]
}

func (x RateRulesType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RateRulesType.Descriptor instead.
func (RateRulesType) EnumDescriptor() ([]byte, []int) {
	return file_domain_response_search_response_hotels_proto_rawDescGZIP(), []int{0}
}

// SearchTracingStatusType categorises the overall search result.
type SearchTracingStatusType int32

const (
	// Request completed successfully.
	SearchTracingStatusType_SEARCH_TRACING_STATUS_OK SearchTracingStatusType = 0
	// Request completed without returning options.
	SearchTracingStatusType_SEARCH_TRACING_STATUS_OK_NO_RESULTS SearchTracingStatusType = 1
	// Request completed with warnings.
	SearchTracingStatusType_SEARCH_TRACING_STATUS_OK_WARNINGS SearchTracingStatusType = 2
	// Request completed but warnings were generated.
	SearchTracingStatusType_SEARCH_TRACING_STATUS_WARNINGS SearchTracingStatusType = 3
	// Request failed with errors.
	SearchTracingStatusType_SEARCH_TRACING_STATUS_ERRORS SearchTracingStatusType = 4
	// Outcome could not be determined.
	SearchTracingStatusType_SEARCH_TRACING_STATUS_UNKNOWN SearchTracingStatusType = 5
	// Partial success with data missing from some providers.
	SearchTracingStatusType_SEARCH_TRACING_STATUS_PARTIAL SearchTracingStatusType = 6
	// Partial success with warnings or errors reported.
	SearchTracingStatusType_SEARCH_TRACING_STATUS_PARTIAL_WITH_WARNINGS_ERRORS SearchTracingStatusType = 7
	// Providers responded with warnings and errors.
	SearchTracingStatusType_SEARCH_TRACING_STATUS_WARNINGS_ERRORS SearchTracingStatusType = 8
)

// Enum value maps for SearchTracingStatusType.
var (
	SearchTracingStatusType_name = map[int32]string{
		0: "SEARCH_TRACING_STATUS_OK",
		1: "SEARCH_TRACING_STATUS_OK_NO_RESULTS",
		2: "SEARCH_TRACING_STATUS_OK_WARNINGS",
		3: "SEARCH_TRACING_STATUS_WARNINGS",
		4: "SEARCH_TRACING_STATUS_ERRORS",
		5: "SEARCH_TRACING_STATUS_UNKNOWN",
		6: "SEARCH_TRACING_STATUS_PARTIAL",
		7: "SEARCH_TRACING_STATUS_PARTIAL_WITH_WARNINGS_ERRORS",
		8: "SEARCH_TRACING_STATUS_WARNINGS_ERRORS",
	}
	SearchTracingStatusType_value = map[string]int32{
		"SEARCH_TRACING_STATUS_OK":                           0,
		"SEARCH_TRACING_STATUS_OK_NO_RESULTS":                1,
		"SEARCH_TRACING_STATUS_OK_WARNINGS":                  2,
		"SEARCH_TRACING_STATUS_WARNINGS":                     3,
		"SEARCH_TRACING_STATUS_ERRORS":                       4,
		"SEARCH_TRACING_STATUS_UNKNOWN":                      5,
		"SEARCH_TRACING_STATUS_PARTIAL":                      6,
		"SEARCH_TRACING_STATUS_PARTIAL_WITH_WARNINGS_ERRORS": 7,
		"SEARCH_TRACING_STATUS_WARNINGS_ERRORS":              8,
	}
)

func (x SearchTracingStatusType) Enum() *SearchTracingStatusType {
	p := new(SearchTracingStatusType)
	*p = x
	return p
}

func (x SearchTracingStatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchTracingStatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_response_search_response_hotels_proto_enumTypes[1].Descriptor()
}

func (SearchTracingStatusType) Type() protoreflect.EnumType {
	return &file_domain_response_search_response_hotels_proto_enumTypes[1]
}

func (x SearchTracingStatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchTracingStatusType.Descriptor instead.
func (SearchTracingStatusType) EnumDescriptor() ([]byte, []int) {
	return file_domain_response_search_response_hotels_proto_rawDescGZIP(), []int{1}
}

// SearchTracingSpanStatusType categorises an individual provider call.
type SearchTracingSpanStatusType int32

const (
	// Provider returned data successfully.
	SearchTracingSpanStatusType_SEARCH_TRACING_SPAN_STATUS_OK SearchTracingSpanStatusType = 0
	// Provider returned successfully without results.
	SearchTracingSpanStatusType_SEARCH_TRACING_SPAN_STATUS_OK_NO_RESULTS SearchTracingSpanStatusType = 1
	// Provider returned successfully and included warnings.
	SearchTracingSpanStatusType_SEARCH_TRACING_SPAN_STATUS_OK_WARNINGS SearchTracingSpanStatusType = 2
	// Provider returned only warnings.
	SearchTracingSpanStatusType_SEARCH_TRACING_SPAN_STATUS_WARNINGS SearchTracingSpanStatusType = 3
	// Provider returned errors.
	SearchTracingSpanStatusType_SEARCH_TRACING_SPAN_STATUS_ERRORS SearchTracingSpanStatusType = 4
	// Response was served from cache.
	SearchTracingSpanStatusType_SEARCH_TRACING_SPAN_STATUS_CACHED SearchTracingSpanStatusType = 15
)

// Enum value maps for SearchTracingSpanStatusType.
var (
	SearchTracingSpanStatusType_name = map[int32]string{
		0:  "SEARCH_TRACING_SPAN_STATUS_OK",
		1:  "SEARCH_TRACING_SPAN_STATUS_OK_NO_RESULTS",
		2:  "SEARCH_TRACING_SPAN_STATUS_OK_WARNINGS",
		3:  "SEARCH_TRACING_SPAN_STATUS_WARNINGS",
		4:  "SEARCH_TRACING_SPAN_STATUS_ERRORS",
		15: "SEARCH_TRACING_SPAN_STATUS_CACHED",
	}
	SearchTracingSpanStatusType_value = map[string]int32{
		"SEARCH_TRACING_SPAN_STATUS_OK":            0,
		"SEARCH_TRACING_SPAN_STATUS_OK_NO_RESULTS": 1,
		"SEARCH_TRACING_SPAN_STATUS_OK_WARNINGS":   2,
		"SEARCH_TRACING_SPAN_STATUS_WARNINGS":      3,
		"SEARCH_TRACING_SPAN_STATUS_ERRORS":        4,
		"SEARCH_TRACING_SPAN_STATUS_CACHED":        15,
	}
)

func (x SearchTracingSpanStatusType) Enum() *SearchTracingSpanStatusType {
	p := new(SearchTracingSpanStatusType)
	*p = x
	return p
}

func (x SearchTracingSpanStatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchTracingSpanStatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_response_search_response_hotels_proto_enumTypes[2].Descriptor()
}

func (SearchTracingSpanStatusType) Type() protoreflect.EnumType {
	return &file_domain_response_search_response_hotels_proto_enumTypes[2]
}

func (x SearchTracingSpanStatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchTracingSpanStatusType.Descriptor instead.
func (SearchTracingSpanStatusType) EnumDescriptor() ([]byte, []int) {
	return file_domain_response_search_response_hotels_proto_rawDescGZIP(), []int{2}
}

// SearchResponse returns availability options along with audit metadata.
type SearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request audit information and downstream trace ids.
	AuditData *AuditData `protobuf:"bytes,1,opt,name=auditData,proto3" json:"auditData,omitempty"`
	// Blocking errors that prevented processing or returning results.
	Errors []*Error `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	// Non-blocking warnings generated during processing.
	Warnings []*Warning `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	// Extra diagnostic data returned when debug mode is enabled.
	DebugData []*TypeValue `protobuf:"bytes,4,rep,name=debugData,proto3" json:"debugData,omitempty"`
	// Availability options aggregated from providers.
	Options []*OptionSearch `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"`
	// Tracing details that summarise downstream provider performance.
	Tracing       *SearchTracing `protobuf:"bytes,6,opt,name=tracing,proto3" json:"tracing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_domain_response_search_response_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_search_response_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_domain_response_search_response_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *SearchResponse) GetAuditData() *AuditData {
	if x != nil {
		return x.AuditData
	}
	return nil
}

func (x *SearchResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *SearchResponse) GetWarnings() []*Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *SearchResponse) GetDebugData() []*TypeValue {
	if x != nil {
		return x.DebugData
	}
	return nil
}

func (x *SearchResponse) GetOptions() []*OptionSearch {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SearchResponse) GetTracing() *SearchTracing {
	if x != nil {
		return x.Tracing
	}
	return nil
}

// RateRule describes a special commercial condition applied to a rate.
type RateRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type categorising the rule.
	Type RateRulesType `protobuf:"varint,1,opt,name=type,proto3,enum=com_bundleport_connect_proto_hotels.RateRulesType" json:"type,omitempty"`
	// Free text description supplied by the provider.
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateRule) Reset() {
	*x = RateRule{}
	mi := &file_domain_response_search_response_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateRule) ProtoMessage() {}

func (x *RateRule) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_search_response_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateRule.ProtoReflect.Descriptor instead.
func (*RateRule) Descriptor() ([]byte, []int) {
	return file_domain_response_search_response_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *RateRule) GetType() RateRulesType {
	if x != nil {
		return x.Type
	}
	return RateRulesType_RATE_RULES_UNSPECIFIED
}

func (x *RateRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Room represents an available room for a specific occupancy.
type Room struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier that links the room to the requested occupancy.
	OccupancyRefId int32 `protobuf:"varint,1,opt,name=occupancyRefId,proto3" json:"occupancyRefId,omitempty"`
	// Provider room identifier.
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Room name or description.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Room total price including taxes or fees.
	RoomPrice *Price `protobuf:"bytes,4,opt,name=roomPrice,proto3" json:"roomPrice,omitempty"`
	// Rate plan that governs booking conditions.
	RatePlan *RatePlan `protobuf:"bytes,5,opt,name=ratePlan,proto3" json:"ratePlan,omitempty"`
	// Promotions applied to the room.
	Promotions []*Promotion `protobuf:"bytes,6,rep,name=promotions,proto3" json:"promotions,omitempty"`
	// Deprecated: number of units allocated for this room.
	//
	// Deprecated: Marked as deprecated in domain/response/search-response-hotels.proto.
	Units         int32 `protobuf:"varint,7,opt,name=units,proto3" json:"units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_domain_response_search_response_hotels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_search_response_hotels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_domain_response_search_response_hotels_proto_rawDescGZIP(), []int{2}
}

func (x *Room) GetOccupancyRefId() int32 {
	if x != nil {
		return x.OccupancyRefId
	}
	return 0
}

func (x *Room) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Room) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Room) GetRoomPrice() *Price {
	if x != nil {
		return x.RoomPrice
	}
	return nil
}

func (x *Room) GetRatePlan() *RatePlan {
	if x != nil {
		return x.RatePlan
	}
	return nil
}

func (x *Room) GetPromotions() []*Promotion {
	if x != nil {
		return x.Promotions
	}
	return nil
}

// Deprecated: Marked as deprecated in domain/response/search-response-hotels.proto.
func (x *Room) GetUnits() int32 {
	if x != nil {
		return x.Units
	}
	return 0
}

// RatePlan contains identifiers and descriptions for a provider rate plan.
type RatePlan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider rate plan code.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Display name for the rate plan.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatePlan) Reset() {
	*x = RatePlan{}
	mi := &file_domain_response_search_response_hotels_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatePlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatePlan) ProtoMessage() {}

func (x *RatePlan) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_search_response_hotels_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatePlan.ProtoReflect.Descriptor instead.
func (*RatePlan) Descriptor() ([]byte, []int) {
	return file_domain_response_search_response_hotels_proto_rawDescGZIP(), []int{3}
}

func (x *RatePlan) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RatePlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Promotion represents a commercial promotion applied to the offer.
type Promotion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Promotion identifier.
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Human readable promotion name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Promotion amount or percentage as provided by the supplier.
	Amount string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// Start date for the promotion validity window.
	EffectiveDate *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=effectiveDate,proto3" json:"effectiveDate,omitempty"`
	// End date for the promotion validity window.
	ExpireDate    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expireDate,proto3" json:"expireDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Promotion) Reset() {
	*x = Promotion{}
	mi := &file_domain_response_search_response_hotels_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Promotion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Promotion) ProtoMessage() {}

func (x *Promotion) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_search_response_hotels_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Promotion.ProtoReflect.Descriptor instead.
func (*Promotion) Descriptor() ([]byte, []int) {
	return file_domain_response_search_response_hotels_proto_rawDescGZIP(), []int{4}
}

func (x *Promotion) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Promotion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Promotion) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Promotion) GetEffectiveDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveDate
	}
	return nil
}

func (x *Promotion) GetExpireDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireDate
	}
	return nil
}

// OptionSearch groups rooms, pricing and policy data for a single offer.
type OptionSearch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Aggregator unique identifier for the option.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Access identifier that supplied the option.
	AccessId string `protobuf:"bytes,3,opt,name=accessId,proto3" json:"accessId,omitempty"`
	// Provider hotel identifier.
	HotelCode string `protobuf:"bytes,4,opt,name=hotelCode,proto3" json:"hotelCode,omitempty"`
	// Hotel name provided by the supplier.
	HotelName string `protobuf:"bytes,5,opt,name=hotelName,proto3" json:"hotelName,omitempty"`
	// Provider board code associated with the option.
	BoardCode string `protobuf:"bytes,6,opt,name=boardCode,proto3" json:"boardCode,omitempty"`
	// Descriptive board name.
	BoardName string `protobuf:"bytes,7,opt,name=boardName,proto3" json:"boardName,omitempty"`
	// Commercial rules that apply to the option rate.
	RateRules []*RateRule `protobuf:"bytes,8,rep,name=rateRules,proto3" json:"rateRules,omitempty"`
	// Rooms included in the option.
	Rooms []*Room `protobuf:"bytes,9,rep,name=rooms,proto3" json:"rooms,omitempty"`
	// Total price for the stay.
	Price *Price `protobuf:"bytes,10,opt,name=price,proto3" json:"price,omitempty"`
	// Payment type that dictates collection mechanics.
	PaymentType PaymentType `protobuf:"varint,11,opt,name=paymentType,proto3,enum=com_bundleport_connect_proto_hotels.PaymentType" json:"paymentType,omitempty"`
	// Optional surcharges applied to the booking.
	Surcharges []*Surcharge `protobuf:"bytes,12,rep,name=surcharges,proto3" json:"surcharges,omitempty"`
	// Cancellation policy describing penalties and windows.
	CancelPolicy *CancelPolicy `protobuf:"bytes,13,opt,name=cancelPolicy,proto3" json:"cancelPolicy,omitempty"`
	// Additional remarks or notes.
	Remarks []*TypeValue `protobuf:"bytes,14,rep,name=remarks,proto3" json:"remarks,omitempty"`
	// Indicates whether the option originated from cache instead of a live call.
	FromCache     bool `protobuf:"varint,15,opt,name=fromCache,proto3" json:"fromCache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionSearch) Reset() {
	*x = OptionSearch{}
	mi := &file_domain_response_search_response_hotels_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionSearch) ProtoMessage() {}

func (x *OptionSearch) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_search_response_hotels_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionSearch.ProtoReflect.Descriptor instead.
func (*OptionSearch) Descriptor() ([]byte, []int) {
	return file_domain_response_search_response_hotels_proto_rawDescGZIP(), []int{5}
}

func (x *OptionSearch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OptionSearch) GetAccessId() string {
	if x != nil {
		return x.AccessId
	}
	return ""
}

func (x *OptionSearch) GetHotelCode() string {
	if x != nil {
		return x.HotelCode
	}
	return ""
}

func (x *OptionSearch) GetHotelName() string {
	if x != nil {
		return x.HotelName
	}
	return ""
}

func (x *OptionSearch) GetBoardCode() string {
	if x != nil {
		return x.BoardCode
	}
	return ""
}

func (x *OptionSearch) GetBoardName() string {
	if x != nil {
		return x.BoardName
	}
	return ""
}

func (x *OptionSearch) GetRateRules() []*RateRule {
	if x != nil {
		return x.RateRules
	}
	return nil
}

func (x *OptionSearch) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *OptionSearch) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *OptionSearch) GetPaymentType() PaymentType {
	if x != nil {
		return x.PaymentType
	}
	return PaymentType_MERCHANT
}

func (x *OptionSearch) GetSurcharges() []*Surcharge {
	if x != nil {
		return x.Surcharges
	}
	return nil
}

func (x *OptionSearch) GetCancelPolicy() *CancelPolicy {
	if x != nil {
		return x.CancelPolicy
	}
	return nil
}

func (x *OptionSearch) GetRemarks() []*TypeValue {
	if x != nil {
		return x.Remarks
	}
	return nil
}

func (x *OptionSearch) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

// SearchTracing summarises how providers responded to the request.
type SearchTracing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall outcome of the request.
	Status SearchTracingStatusType `protobuf:"varint,1,opt,name=status,proto3,enum=com_bundleport_connect_proto_hotels.SearchTracingStatusType" json:"status,omitempty"`
	// Per-access spans representing each provider call.
	AccessSpans   []*SearchTracingAccessSpan `protobuf:"bytes,2,rep,name=accessSpans,proto3" json:"accessSpans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTracing) Reset() {
	*x = SearchTracing{}
	mi := &file_domain_response_search_response_hotels_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTracing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTracing) ProtoMessage() {}

func (x *SearchTracing) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_search_response_hotels_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTracing.ProtoReflect.Descriptor instead.
func (*SearchTracing) Descriptor() ([]byte, []int) {
	return file_domain_response_search_response_hotels_proto_rawDescGZIP(), []int{6}
}

func (x *SearchTracing) GetStatus() SearchTracingStatusType {
	if x != nil {
		return x.Status
	}
	return SearchTracingStatusType_SEARCH_TRACING_STATUS_OK
}

func (x *SearchTracing) GetAccessSpans() []*SearchTracingAccessSpan {
	if x != nil {
		return x.AccessSpans
	}
	return nil
}

// SearchTracingAccessSpan contains metrics for a single provider access.
type SearchTracingAccessSpan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the access that was called.
	Access string `protobuf:"bytes,1,opt,name=access,proto3" json:"access,omitempty"`
	// Result of the access call.
	Status SearchTracingSpanStatusType `protobuf:"varint,2,opt,name=status,proto3,enum=com_bundleport_connect_proto_hotels.SearchTracingSpanStatusType" json:"status,omitempty"`
	// Number of hotels requested from the provider.
	HotelsRequested int32 `protobuf:"varint,3,opt,name=hotelsRequested,proto3" json:"hotelsRequested,omitempty"`
	// Number of hotels returned by the provider.
	HotelsReturned int32 `protobuf:"varint,4,opt,name=hotelsReturned,proto3" json:"hotelsReturned,omitempty"`
	// Provider transactions for the access.
	Transactions  []*SearchTracingTransaction `protobuf:"bytes,6,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTracingAccessSpan) Reset() {
	*x = SearchTracingAccessSpan{}
	mi := &file_domain_response_search_response_hotels_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTracingAccessSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTracingAccessSpan) ProtoMessage() {}

func (x *SearchTracingAccessSpan) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_search_response_hotels_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTracingAccessSpan.ProtoReflect.Descriptor instead.
func (*SearchTracingAccessSpan) Descriptor() ([]byte, []int) {
	return file_domain_response_search_response_hotels_proto_rawDescGZIP(), []int{7}
}

func (x *SearchTracingAccessSpan) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *SearchTracingAccessSpan) GetStatus() SearchTracingSpanStatusType {
	if x != nil {
		return x.Status
	}
	return SearchTracingSpanStatusType_SEARCH_TRACING_SPAN_STATUS_OK
}

func (x *SearchTracingAccessSpan) GetHotelsRequested() int32 {
	if x != nil {
		return x.HotelsRequested
	}
	return 0
}

func (x *SearchTracingAccessSpan) GetHotelsReturned() int32 {
	if x != nil {
		return x.HotelsReturned
	}
	return 0
}

func (x *SearchTracingAccessSpan) GetTransactions() []*SearchTracingTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

// SearchTracingTransaction captures details of a provider invocation.
type SearchTracingTransaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the downstream transaction.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Status of the provider interaction.
	Status SearchTracingSpanStatusType `protobuf:"varint,2,opt,name=status,proto3,enum=com_bundleport_connect_proto_hotels.SearchTracingSpanStatusType" json:"status,omitempty"`
	// Duration in milliseconds.
	Duration      int32 `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTracingTransaction) Reset() {
	*x = SearchTracingTransaction{}
	mi := &file_domain_response_search_response_hotels_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTracingTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTracingTransaction) ProtoMessage() {}

func (x *SearchTracingTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_domain_response_search_response_hotels_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTracingTransaction.ProtoReflect.Descriptor instead.
func (*SearchTracingTransaction) Descriptor() ([]byte, []int) {
	return file_domain_response_search_response_hotels_proto_rawDescGZIP(), []int{8}
}

func (x *SearchTracingTransaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchTracingTransaction) GetStatus() SearchTracingSpanStatusType {
	if x != nil {
		return x.Status
	}
	return SearchTracingSpanStatusType_SEARCH_TRACING_SPAN_STATUS_OK
}

func (x *SearchTracingTransaction) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_domain_response_search_response_hotels_proto protoreflect.FileDescriptor

const file_domain_response_search_response_hotels_proto_rawDesc = "" +
	"\n" +
	",domain/response/search-response-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a\x1fgoogle/protobuf/timestamp.proto\x1a,domain/response/common-response-hotels.proto\x1a-domain/response/payment-response-hotels.proto\x1a-domain/response/booking-response-hotels.proto\"\xd5\x03\n" +
	"\x0eSearchResponse\x12L\n" +
	"\tauditData\x18\x01 \x01(\v2..com_bundleport_connect_proto_hotels.AuditDataR\tauditData\x12B\n" +
	"\x06errors\x18\x02 \x03(\v2*.com_bundleport_connect_proto_hotels.ErrorR\x06errors\x12H\n" +
	"\bwarnings\x18\x03 \x03(\v2,.com_bundleport_connect_proto_hotels.WarningR\bwarnings\x12L\n" +
	"\tdebugData\x18\x04 \x03(\v2..com_bundleport_connect_proto_hotels.TypeValueR\tdebugData\x12K\n" +
	"\aoptions\x18\x05 \x03(\v21.com_bundleport_connect_proto_hotels.OptionSearchR\aoptions\x12L\n" +
	"\atracing\x18\x06 \x01(\v22.com_bundleport_connect_proto_hotels.SearchTracingR\atracing\"t\n" +
	"\bRateRule\x12F\n" +
	"\x04type\x18\x01 \x01(\x0e22.com_bundleport_connect_proto_hotels.RateRulesTypeR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xe3\x02\n" +
	"\x04Room\x12&\n" +
	"\x0eoccupancyRefId\x18\x01 \x01(\x05R\x0eoccupancyRefId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12H\n" +
	"\troomPrice\x18\x04 \x01(\v2*.com_bundleport_connect_proto_hotels.PriceR\troomPrice\x12I\n" +
	"\bratePlan\x18\x05 \x01(\v2-.com_bundleport_connect_proto_hotels.RatePlanR\bratePlan\x12N\n" +
	"\n" +
	"promotions\x18\x06 \x03(\v2..com_bundleport_connect_proto_hotels.PromotionR\n" +
	"promotions\x12\x18\n" +
	"\x05units\x18\a \x01(\x05B\x02\x18\x01R\x05units\"2\n" +
	"\bRatePlan\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xc9\x01\n" +
	"\tPromotion\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12@\n" +
	"\reffectiveDate\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\reffectiveDate\x12:\n" +
	"\n" +
	"expireDate\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expireDate\"\xe5\x05\n" +
	"\fOptionSearch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\baccessId\x18\x03 \x01(\tR\baccessId\x12\x1c\n" +
	"\thotelCode\x18\x04 \x01(\tR\thotelCode\x12\x1c\n" +
	"\thotelName\x18\x05 \x01(\tR\thotelName\x12\x1c\n" +
	"\tboardCode\x18\x06 \x01(\tR\tboardCode\x12\x1c\n" +
	"\tboardName\x18\a \x01(\tR\tboardName\x12K\n" +
	"\trateRules\x18\b \x03(\v2-.com_bundleport_connect_proto_hotels.RateRuleR\trateRules\x12?\n" +
	"\x05rooms\x18\t \x03(\v2).com_bundleport_connect_proto_hotels.RoomR\x05rooms\x12@\n" +
	"\x05price\x18\n" +
	" \x01(\v2*.com_bundleport_connect_proto_hotels.PriceR\x05price\x12R\n" +
	"\vpaymentType\x18\v \x01(\x0e20.com_bundleport_connect_proto_hotels.PaymentTypeR\vpaymentType\x12N\n" +
	"\n" +
	"surcharges\x18\f \x03(\v2..com_bundleport_connect_proto_hotels.SurchargeR\n" +
	"surcharges\x12U\n" +
	"\fcancelPolicy\x18\r \x01(\v21.com_bundleport_connect_proto_hotels.CancelPolicyR\fcancelPolicy\x12H\n" +
	"\aremarks\x18\x0e \x03(\v2..com_bundleport_connect_proto_hotels.TypeValueR\aremarks\x12\x1c\n" +
	"\tfromCache\x18\x0f \x01(\bR\tfromCache\"\xc5\x01\n" +
	"\rSearchTracing\x12T\n" +
	"\x06status\x18\x01 \x01(\x0e2<.com_bundleport_connect_proto_hotels.SearchTracingStatusTypeR\x06status\x12^\n" +
	"\vaccessSpans\x18\x02 \x03(\v2<.com_bundleport_connect_proto_hotels.SearchTracingAccessSpanR\vaccessSpans\"\xc0\x02\n" +
	"\x17SearchTracingAccessSpan\x12\x16\n" +
	"\x06access\x18\x01 \x01(\tR\x06access\x12X\n" +
	"\x06status\x18\x02 \x01(\x0e2@.com_bundleport_connect_proto_hotels.SearchTracingSpanStatusTypeR\x06status\x12(\n" +
	"\x0fhotelsRequested\x18\x03 \x01(\x05R\x0fhotelsRequested\x12&\n" +
	"\x0ehotelsReturned\x18\x04 \x01(\x05R\x0ehotelsReturned\x12a\n" +
	"\ftransactions\x18\x06 \x03(\v2=.com_bundleport_connect_proto_hotels.SearchTracingTransactionR\ftransactions\"\xa0\x01\n" +
	"\x18SearchTracingTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12X\n" +
	"\x06status\x18\x02 \x01(\x0e2@.com_bundleport_connect_proto_hotels.SearchTracingSpanStatusTypeR\x06status\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x05R\bduration*\xdb\x03\n" +
	"\rRateRulesType\x12\x1a\n" +
	"\x16RATE_RULES_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cRATE_RULES_BALEARIC_RESIDENT\x10\x01\x12\x1e\n" +
	"\x1aRATE_RULES_CANARY_RESIDENT\x10\x02\x12\x15\n" +
	"\x11RATE_RULES_CUSTOM\x10\x03\x12\x1f\n" +
	"\x1bRATE_RULES_ESSENTIAL_WORKER\x10\x04\x12\x18\n" +
	"\x14RATE_RULES_HONEYMOON\x10\x05\x12\x1b\n" +
	"\x17RATE_RULES_LARGE_FAMILY\x10\x06\x12\x15\n" +
	"\x11RATE_RULES_MOBILE\x10\a\x12\x19\n" +
	"\x15RATE_RULES_NEGOTIATED\x10\b\x12\x18\n" +
	"\x14RATE_RULES_CORPORATE\x10\t\x12\x16\n" +
	"\x12RATE_RULES_OLDER55\x10\n" +
	"\x12\x16\n" +
	"\x12RATE_RULES_OLDER60\x10\v\x12\x16\n" +
	"\x12RATE_RULES_OLDER65\x10\f\x12\x16\n" +
	"\x12RATE_RULES_PACKAGE\x10\r\x12\x1d\n" +
	"\x19RATE_RULES_PUBLIC_SERVANT\x10\x0e\x12\x19\n" +
	"\x15RATE_RULES_UNEMPLOYED\x10\x0f\x12\x17\n" +
	"\x13RATE_RULES_WARRANTY\x10\x10*\xf6\x02\n" +
	"\x17SearchTracingStatusType\x12\x1c\n" +
	"\x18SEARCH_TRACING_STATUS_OK\x10\x00\x12'\n" +
	"#SEARCH_TRACING_STATUS_OK_NO_RESULTS\x10\x01\x12%\n" +
	"!SEARCH_TRACING_STATUS_OK_WARNINGS\x10\x02\x12\"\n" +
	"\x1eSEARCH_TRACING_STATUS_WARNINGS\x10\x03\x12 \n" +
	"\x1cSEARCH_TRACING_STATUS_ERRORS\x10\x04\x12!\n" +
	"\x1dSEARCH_TRACING_STATUS_UNKNOWN\x10\x05\x12!\n" +
	"\x1dSEARCH_TRACING_STATUS_PARTIAL\x10\x06\x126\n" +
	"2SEARCH_TRACING_STATUS_PARTIAL_WITH_WARNINGS_ERRORS\x10\a\x12)\n" +
	"%SEARCH_TRACING_STATUS_WARNINGS_ERRORS\x10\b*\x91\x02\n" +
	"\x1bSearchTracingSpanStatusType\x12!\n" +
	"\x1dSEARCH_TRACING_SPAN_STATUS_OK\x10\x00\x12,\n" +
	"(SEARCH_TRACING_SPAN_STATUS_OK_NO_RESULTS\x10\x01\x12*\n" +
	"&SEARCH_TRACING_SPAN_STATUS_OK_WARNINGS\x10\x02\x12'\n" +
	"#SEARCH_TRACING_SPAN_STATUS_WARNINGS\x10\x03\x12%\n" +
	"!SEARCH_TRACING_SPAN_STATUS_ERRORS\x10\x04\x12%\n" +
	"!SEARCH_TRACING_SPAN_STATUS_CACHED\x10\x0fB\x82\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x14SearchResponseProtosP\x01Z.github.com/bundleport/connect-hotels-go/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_response_search_response_hotels_proto_rawDescOnce sync.Once
	file_domain_response_search_response_hotels_proto_rawDescData []byte
)

func file_domain_response_search_response_hotels_proto_rawDescGZIP() []byte {
	file_domain_response_search_response_hotels_proto_rawDescOnce.Do(func() {
		file_domain_response_search_response_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_response_search_response_hotels_proto_rawDesc), len(file_domain_response_search_response_hotels_proto_rawDesc)))
	})
	return file_domain_response_search_response_hotels_proto_rawDescData
}

var file_domain_response_search_response_hotels_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_domain_response_search_response_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_domain_response_search_response_hotels_proto_goTypes = []any{
	(RateRulesType)(0),               // 0: com_bundleport_connect_proto_hotels.RateRulesType
	(SearchTracingStatusType)(0),     // 1: com_bundleport_connect_proto_hotels.SearchTracingStatusType
	(SearchTracingSpanStatusType)(0), // 2: com_bundleport_connect_proto_hotels.SearchTracingSpanStatusType
	(*SearchResponse)(nil),           // 3: com_bundleport_connect_proto_hotels.SearchResponse
	(*RateRule)(nil),                 // 4: com_bundleport_connect_proto_hotels.RateRule
	(*Room)(nil),                     // 5: com_bundleport_connect_proto_hotels.Room
	(*RatePlan)(nil),                 // 6: com_bundleport_connect_proto_hotels.RatePlan
	(*Promotion)(nil),                // 7: com_bundleport_connect_proto_hotels.Promotion
	(*OptionSearch)(nil),             // 8: com_bundleport_connect_proto_hotels.OptionSearch
	(*SearchTracing)(nil),            // 9: com_bundleport_connect_proto_hotels.SearchTracing
	(*SearchTracingAccessSpan)(nil),  // 10: com_bundleport_connect_proto_hotels.SearchTracingAccessSpan
	(*SearchTracingTransaction)(nil), // 11: com_bundleport_connect_proto_hotels.SearchTracingTransaction
	(*AuditData)(nil),                // 12: com_bundleport_connect_proto_hotels.AuditData
	(*Error)(nil),                    // 13: com_bundleport_connect_proto_hotels.Error
	(*Warning)(nil),                  // 14: com_bundleport_connect_proto_hotels.Warning
	(*TypeValue)(nil),                // 15: com_bundleport_connect_proto_hotels.TypeValue
	(*Price)(nil),                    // 16: com_bundleport_connect_proto_hotels.Price
	(*timestamppb.Timestamp)(nil),    // 17: google.protobuf.Timestamp
	(PaymentType)(0),                 // 18: com_bundleport_connect_proto_hotels.PaymentType
	(*Surcharge)(nil),                // 19: com_bundleport_connect_proto_hotels.Surcharge
	(*CancelPolicy)(nil),             // 20: com_bundleport_connect_proto_hotels.CancelPolicy
}
var file_domain_response_search_response_hotels_proto_depIdxs = []int32{
	12, // 0: com_bundleport_connect_proto_hotels.SearchResponse.auditData:type_name -> com_bundleport_connect_proto_hotels.AuditData
	13, // 1: com_bundleport_connect_proto_hotels.SearchResponse.errors:type_name -> com_bundleport_connect_proto_hotels.Error
	14, // 2: com_bundleport_connect_proto_hotels.SearchResponse.warnings:type_name -> com_bundleport_connect_proto_hotels.Warning
	15, // 3: com_bundleport_connect_proto_hotels.SearchResponse.debugData:type_name -> com_bundleport_connect_proto_hotels.TypeValue
	8,  // 4: com_bundleport_connect_proto_hotels.SearchResponse.options:type_name -> com_bundleport_connect_proto_hotels.OptionSearch
	9,  // 5: com_bundleport_connect_proto_hotels.SearchResponse.tracing:type_name -> com_bundleport_connect_proto_hotels.SearchTracing
	0,  // 6: com_bundleport_connect_proto_hotels.RateRule.type:type_name -> com_bundleport_connect_proto_hotels.RateRulesType
	16, // 7: com_bundleport_connect_proto_hotels.Room.roomPrice:type_name -> com_bundleport_connect_proto_hotels.Price
	6,  // 8: com_bundleport_connect_proto_hotels.Room.ratePlan:type_name -> com_bundleport_connect_proto_hotels.RatePlan
	7,  // 9: com_bundleport_connect_proto_hotels.Room.promotions:type_name -> com_bundleport_connect_proto_hotels.Promotion
	17, // 10: com_bundleport_connect_proto_hotels.Promotion.effectiveDate:type_name -> google.protobuf.Timestamp
	17, // 11: com_bundleport_connect_proto_hotels.Promotion.expireDate:type_name -> google.protobuf.Timestamp
	4,  // 12: com_bundleport_connect_proto_hotels.OptionSearch.rateRules:type_name -> com_bundleport_connect_proto_hotels.RateRule
	5,  // 13: com_bundleport_connect_proto_hotels.OptionSearch.rooms:type_name -> com_bundleport_connect_proto_hotels.Room
	16, // 14: com_bundleport_connect_proto_hotels.OptionSearch.price:type_name -> com_bundleport_connect_proto_hotels.Price
	18, // 15: com_bundleport_connect_proto_hotels.OptionSearch.paymentType:type_name -> com_bundleport_connect_proto_hotels.PaymentType
	19, // 16: com_bundleport_connect_proto_hotels.OptionSearch.surcharges:type_name -> com_bundleport_connect_proto_hotels.Surcharge
	20, // 17: com_bundleport_connect_proto_hotels.OptionSearch.cancelPolicy:type_name -> com_bundleport_connect_proto_hotels.CancelPolicy
	15, // 18: com_bundleport_connect_proto_hotels.OptionSearch.remarks:type_name -> com_bundleport_connect_proto_hotels.TypeValue
	1,  // 19: com_bundleport_connect_proto_hotels.SearchTracing.status:type_name -> com_bundleport_connect_proto_hotels.SearchTracingStatusType
	10, // 20: com_bundleport_connect_proto_hotels.SearchTracing.accessSpans:type_name -> com_bundleport_connect_proto_hotels.SearchTracingAccessSpan
	2,  // 21: com_bundleport_connect_proto_hotels.SearchTracingAccessSpan.status:type_name -> com_bundleport_connect_proto_hotels.SearchTracingSpanStatusType
	11, // 22: com_bundleport_connect_proto_hotels.SearchTracingAccessSpan.transactions:type_name -> com_bundleport_connect_proto_hotels.SearchTracingTransaction
	2,  // 23: com_bundleport_connect_proto_hotels.SearchTracingTransaction.status:type_name -> com_bundleport_connect_proto_hotels.SearchTracingSpanStatusType
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_domain_response_search_response_hotels_proto_init() }
func file_domain_response_search_response_hotels_proto_init() {
	if File_domain_response_search_response_hotels_proto != nil {
		return
	}
	file_domain_response_common_response_hotels_proto_init()
	file_domain_response_payment_response_hotels_proto_init()
	file_domain_response_booking_response_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_response_search_response_hotels_proto_rawDesc), len(file_domain_response_search_response_hotels_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_response_search_response_hotels_proto_goTypes,
		DependencyIndexes: file_domain_response_search_response_hotels_proto_depIdxs,
		EnumInfos:         file_domain_response_search_response_hotels_proto_enumTypes,
		MessageInfos:      file_domain_response_search_response_hotels_proto_msgTypes,
	}.Build()
	File_domain_response_search_response_hotels_proto = out.File
	file_domain_response_search_response_hotels_proto_goTypes = nil
	file_domain_response_search_response_hotels_proto_depIdxs = nil
}
