// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/request/search-request-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BusinessRulesType defines optimiser strategies applied during search.
type BusinessRulesType int32

const (
	// Prioritises the best price available across providers.
	BusinessRulesType_CHEAPER_AMOUNT BusinessRulesType = 0
	// Groups and prioritises results by room type similarity.
	BusinessRulesType_ROOM_TYPE BusinessRulesType = 1
)

// Enum value maps for BusinessRulesType.
var (
	BusinessRulesType_name = map[int32]string{
		0: "CHEAPER_AMOUNT",
		1: "ROOM_TYPE",
	}
	BusinessRulesType_value = map[string]int32{
		"CHEAPER_AMOUNT": 0,
		"ROOM_TYPE":      1,
	}
)

func (x BusinessRulesType) Enum() *BusinessRulesType {
	p := new(BusinessRulesType)
	*p = x
	return p
}

func (x BusinessRulesType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BusinessRulesType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_request_search_request_hotels_proto_enumTypes[0].Descriptor()
}

func (BusinessRulesType) Type() protoreflect.EnumType {
	return &file_domain_request_search_request_hotels_proto_enumTypes[0]
}

func (x BusinessRulesType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BusinessRulesType.Descriptor instead.
func (BusinessRulesType) EnumDescriptor() ([]byte, []int) {
	return file_domain_request_search_request_hotels_proto_rawDescGZIP(), []int{0}
}

// SearchRequest aggregates settings and criteria for hotel availability searches.
type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @required Stay details, guests, filters, and preferences.
	Criteria *CriteriaSearchInput `protobuf:"bytes,1,opt,name=criteria,proto3" json:"criteria,omitempty"`
	// @required Execution settings shared across aggregator requests.
	Settings      *SettingsInput `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_domain_request_search_request_hotels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_search_request_hotels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_domain_request_search_request_hotels_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetCriteria() *CriteriaSearchInput {
	if x != nil {
		return x.Criteria
	}
	return nil
}

func (x *SearchRequest) GetSettings() *SettingsInput {
	if x != nil {
		return x.Settings
	}
	return nil
}

// CriteriaSearchInput captures stay and guest preferences.
type CriteriaSearchInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @required Check-in date for the requested stay.
	CheckIn *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=checkIn,proto3" json:"checkIn,omitempty"`
	// @required Check-out date for the requested stay.
	CheckOut *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=checkOut,proto3" json:"checkOut,omitempty"`
	// Provider hotel identifiers to limit the search scope.
	Hotels []string `protobuf:"bytes,3,rep,name=hotels,proto3" json:"hotels,omitempty"`
	// Elements that must be excluded from the results.
	Exclusions []*Exclusion `protobuf:"bytes,4,rep,name=exclusions,proto3" json:"exclusions,omitempty"`
	// @required Occupancies requested; one entry per room configuration.
	Occupancies []*RoomInput `protobuf:"bytes,5,rep,name=occupancies,proto3" json:"occupancies,omitempty"`
	// Business rules to apply when curating results.
	BusinessRules *BusinessRulesInput `protobuf:"bytes,6,opt,name=businessRules,proto3" json:"businessRules,omitempty"`
	// ISO 639-1 language code for textual content.
	Language string `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	// ISO 4217 currency code used for prices.
	Currency string `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	// ISO 3166 alpha-2 nationality code for guests.
	Nationality string `protobuf:"bytes,9,opt,name=nationality,proto3" json:"nationality,omitempty"`
	// Provider-specific additional parameters forwarded as-is.
	AdditionalParams map[string]string `protobuf:"bytes,10,rep,name=additionalParams,proto3" json:"additionalParams,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CriteriaSearchInput) Reset() {
	*x = CriteriaSearchInput{}
	mi := &file_domain_request_search_request_hotels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriteriaSearchInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriteriaSearchInput) ProtoMessage() {}

func (x *CriteriaSearchInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_search_request_hotels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriteriaSearchInput.ProtoReflect.Descriptor instead.
func (*CriteriaSearchInput) Descriptor() ([]byte, []int) {
	return file_domain_request_search_request_hotels_proto_rawDescGZIP(), []int{1}
}

func (x *CriteriaSearchInput) GetCheckIn() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckIn
	}
	return nil
}

func (x *CriteriaSearchInput) GetCheckOut() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckOut
	}
	return nil
}

func (x *CriteriaSearchInput) GetHotels() []string {
	if x != nil {
		return x.Hotels
	}
	return nil
}

func (x *CriteriaSearchInput) GetExclusions() []*Exclusion {
	if x != nil {
		return x.Exclusions
	}
	return nil
}

func (x *CriteriaSearchInput) GetOccupancies() []*RoomInput {
	if x != nil {
		return x.Occupancies
	}
	return nil
}

func (x *CriteriaSearchInput) GetBusinessRules() *BusinessRulesInput {
	if x != nil {
		return x.BusinessRules
	}
	return nil
}

func (x *CriteriaSearchInput) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CriteriaSearchInput) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CriteriaSearchInput) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *CriteriaSearchInput) GetAdditionalParams() map[string]string {
	if x != nil {
		return x.AdditionalParams
	}
	return nil
}

// BusinessRulesInput describes optimisation constraints for search results.
type BusinessRulesInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optimisation strategy that the aggregator should apply.
	BusinessRulesType BusinessRulesType `protobuf:"varint,1,opt,name=businessRulesType,proto3,enum=com_bundleport_connect_proto_hotels.BusinessRulesType" json:"businessRulesType,omitempty"`
	// Maximum number of options per board and rate plan to return per provider when applicable.
	OptionsQuota  int32 `protobuf:"varint,2,opt,name=optionsQuota,proto3" json:"optionsQuota,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessRulesInput) Reset() {
	*x = BusinessRulesInput{}
	mi := &file_domain_request_search_request_hotels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessRulesInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessRulesInput) ProtoMessage() {}

func (x *BusinessRulesInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_search_request_hotels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessRulesInput.ProtoReflect.Descriptor instead.
func (*BusinessRulesInput) Descriptor() ([]byte, []int) {
	return file_domain_request_search_request_hotels_proto_rawDescGZIP(), []int{2}
}

func (x *BusinessRulesInput) GetBusinessRulesType() BusinessRulesType {
	if x != nil {
		return x.BusinessRulesType
	}
	return BusinessRulesType_CHEAPER_AMOUNT
}

func (x *BusinessRulesInput) GetOptionsQuota() int32 {
	if x != nil {
		return x.OptionsQuota
	}
	return 0
}

// RoomInput encapsulates the occupancy requested for one room.
type RoomInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @required Travellers assigned to the room.
	Paxes         []*PaxInput `protobuf:"bytes,1,rep,name=paxes,proto3" json:"paxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInput) Reset() {
	*x = RoomInput{}
	mi := &file_domain_request_search_request_hotels_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInput) ProtoMessage() {}

func (x *RoomInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_search_request_hotels_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInput.ProtoReflect.Descriptor instead.
func (*RoomInput) Descriptor() ([]byte, []int) {
	return file_domain_request_search_request_hotels_proto_rawDescGZIP(), []int{3}
}

func (x *RoomInput) GetPaxes() []*PaxInput {
	if x != nil {
		return x.Paxes
	}
	return nil
}

// PaxInput represents an individual traveller.
type PaxInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Traveller age at check-in time.
	Age           int32 `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaxInput) Reset() {
	*x = PaxInput{}
	mi := &file_domain_request_search_request_hotels_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaxInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaxInput) ProtoMessage() {}

func (x *PaxInput) ProtoReflect() protoreflect.Message {
	mi := &file_domain_request_search_request_hotels_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaxInput.ProtoReflect.Descriptor instead.
func (*PaxInput) Descriptor() ([]byte, []int) {
	return file_domain_request_search_request_hotels_proto_rawDescGZIP(), []int{4}
}

func (x *PaxInput) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_domain_request_search_request_hotels_proto protoreflect.FileDescriptor

const file_domain_request_search_request_hotels_proto_rawDesc = "" +
	"\n" +
	"*domain/request/search-request-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a\x1fgoogle/protobuf/timestamp.proto\x1a*domain/request/common-request-hotels.proto\"\xb5\x01\n" +
	"\rSearchRequest\x12T\n" +
	"\bcriteria\x18\x01 \x01(\v28.com_bundleport_connect_proto_hotels.CriteriaSearchInputR\bcriteria\x12N\n" +
	"\bsettings\x18\x02 \x01(\v22.com_bundleport_connect_proto_hotels.SettingsInputR\bsettings\"\xb7\x05\n" +
	"\x13CriteriaSearchInput\x124\n" +
	"\acheckIn\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\acheckIn\x126\n" +
	"\bcheckOut\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bcheckOut\x12\x16\n" +
	"\x06hotels\x18\x03 \x03(\tR\x06hotels\x12N\n" +
	"\n" +
	"exclusions\x18\x04 \x03(\v2..com_bundleport_connect_proto_hotels.ExclusionR\n" +
	"exclusions\x12P\n" +
	"\voccupancies\x18\x05 \x03(\v2..com_bundleport_connect_proto_hotels.RoomInputR\voccupancies\x12]\n" +
	"\rbusinessRules\x18\x06 \x01(\v27.com_bundleport_connect_proto_hotels.BusinessRulesInputR\rbusinessRules\x12\x1a\n" +
	"\blanguage\x18\a \x01(\tR\blanguage\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12 \n" +
	"\vnationality\x18\t \x01(\tR\vnationality\x12z\n" +
	"\x10additionalParams\x18\n" +
	" \x03(\v2N.com_bundleport_connect_proto_hotels.CriteriaSearchInput.AdditionalParamsEntryR\x10additionalParams\x1aC\n" +
	"\x15AdditionalParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x01\n" +
	"\x12BusinessRulesInput\x12d\n" +
	"\x11businessRulesType\x18\x01 \x01(\x0e26.com_bundleport_connect_proto_hotels.BusinessRulesTypeR\x11businessRulesType\x12\"\n" +
	"\foptionsQuota\x18\x02 \x01(\x05R\foptionsQuota\"P\n" +
	"\tRoomInput\x12C\n" +
	"\x05paxes\x18\x01 \x03(\v2-.com_bundleport_connect_proto_hotels.PaxInputR\x05paxes\"\x1c\n" +
	"\bPaxInput\x12\x10\n" +
	"\x03age\x18\x01 \x01(\x05R\x03age*6\n" +
	"\x11BusinessRulesType\x12\x12\n" +
	"\x0eCHEAPER_AMOUNT\x10\x00\x12\r\n" +
	"\tROOM_TYPE\x10\x01B\x81\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x13SearchRequestProtosP\x01Z.github.com/bundleport/connect-go-schema/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var (
	file_domain_request_search_request_hotels_proto_rawDescOnce sync.Once
	file_domain_request_search_request_hotels_proto_rawDescData []byte
)

func file_domain_request_search_request_hotels_proto_rawDescGZIP() []byte {
	file_domain_request_search_request_hotels_proto_rawDescOnce.Do(func() {
		file_domain_request_search_request_hotels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_request_search_request_hotels_proto_rawDesc), len(file_domain_request_search_request_hotels_proto_rawDesc)))
	})
	return file_domain_request_search_request_hotels_proto_rawDescData
}

var file_domain_request_search_request_hotels_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_domain_request_search_request_hotels_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_domain_request_search_request_hotels_proto_goTypes = []any{
	(BusinessRulesType)(0),        // 0: com_bundleport_connect_proto_hotels.BusinessRulesType
	(*SearchRequest)(nil),         // 1: com_bundleport_connect_proto_hotels.SearchRequest
	(*CriteriaSearchInput)(nil),   // 2: com_bundleport_connect_proto_hotels.CriteriaSearchInput
	(*BusinessRulesInput)(nil),    // 3: com_bundleport_connect_proto_hotels.BusinessRulesInput
	(*RoomInput)(nil),             // 4: com_bundleport_connect_proto_hotels.RoomInput
	(*PaxInput)(nil),              // 5: com_bundleport_connect_proto_hotels.PaxInput
	nil,                           // 6: com_bundleport_connect_proto_hotels.CriteriaSearchInput.AdditionalParamsEntry
	(*SettingsInput)(nil),         // 7: com_bundleport_connect_proto_hotels.SettingsInput
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*Exclusion)(nil),             // 9: com_bundleport_connect_proto_hotels.Exclusion
}
var file_domain_request_search_request_hotels_proto_depIdxs = []int32{
	2,  // 0: com_bundleport_connect_proto_hotels.SearchRequest.criteria:type_name -> com_bundleport_connect_proto_hotels.CriteriaSearchInput
	7,  // 1: com_bundleport_connect_proto_hotels.SearchRequest.settings:type_name -> com_bundleport_connect_proto_hotels.SettingsInput
	8,  // 2: com_bundleport_connect_proto_hotels.CriteriaSearchInput.checkIn:type_name -> google.protobuf.Timestamp
	8,  // 3: com_bundleport_connect_proto_hotels.CriteriaSearchInput.checkOut:type_name -> google.protobuf.Timestamp
	9,  // 4: com_bundleport_connect_proto_hotels.CriteriaSearchInput.exclusions:type_name -> com_bundleport_connect_proto_hotels.Exclusion
	4,  // 5: com_bundleport_connect_proto_hotels.CriteriaSearchInput.occupancies:type_name -> com_bundleport_connect_proto_hotels.RoomInput
	3,  // 6: com_bundleport_connect_proto_hotels.CriteriaSearchInput.businessRules:type_name -> com_bundleport_connect_proto_hotels.BusinessRulesInput
	6,  // 7: com_bundleport_connect_proto_hotels.CriteriaSearchInput.additionalParams:type_name -> com_bundleport_connect_proto_hotels.CriteriaSearchInput.AdditionalParamsEntry
	0,  // 8: com_bundleport_connect_proto_hotels.BusinessRulesInput.businessRulesType:type_name -> com_bundleport_connect_proto_hotels.BusinessRulesType
	5,  // 9: com_bundleport_connect_proto_hotels.RoomInput.paxes:type_name -> com_bundleport_connect_proto_hotels.PaxInput
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_domain_request_search_request_hotels_proto_init() }
func file_domain_request_search_request_hotels_proto_init() {
	if File_domain_request_search_request_hotels_proto != nil {
		return
	}
	file_domain_request_common_request_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_request_search_request_hotels_proto_rawDesc), len(file_domain_request_search_request_hotels_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_request_search_request_hotels_proto_goTypes,
		DependencyIndexes: file_domain_request_search_request_hotels_proto_depIdxs,
		EnumInfos:         file_domain_request_search_request_hotels_proto_enumTypes,
		MessageInfos:      file_domain_request_search_request_hotels_proto_msgTypes,
	}.Build()
	File_domain_request_search_request_hotels_proto = out.File
	file_domain_request_search_request_hotels_proto_goTypes = nil
	file_domain_request_search_request_hotels_proto_depIdxs = nil
}
