// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: services/services-hotels.proto

package hotels

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Integration_Search_FullMethodName             = "/com_bundleport_connect_proto_hotels.Integration/Search"
	Integration_Quote_FullMethodName              = "/com_bundleport_connect_proto_hotels.Integration/Quote"
	Integration_Book_FullMethodName               = "/com_bundleport_connect_proto_hotels.Integration/Book"
	Integration_Cancel_FullMethodName             = "/com_bundleport_connect_proto_hotels.Integration/Cancel"
	Integration_BookingDetail_FullMethodName      = "/com_bundleport_connect_proto_hotels.Integration/BookingDetail"
	Integration_BookingList_FullMethodName        = "/com_bundleport_connect_proto_hotels.Integration/BookingList"
	Integration_GetBoards_FullMethodName          = "/com_bundleport_connect_proto_hotels.Integration/GetBoards"
	Integration_GetCategories_FullMethodName      = "/com_bundleport_connect_proto_hotels.Integration/GetCategories"
	Integration_GetHotels_FullMethodName          = "/com_bundleport_connect_proto_hotels.Integration/GetHotels"
	Integration_GetRooms_FullMethodName           = "/com_bundleport_connect_proto_hotels.Integration/GetRooms"
	Integration_GetDestinations_FullMethodName    = "/com_bundleport_connect_proto_hotels.Integration/GetDestinations"
	Integration_SearchDestinations_FullMethodName = "/com_bundleport_connect_proto_hotels.Integration/SearchDestinations"
	Integration_GetMetadata_FullMethodName        = "/com_bundleport_connect_proto_hotels.Integration/GetMetadata"
)

// IntegrationClient is the client API for Integration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// @info: Bundleport Aggregator surfaces booking flow and catalog APIs across providers via ConnectRPC.
// Integration exposes hotel shopping and booking operations through the aggregator in a single unified API.
// Refer to the general Bundleport Connect docs for more information.
// @title: Bundleport REST API
type IntegrationClient interface {
	// Retrieves availability options for a stay across configured providers.
	// @tag: Booking Flow
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Retrieves a price confirmation for a previously selected option.
	// @tag: Booking Flow
	Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error)
	// Confirms a booking for the given option and traveller details.
	// @tag: Booking Flow
	Book(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*BookResponse, error)
	// Cancels an existing booking and returns updated booking status.
	// @tag: Booking Flow
	Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
	// Retrieves detailed information for a single booking record.
	// @tag: Booking Flow
	BookingDetail(ctx context.Context, in *BookingDetailRequest, opts ...grpc.CallOption) (*BookingDetailResponse, error)
	// Lists bookings filtered by time range, status or references.
	// @tag: Booking Flow
	BookingList(ctx context.Context, in *BookingListRequest, opts ...grpc.CallOption) (*BookingListResponse, error)
	// Returns the boards available for a given hotel or destination.
	// @tag: Content
	GetBoards(ctx context.Context, in *GetBoardsRequest, opts ...grpc.CallOption) (*GetBoardsResponse, error)
	// Returns the categories configured for available hotels.
	// @tag: Content
	GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error)
	// Lists hotels accessible within the configured provider accounts.
	// @tag: Content
	GetHotels(ctx context.Context, in *GetHotelsRequest, opts ...grpc.CallOption) (*GetHotelsResponse, error)
	// Lists rooms mapped for a given hotel.
	// @tag: Content
	GetRooms(ctx context.Context, in *GetRoomsRequest, opts ...grpc.CallOption) (*GetRoomsResponse, error)
	// Returns destinations configured for the aggregator.
	// @tag: Content
	GetDestinations(ctx context.Context, in *GetDestinationsRequest, opts ...grpc.CallOption) (*GetDestinationsResponse, error)
	// Searches destinations matching the provided criteria.
	// @tag: Content
	SearchDestinations(ctx context.Context, in *SearchDestinationsRequest, opts ...grpc.CallOption) (*SearchDestinationsResponse, error)
	// Retrieves static metadata from providers and internal catalogues.
	// @tag: Content
	GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error)
}

type integrationClient struct {
	cc grpc.ClientConnInterface
}

func NewIntegrationClient(cc grpc.ClientConnInterface) IntegrationClient {
	return &integrationClient{cc}
}

func (c *integrationClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, Integration_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationClient) Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuoteResponse)
	err := c.cc.Invoke(ctx, Integration_Quote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationClient) Book(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*BookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookResponse)
	err := c.cc.Invoke(ctx, Integration_Book_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationClient) Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, Integration_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationClient) BookingDetail(ctx context.Context, in *BookingDetailRequest, opts ...grpc.CallOption) (*BookingDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingDetailResponse)
	err := c.cc.Invoke(ctx, Integration_BookingDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationClient) BookingList(ctx context.Context, in *BookingListRequest, opts ...grpc.CallOption) (*BookingListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingListResponse)
	err := c.cc.Invoke(ctx, Integration_BookingList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationClient) GetBoards(ctx context.Context, in *GetBoardsRequest, opts ...grpc.CallOption) (*GetBoardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBoardsResponse)
	err := c.cc.Invoke(ctx, Integration_GetBoards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationClient) GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoriesResponse)
	err := c.cc.Invoke(ctx, Integration_GetCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationClient) GetHotels(ctx context.Context, in *GetHotelsRequest, opts ...grpc.CallOption) (*GetHotelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHotelsResponse)
	err := c.cc.Invoke(ctx, Integration_GetHotels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationClient) GetRooms(ctx context.Context, in *GetRoomsRequest, opts ...grpc.CallOption) (*GetRoomsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoomsResponse)
	err := c.cc.Invoke(ctx, Integration_GetRooms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationClient) GetDestinations(ctx context.Context, in *GetDestinationsRequest, opts ...grpc.CallOption) (*GetDestinationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDestinationsResponse)
	err := c.cc.Invoke(ctx, Integration_GetDestinations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationClient) SearchDestinations(ctx context.Context, in *SearchDestinationsRequest, opts ...grpc.CallOption) (*SearchDestinationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchDestinationsResponse)
	err := c.cc.Invoke(ctx, Integration_SearchDestinations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationClient) GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetadataResponse)
	err := c.cc.Invoke(ctx, Integration_GetMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntegrationServer is the server API for Integration service.
// All implementations must embed UnimplementedIntegrationServer
// for forward compatibility.
//
// @info: Bundleport Aggregator surfaces booking flow and catalog APIs across providers via ConnectRPC.
// Integration exposes hotel shopping and booking operations through the aggregator in a single unified API.
// Refer to the general Bundleport Connect docs for more information.
// @title: Bundleport REST API
type IntegrationServer interface {
	// Retrieves availability options for a stay across configured providers.
	// @tag: Booking Flow
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// Retrieves a price confirmation for a previously selected option.
	// @tag: Booking Flow
	Quote(context.Context, *QuoteRequest) (*QuoteResponse, error)
	// Confirms a booking for the given option and traveller details.
	// @tag: Booking Flow
	Book(context.Context, *BookRequest) (*BookResponse, error)
	// Cancels an existing booking and returns updated booking status.
	// @tag: Booking Flow
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
	// Retrieves detailed information for a single booking record.
	// @tag: Booking Flow
	BookingDetail(context.Context, *BookingDetailRequest) (*BookingDetailResponse, error)
	// Lists bookings filtered by time range, status or references.
	// @tag: Booking Flow
	BookingList(context.Context, *BookingListRequest) (*BookingListResponse, error)
	// Returns the boards available for a given hotel or destination.
	// @tag: Content
	GetBoards(context.Context, *GetBoardsRequest) (*GetBoardsResponse, error)
	// Returns the categories configured for available hotels.
	// @tag: Content
	GetCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesResponse, error)
	// Lists hotels accessible within the configured provider accounts.
	// @tag: Content
	GetHotels(context.Context, *GetHotelsRequest) (*GetHotelsResponse, error)
	// Lists rooms mapped for a given hotel.
	// @tag: Content
	GetRooms(context.Context, *GetRoomsRequest) (*GetRoomsResponse, error)
	// Returns destinations configured for the aggregator.
	// @tag: Content
	GetDestinations(context.Context, *GetDestinationsRequest) (*GetDestinationsResponse, error)
	// Searches destinations matching the provided criteria.
	// @tag: Content
	SearchDestinations(context.Context, *SearchDestinationsRequest) (*SearchDestinationsResponse, error)
	// Retrieves static metadata from providers and internal catalogues.
	// @tag: Content
	GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error)
	mustEmbedUnimplementedIntegrationServer()
}

// UnimplementedIntegrationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntegrationServer struct{}

func (UnimplementedIntegrationServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedIntegrationServer) Quote(context.Context, *QuoteRequest) (*QuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Quote not implemented")
}
func (UnimplementedIntegrationServer) Book(context.Context, *BookRequest) (*BookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Book not implemented")
}
func (UnimplementedIntegrationServer) Cancel(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedIntegrationServer) BookingDetail(context.Context, *BookingDetailRequest) (*BookingDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookingDetail not implemented")
}
func (UnimplementedIntegrationServer) BookingList(context.Context, *BookingListRequest) (*BookingListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookingList not implemented")
}
func (UnimplementedIntegrationServer) GetBoards(context.Context, *GetBoardsRequest) (*GetBoardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBoards not implemented")
}
func (UnimplementedIntegrationServer) GetCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategories not implemented")
}
func (UnimplementedIntegrationServer) GetHotels(context.Context, *GetHotelsRequest) (*GetHotelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHotels not implemented")
}
func (UnimplementedIntegrationServer) GetRooms(context.Context, *GetRoomsRequest) (*GetRoomsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRooms not implemented")
}
func (UnimplementedIntegrationServer) GetDestinations(context.Context, *GetDestinationsRequest) (*GetDestinationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDestinations not implemented")
}
func (UnimplementedIntegrationServer) SearchDestinations(context.Context, *SearchDestinationsRequest) (*SearchDestinationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchDestinations not implemented")
}
func (UnimplementedIntegrationServer) GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedIntegrationServer) mustEmbedUnimplementedIntegrationServer() {}
func (UnimplementedIntegrationServer) testEmbeddedByValue()                     {}

// UnsafeIntegrationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntegrationServer will
// result in compilation errors.
type UnsafeIntegrationServer interface {
	mustEmbedUnimplementedIntegrationServer()
}

func RegisterIntegrationServer(s grpc.ServiceRegistrar, srv IntegrationServer) {
	// If the following call pancis, it indicates UnimplementedIntegrationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Integration_ServiceDesc, srv)
}

func _Integration_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Integration_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Integration_Quote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServer).Quote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Integration_Quote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServer).Quote(ctx, req.(*QuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Integration_Book_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServer).Book(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Integration_Book_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServer).Book(ctx, req.(*BookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Integration_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Integration_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServer).Cancel(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Integration_BookingDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServer).BookingDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Integration_BookingDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServer).BookingDetail(ctx, req.(*BookingDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Integration_BookingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServer).BookingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Integration_BookingList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServer).BookingList(ctx, req.(*BookingListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Integration_GetBoards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBoardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServer).GetBoards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Integration_GetBoards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServer).GetBoards(ctx, req.(*GetBoardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Integration_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Integration_GetCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServer).GetCategories(ctx, req.(*GetCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Integration_GetHotels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHotelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServer).GetHotels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Integration_GetHotels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServer).GetHotels(ctx, req.(*GetHotelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Integration_GetRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServer).GetRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Integration_GetRooms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServer).GetRooms(ctx, req.(*GetRoomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Integration_GetDestinations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDestinationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServer).GetDestinations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Integration_GetDestinations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServer).GetDestinations(ctx, req.(*GetDestinationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Integration_SearchDestinations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchDestinationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServer).SearchDestinations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Integration_SearchDestinations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServer).SearchDestinations(ctx, req.(*SearchDestinationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Integration_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Integration_GetMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServer).GetMetadata(ctx, req.(*GetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Integration_ServiceDesc is the grpc.ServiceDesc for Integration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Integration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com_bundleport_connect_proto_hotels.Integration",
	HandlerType: (*IntegrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _Integration_Search_Handler,
		},
		{
			MethodName: "Quote",
			Handler:    _Integration_Quote_Handler,
		},
		{
			MethodName: "Book",
			Handler:    _Integration_Book_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _Integration_Cancel_Handler,
		},
		{
			MethodName: "BookingDetail",
			Handler:    _Integration_BookingDetail_Handler,
		},
		{
			MethodName: "BookingList",
			Handler:    _Integration_BookingList_Handler,
		},
		{
			MethodName: "GetBoards",
			Handler:    _Integration_GetBoards_Handler,
		},
		{
			MethodName: "GetCategories",
			Handler:    _Integration_GetCategories_Handler,
		},
		{
			MethodName: "GetHotels",
			Handler:    _Integration_GetHotels_Handler,
		},
		{
			MethodName: "GetRooms",
			Handler:    _Integration_GetRooms_Handler,
		},
		{
			MethodName: "GetDestinations",
			Handler:    _Integration_GetDestinations_Handler,
		},
		{
			MethodName: "SearchDestinations",
			Handler:    _Integration_SearchDestinations_Handler,
		},
		{
			MethodName: "GetMetadata",
			Handler:    _Integration_GetMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/services-hotels.proto",
}
