// Code generated by MockGen. DO NOT EDIT.
// Source: ./hotels/services-hotels_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=./hotels/services-hotels_grpc.pb.go -package=hotels -destination=./hotels/services-hotels_grpc_mock.pb.go
//

// Package hotels is a generated GoMock package.
package hotels

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockIntegrationClient is a mock of IntegrationClient interface.
type MockIntegrationClient struct {
	ctrl     *gomock.Controller
	recorder *MockIntegrationClientMockRecorder
	isgomock struct{}
}

// MockIntegrationClientMockRecorder is the mock recorder for MockIntegrationClient.
type MockIntegrationClientMockRecorder struct {
	mock *MockIntegrationClient
}

// NewMockIntegrationClient creates a new mock instance.
func NewMockIntegrationClient(ctrl *gomock.Controller) *MockIntegrationClient {
	mock := &MockIntegrationClient{ctrl: ctrl}
	mock.recorder = &MockIntegrationClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIntegrationClient) EXPECT() *MockIntegrationClientMockRecorder {
	return m.recorder
}

// Book mocks base method.
func (m *MockIntegrationClient) Book(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*BookResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Book", varargs...)
	ret0, _ := ret[0].(*BookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Book indicates an expected call of Book.
func (mr *MockIntegrationClientMockRecorder) Book(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Book", reflect.TypeOf((*MockIntegrationClient)(nil).Book), varargs...)
}

// BookingDetail mocks base method.
func (m *MockIntegrationClient) BookingDetail(ctx context.Context, in *BookingDetailRequest, opts ...grpc.CallOption) (*BookingDetailResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BookingDetail", varargs...)
	ret0, _ := ret[0].(*BookingDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BookingDetail indicates an expected call of BookingDetail.
func (mr *MockIntegrationClientMockRecorder) BookingDetail(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BookingDetail", reflect.TypeOf((*MockIntegrationClient)(nil).BookingDetail), varargs...)
}

// BookingList mocks base method.
func (m *MockIntegrationClient) BookingList(ctx context.Context, in *BookingListRequest, opts ...grpc.CallOption) (*BookingListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BookingList", varargs...)
	ret0, _ := ret[0].(*BookingListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BookingList indicates an expected call of BookingList.
func (mr *MockIntegrationClientMockRecorder) BookingList(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BookingList", reflect.TypeOf((*MockIntegrationClient)(nil).BookingList), varargs...)
}

// Cancel mocks base method.
func (m *MockIntegrationClient) Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Cancel", varargs...)
	ret0, _ := ret[0].(*CancelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cancel indicates an expected call of Cancel.
func (mr *MockIntegrationClientMockRecorder) Cancel(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockIntegrationClient)(nil).Cancel), varargs...)
}

// GetBoards mocks base method.
func (m *MockIntegrationClient) GetBoards(ctx context.Context, in *GetBoardsRequest, opts ...grpc.CallOption) (*GetBoardsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBoards", varargs...)
	ret0, _ := ret[0].(*GetBoardsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBoards indicates an expected call of GetBoards.
func (mr *MockIntegrationClientMockRecorder) GetBoards(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoards", reflect.TypeOf((*MockIntegrationClient)(nil).GetBoards), varargs...)
}

// GetCategories mocks base method.
func (m *MockIntegrationClient) GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCategories", varargs...)
	ret0, _ := ret[0].(*GetCategoriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategories indicates an expected call of GetCategories.
func (mr *MockIntegrationClientMockRecorder) GetCategories(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategories", reflect.TypeOf((*MockIntegrationClient)(nil).GetCategories), varargs...)
}

// GetDestinations mocks base method.
func (m *MockIntegrationClient) GetDestinations(ctx context.Context, in *GetDestinationsRequest, opts ...grpc.CallOption) (*GetDestinationsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDestinations", varargs...)
	ret0, _ := ret[0].(*GetDestinationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDestinations indicates an expected call of GetDestinations.
func (mr *MockIntegrationClientMockRecorder) GetDestinations(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDestinations", reflect.TypeOf((*MockIntegrationClient)(nil).GetDestinations), varargs...)
}

// GetHotels mocks base method.
func (m *MockIntegrationClient) GetHotels(ctx context.Context, in *GetHotelsRequest, opts ...grpc.CallOption) (*GetHotelsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetHotels", varargs...)
	ret0, _ := ret[0].(*GetHotelsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHotels indicates an expected call of GetHotels.
func (mr *MockIntegrationClientMockRecorder) GetHotels(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHotels", reflect.TypeOf((*MockIntegrationClient)(nil).GetHotels), varargs...)
}

// GetMetadata mocks base method.
func (m *MockIntegrationClient) GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMetadata", varargs...)
	ret0, _ := ret[0].(*GetMetadataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockIntegrationClientMockRecorder) GetMetadata(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockIntegrationClient)(nil).GetMetadata), varargs...)
}

// GetRooms mocks base method.
func (m *MockIntegrationClient) GetRooms(ctx context.Context, in *GetRoomsRequest, opts ...grpc.CallOption) (*GetRoomsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRooms", varargs...)
	ret0, _ := ret[0].(*GetRoomsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRooms indicates an expected call of GetRooms.
func (mr *MockIntegrationClientMockRecorder) GetRooms(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRooms", reflect.TypeOf((*MockIntegrationClient)(nil).GetRooms), varargs...)
}

// Quote mocks base method.
func (m *MockIntegrationClient) Quote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Quote", varargs...)
	ret0, _ := ret[0].(*QuoteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Quote indicates an expected call of Quote.
func (mr *MockIntegrationClientMockRecorder) Quote(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Quote", reflect.TypeOf((*MockIntegrationClient)(nil).Quote), varargs...)
}

// Search mocks base method.
func (m *MockIntegrationClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Search", varargs...)
	ret0, _ := ret[0].(*SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockIntegrationClientMockRecorder) Search(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockIntegrationClient)(nil).Search), varargs...)
}

// SearchDestinations mocks base method.
func (m *MockIntegrationClient) SearchDestinations(ctx context.Context, in *SearchDestinationsRequest, opts ...grpc.CallOption) (*SearchDestinationsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchDestinations", varargs...)
	ret0, _ := ret[0].(*SearchDestinationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchDestinations indicates an expected call of SearchDestinations.
func (mr *MockIntegrationClientMockRecorder) SearchDestinations(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchDestinations", reflect.TypeOf((*MockIntegrationClient)(nil).SearchDestinations), varargs...)
}

// MockIntegrationServer is a mock of IntegrationServer interface.
type MockIntegrationServer struct {
	ctrl     *gomock.Controller
	recorder *MockIntegrationServerMockRecorder
	isgomock struct{}
}

// MockIntegrationServerMockRecorder is the mock recorder for MockIntegrationServer.
type MockIntegrationServerMockRecorder struct {
	mock *MockIntegrationServer
}

// NewMockIntegrationServer creates a new mock instance.
func NewMockIntegrationServer(ctrl *gomock.Controller) *MockIntegrationServer {
	mock := &MockIntegrationServer{ctrl: ctrl}
	mock.recorder = &MockIntegrationServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIntegrationServer) EXPECT() *MockIntegrationServerMockRecorder {
	return m.recorder
}

// Book mocks base method.
func (m *MockIntegrationServer) Book(arg0 context.Context, arg1 *BookRequest) (*BookResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Book", arg0, arg1)
	ret0, _ := ret[0].(*BookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Book indicates an expected call of Book.
func (mr *MockIntegrationServerMockRecorder) Book(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Book", reflect.TypeOf((*MockIntegrationServer)(nil).Book), arg0, arg1)
}

// BookingDetail mocks base method.
func (m *MockIntegrationServer) BookingDetail(arg0 context.Context, arg1 *BookingDetailRequest) (*BookingDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BookingDetail", arg0, arg1)
	ret0, _ := ret[0].(*BookingDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BookingDetail indicates an expected call of BookingDetail.
func (mr *MockIntegrationServerMockRecorder) BookingDetail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BookingDetail", reflect.TypeOf((*MockIntegrationServer)(nil).BookingDetail), arg0, arg1)
}

// BookingList mocks base method.
func (m *MockIntegrationServer) BookingList(arg0 context.Context, arg1 *BookingListRequest) (*BookingListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BookingList", arg0, arg1)
	ret0, _ := ret[0].(*BookingListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BookingList indicates an expected call of BookingList.
func (mr *MockIntegrationServerMockRecorder) BookingList(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BookingList", reflect.TypeOf((*MockIntegrationServer)(nil).BookingList), arg0, arg1)
}

// Cancel mocks base method.
func (m *MockIntegrationServer) Cancel(arg0 context.Context, arg1 *CancelRequest) (*CancelResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", arg0, arg1)
	ret0, _ := ret[0].(*CancelResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cancel indicates an expected call of Cancel.
func (mr *MockIntegrationServerMockRecorder) Cancel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockIntegrationServer)(nil).Cancel), arg0, arg1)
}

// GetBoards mocks base method.
func (m *MockIntegrationServer) GetBoards(arg0 context.Context, arg1 *GetBoardsRequest) (*GetBoardsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBoards", arg0, arg1)
	ret0, _ := ret[0].(*GetBoardsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBoards indicates an expected call of GetBoards.
func (mr *MockIntegrationServerMockRecorder) GetBoards(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBoards", reflect.TypeOf((*MockIntegrationServer)(nil).GetBoards), arg0, arg1)
}

// GetCategories mocks base method.
func (m *MockIntegrationServer) GetCategories(arg0 context.Context, arg1 *GetCategoriesRequest) (*GetCategoriesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategories", arg0, arg1)
	ret0, _ := ret[0].(*GetCategoriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategories indicates an expected call of GetCategories.
func (mr *MockIntegrationServerMockRecorder) GetCategories(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategories", reflect.TypeOf((*MockIntegrationServer)(nil).GetCategories), arg0, arg1)
}

// GetDestinations mocks base method.
func (m *MockIntegrationServer) GetDestinations(arg0 context.Context, arg1 *GetDestinationsRequest) (*GetDestinationsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDestinations", arg0, arg1)
	ret0, _ := ret[0].(*GetDestinationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDestinations indicates an expected call of GetDestinations.
func (mr *MockIntegrationServerMockRecorder) GetDestinations(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDestinations", reflect.TypeOf((*MockIntegrationServer)(nil).GetDestinations), arg0, arg1)
}

// GetHotels mocks base method.
func (m *MockIntegrationServer) GetHotels(arg0 context.Context, arg1 *GetHotelsRequest) (*GetHotelsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHotels", arg0, arg1)
	ret0, _ := ret[0].(*GetHotelsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHotels indicates an expected call of GetHotels.
func (mr *MockIntegrationServerMockRecorder) GetHotels(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHotels", reflect.TypeOf((*MockIntegrationServer)(nil).GetHotels), arg0, arg1)
}

// GetMetadata mocks base method.
func (m *MockIntegrationServer) GetMetadata(arg0 context.Context, arg1 *GetMetadataRequest) (*GetMetadataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", arg0, arg1)
	ret0, _ := ret[0].(*GetMetadataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockIntegrationServerMockRecorder) GetMetadata(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockIntegrationServer)(nil).GetMetadata), arg0, arg1)
}

// GetRooms mocks base method.
func (m *MockIntegrationServer) GetRooms(arg0 context.Context, arg1 *GetRoomsRequest) (*GetRoomsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRooms", arg0, arg1)
	ret0, _ := ret[0].(*GetRoomsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRooms indicates an expected call of GetRooms.
func (mr *MockIntegrationServerMockRecorder) GetRooms(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRooms", reflect.TypeOf((*MockIntegrationServer)(nil).GetRooms), arg0, arg1)
}

// Quote mocks base method.
func (m *MockIntegrationServer) Quote(arg0 context.Context, arg1 *QuoteRequest) (*QuoteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Quote", arg0, arg1)
	ret0, _ := ret[0].(*QuoteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Quote indicates an expected call of Quote.
func (mr *MockIntegrationServerMockRecorder) Quote(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Quote", reflect.TypeOf((*MockIntegrationServer)(nil).Quote), arg0, arg1)
}

// Search mocks base method.
func (m *MockIntegrationServer) Search(arg0 context.Context, arg1 *SearchRequest) (*SearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", arg0, arg1)
	ret0, _ := ret[0].(*SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockIntegrationServerMockRecorder) Search(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockIntegrationServer)(nil).Search), arg0, arg1)
}

// SearchDestinations mocks base method.
func (m *MockIntegrationServer) SearchDestinations(arg0 context.Context, arg1 *SearchDestinationsRequest) (*SearchDestinationsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchDestinations", arg0, arg1)
	ret0, _ := ret[0].(*SearchDestinationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchDestinations indicates an expected call of SearchDestinations.
func (mr *MockIntegrationServerMockRecorder) SearchDestinations(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchDestinations", reflect.TypeOf((*MockIntegrationServer)(nil).SearchDestinations), arg0, arg1)
}

// mustEmbedUnimplementedIntegrationServer mocks base method.
func (m *MockIntegrationServer) mustEmbedUnimplementedIntegrationServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedIntegrationServer")
}

// mustEmbedUnimplementedIntegrationServer indicates an expected call of mustEmbedUnimplementedIntegrationServer.
func (mr *MockIntegrationServerMockRecorder) mustEmbedUnimplementedIntegrationServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedIntegrationServer", reflect.TypeOf((*MockIntegrationServer)(nil).mustEmbedUnimplementedIntegrationServer))
}

// MockUnsafeIntegrationServer is a mock of UnsafeIntegrationServer interface.
type MockUnsafeIntegrationServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeIntegrationServerMockRecorder
	isgomock struct{}
}

// MockUnsafeIntegrationServerMockRecorder is the mock recorder for MockUnsafeIntegrationServer.
type MockUnsafeIntegrationServerMockRecorder struct {
	mock *MockUnsafeIntegrationServer
}

// NewMockUnsafeIntegrationServer creates a new mock instance.
func NewMockUnsafeIntegrationServer(ctrl *gomock.Controller) *MockUnsafeIntegrationServer {
	mock := &MockUnsafeIntegrationServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeIntegrationServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeIntegrationServer) EXPECT() *MockUnsafeIntegrationServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedIntegrationServer mocks base method.
func (m *MockUnsafeIntegrationServer) mustEmbedUnimplementedIntegrationServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedIntegrationServer")
}

// mustEmbedUnimplementedIntegrationServer indicates an expected call of mustEmbedUnimplementedIntegrationServer.
func (mr *MockUnsafeIntegrationServerMockRecorder) mustEmbedUnimplementedIntegrationServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedIntegrationServer", reflect.TypeOf((*MockUnsafeIntegrationServer)(nil).mustEmbedUnimplementedIntegrationServer))
}
