// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: services/services-hotels.proto

package hotels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_services_services_hotels_proto protoreflect.FileDescriptor

const file_services_services_hotels_proto_rawDesc = "" +
	"\n" +
	"\x1eservices/services-hotels.proto\x12#com_bundleport_connect_proto_hotels\x1a*domain/request/search-request-hotels.proto\x1a,domain/response/search-response-hotels.proto\x1a)domain/request/quote-request-hotels.proto\x1a+domain/response/quote-response-hotels.proto\x1a(domain/request/book-request-hotels.proto\x1a*domain/response/book-response-hotels.proto\x1a*domain/request/cancel-request-hotels.proto\x1a,domain/response/cancel-response-hotels.proto\x1a2domain/request/booking-detail-request-hotels.proto\x1a4domain/response/booking-detail-response-hotels.proto\x1a0domain/request/booking-list-request-hotels.proto\x1a2domain/response/booking-list-response-hotels.proto\x1a*domain/request/boards-request-hotels.proto\x1a,domain/response/boards-response-hotels.proto\x1a.domain/request/categories-request-hotels.proto\x1a0domain/response/categories-response-hotels.proto\x1a*domain/request/hotels-request-hotels.proto\x1a,domain/response/hotels-response-hotels.proto\x1a)domain/request/rooms-request-hotels.proto\x1a+domain/response/rooms-response-hotels.proto\x1a0domain/request/destinations-request-hotels.proto\x1a2domain/response/destinations-response-hotels.proto\x1a,domain/request/metadata-request-hotels.proto\x1a.domain/response/metadata-response-hotels.proto2\x9a\r\n" +
	"\vIntegration\x12s\n" +
	"\x06Search\x122.com_bundleport_connect_proto_hotels.SearchRequest\x1a3.com_bundleport_connect_proto_hotels.SearchResponse\"\x00\x12p\n" +
	"\x05Quote\x121.com_bundleport_connect_proto_hotels.QuoteRequest\x1a2.com_bundleport_connect_proto_hotels.QuoteResponse\"\x00\x12m\n" +
	"\x04Book\x120.com_bundleport_connect_proto_hotels.BookRequest\x1a1.com_bundleport_connect_proto_hotels.BookResponse\"\x00\x12s\n" +
	"\x06Cancel\x122.com_bundleport_connect_proto_hotels.CancelRequest\x1a3.com_bundleport_connect_proto_hotels.CancelResponse\"\x00\x12\x88\x01\n" +
	"\rBookingDetail\x129.com_bundleport_connect_proto_hotels.BookingDetailRequest\x1a:.com_bundleport_connect_proto_hotels.BookingDetailResponse\"\x00\x12\x82\x01\n" +
	"\vBookingList\x127.com_bundleport_connect_proto_hotels.BookingListRequest\x1a8.com_bundleport_connect_proto_hotels.BookingListResponse\"\x00\x12|\n" +
	"\tGetBoards\x125.com_bundleport_connect_proto_hotels.GetBoardsRequest\x1a6.com_bundleport_connect_proto_hotels.GetBoardsResponse\"\x00\x12\x88\x01\n" +
	"\rGetCategories\x129.com_bundleport_connect_proto_hotels.GetCategoriesRequest\x1a:.com_bundleport_connect_proto_hotels.GetCategoriesResponse\"\x00\x12|\n" +
	"\tGetHotels\x125.com_bundleport_connect_proto_hotels.GetHotelsRequest\x1a6.com_bundleport_connect_proto_hotels.GetHotelsResponse\"\x00\x12y\n" +
	"\bGetRooms\x124.com_bundleport_connect_proto_hotels.GetRoomsRequest\x1a5.com_bundleport_connect_proto_hotels.GetRoomsResponse\"\x00\x12\x8e\x01\n" +
	"\x0fGetDestinations\x12;.com_bundleport_connect_proto_hotels.GetDestinationsRequest\x1a<.com_bundleport_connect_proto_hotels.GetDestinationsResponse\"\x00\x12\x97\x01\n" +
	"\x12SearchDestinations\x12>.com_bundleport_connect_proto_hotels.SearchDestinationsRequest\x1a?.com_bundleport_connect_proto_hotels.SearchDestinationsResponse\"\x00\x12\x82\x01\n" +
	"\vGetMetadata\x127.com_bundleport_connect_proto_hotels.GetMetadataRequest\x1a8.com_bundleport_connect_proto_hotels.GetMetadataResponse\"\x00B\x82\x01\n" +
	"\x1ccom.bundleport.connect.protoB\x14HotelsServicesProtosP\x01Z.github.com/bundleport/connect-go-schema/hotels\xaa\x02\x19Bundleport.Connect.Hotelsb\x06proto3"

var file_services_services_hotels_proto_goTypes = []any{
	(*SearchRequest)(nil),              // 0: com_bundleport_connect_proto_hotels.SearchRequest
	(*QuoteRequest)(nil),               // 1: com_bundleport_connect_proto_hotels.QuoteRequest
	(*BookRequest)(nil),                // 2: com_bundleport_connect_proto_hotels.BookRequest
	(*CancelRequest)(nil),              // 3: com_bundleport_connect_proto_hotels.CancelRequest
	(*BookingDetailRequest)(nil),       // 4: com_bundleport_connect_proto_hotels.BookingDetailRequest
	(*BookingListRequest)(nil),         // 5: com_bundleport_connect_proto_hotels.BookingListRequest
	(*GetBoardsRequest)(nil),           // 6: com_bundleport_connect_proto_hotels.GetBoardsRequest
	(*GetCategoriesRequest)(nil),       // 7: com_bundleport_connect_proto_hotels.GetCategoriesRequest
	(*GetHotelsRequest)(nil),           // 8: com_bundleport_connect_proto_hotels.GetHotelsRequest
	(*GetRoomsRequest)(nil),            // 9: com_bundleport_connect_proto_hotels.GetRoomsRequest
	(*GetDestinationsRequest)(nil),     // 10: com_bundleport_connect_proto_hotels.GetDestinationsRequest
	(*SearchDestinationsRequest)(nil),  // 11: com_bundleport_connect_proto_hotels.SearchDestinationsRequest
	(*GetMetadataRequest)(nil),         // 12: com_bundleport_connect_proto_hotels.GetMetadataRequest
	(*SearchResponse)(nil),             // 13: com_bundleport_connect_proto_hotels.SearchResponse
	(*QuoteResponse)(nil),              // 14: com_bundleport_connect_proto_hotels.QuoteResponse
	(*BookResponse)(nil),               // 15: com_bundleport_connect_proto_hotels.BookResponse
	(*CancelResponse)(nil),             // 16: com_bundleport_connect_proto_hotels.CancelResponse
	(*BookingDetailResponse)(nil),      // 17: com_bundleport_connect_proto_hotels.BookingDetailResponse
	(*BookingListResponse)(nil),        // 18: com_bundleport_connect_proto_hotels.BookingListResponse
	(*GetBoardsResponse)(nil),          // 19: com_bundleport_connect_proto_hotels.GetBoardsResponse
	(*GetCategoriesResponse)(nil),      // 20: com_bundleport_connect_proto_hotels.GetCategoriesResponse
	(*GetHotelsResponse)(nil),          // 21: com_bundleport_connect_proto_hotels.GetHotelsResponse
	(*GetRoomsResponse)(nil),           // 22: com_bundleport_connect_proto_hotels.GetRoomsResponse
	(*GetDestinationsResponse)(nil),    // 23: com_bundleport_connect_proto_hotels.GetDestinationsResponse
	(*SearchDestinationsResponse)(nil), // 24: com_bundleport_connect_proto_hotels.SearchDestinationsResponse
	(*GetMetadataResponse)(nil),        // 25: com_bundleport_connect_proto_hotels.GetMetadataResponse
}
var file_services_services_hotels_proto_depIdxs = []int32{
	0,  // 0: com_bundleport_connect_proto_hotels.Integration.Search:input_type -> com_bundleport_connect_proto_hotels.SearchRequest
	1,  // 1: com_bundleport_connect_proto_hotels.Integration.Quote:input_type -> com_bundleport_connect_proto_hotels.QuoteRequest
	2,  // 2: com_bundleport_connect_proto_hotels.Integration.Book:input_type -> com_bundleport_connect_proto_hotels.BookRequest
	3,  // 3: com_bundleport_connect_proto_hotels.Integration.Cancel:input_type -> com_bundleport_connect_proto_hotels.CancelRequest
	4,  // 4: com_bundleport_connect_proto_hotels.Integration.BookingDetail:input_type -> com_bundleport_connect_proto_hotels.BookingDetailRequest
	5,  // 5: com_bundleport_connect_proto_hotels.Integration.BookingList:input_type -> com_bundleport_connect_proto_hotels.BookingListRequest
	6,  // 6: com_bundleport_connect_proto_hotels.Integration.GetBoards:input_type -> com_bundleport_connect_proto_hotels.GetBoardsRequest
	7,  // 7: com_bundleport_connect_proto_hotels.Integration.GetCategories:input_type -> com_bundleport_connect_proto_hotels.GetCategoriesRequest
	8,  // 8: com_bundleport_connect_proto_hotels.Integration.GetHotels:input_type -> com_bundleport_connect_proto_hotels.GetHotelsRequest
	9,  // 9: com_bundleport_connect_proto_hotels.Integration.GetRooms:input_type -> com_bundleport_connect_proto_hotels.GetRoomsRequest
	10, // 10: com_bundleport_connect_proto_hotels.Integration.GetDestinations:input_type -> com_bundleport_connect_proto_hotels.GetDestinationsRequest
	11, // 11: com_bundleport_connect_proto_hotels.Integration.SearchDestinations:input_type -> com_bundleport_connect_proto_hotels.SearchDestinationsRequest
	12, // 12: com_bundleport_connect_proto_hotels.Integration.GetMetadata:input_type -> com_bundleport_connect_proto_hotels.GetMetadataRequest
	13, // 13: com_bundleport_connect_proto_hotels.Integration.Search:output_type -> com_bundleport_connect_proto_hotels.SearchResponse
	14, // 14: com_bundleport_connect_proto_hotels.Integration.Quote:output_type -> com_bundleport_connect_proto_hotels.QuoteResponse
	15, // 15: com_bundleport_connect_proto_hotels.Integration.Book:output_type -> com_bundleport_connect_proto_hotels.BookResponse
	16, // 16: com_bundleport_connect_proto_hotels.Integration.Cancel:output_type -> com_bundleport_connect_proto_hotels.CancelResponse
	17, // 17: com_bundleport_connect_proto_hotels.Integration.BookingDetail:output_type -> com_bundleport_connect_proto_hotels.BookingDetailResponse
	18, // 18: com_bundleport_connect_proto_hotels.Integration.BookingList:output_type -> com_bundleport_connect_proto_hotels.BookingListResponse
	19, // 19: com_bundleport_connect_proto_hotels.Integration.GetBoards:output_type -> com_bundleport_connect_proto_hotels.GetBoardsResponse
	20, // 20: com_bundleport_connect_proto_hotels.Integration.GetCategories:output_type -> com_bundleport_connect_proto_hotels.GetCategoriesResponse
	21, // 21: com_bundleport_connect_proto_hotels.Integration.GetHotels:output_type -> com_bundleport_connect_proto_hotels.GetHotelsResponse
	22, // 22: com_bundleport_connect_proto_hotels.Integration.GetRooms:output_type -> com_bundleport_connect_proto_hotels.GetRoomsResponse
	23, // 23: com_bundleport_connect_proto_hotels.Integration.GetDestinations:output_type -> com_bundleport_connect_proto_hotels.GetDestinationsResponse
	24, // 24: com_bundleport_connect_proto_hotels.Integration.SearchDestinations:output_type -> com_bundleport_connect_proto_hotels.SearchDestinationsResponse
	25, // 25: com_bundleport_connect_proto_hotels.Integration.GetMetadata:output_type -> com_bundleport_connect_proto_hotels.GetMetadataResponse
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_services_services_hotels_proto_init() }
func file_services_services_hotels_proto_init() {
	if File_services_services_hotels_proto != nil {
		return
	}
	file_domain_request_search_request_hotels_proto_init()
	file_domain_response_search_response_hotels_proto_init()
	file_domain_request_quote_request_hotels_proto_init()
	file_domain_response_quote_response_hotels_proto_init()
	file_domain_request_book_request_hotels_proto_init()
	file_domain_response_book_response_hotels_proto_init()
	file_domain_request_cancel_request_hotels_proto_init()
	file_domain_response_cancel_response_hotels_proto_init()
	file_domain_request_booking_detail_request_hotels_proto_init()
	file_domain_response_booking_detail_response_hotels_proto_init()
	file_domain_request_booking_list_request_hotels_proto_init()
	file_domain_response_booking_list_response_hotels_proto_init()
	file_domain_request_boards_request_hotels_proto_init()
	file_domain_response_boards_response_hotels_proto_init()
	file_domain_request_categories_request_hotels_proto_init()
	file_domain_response_categories_response_hotels_proto_init()
	file_domain_request_hotels_request_hotels_proto_init()
	file_domain_response_hotels_response_hotels_proto_init()
	file_domain_request_rooms_request_hotels_proto_init()
	file_domain_response_rooms_response_hotels_proto_init()
	file_domain_request_destinations_request_hotels_proto_init()
	file_domain_response_destinations_response_hotels_proto_init()
	file_domain_request_metadata_request_hotels_proto_init()
	file_domain_response_metadata_response_hotels_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_services_hotels_proto_rawDesc), len(file_services_services_hotels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_services_hotels_proto_goTypes,
		DependencyIndexes: file_services_services_hotels_proto_depIdxs,
	}.Build()
	File_services_services_hotels_proto = out.File
	file_services_services_hotels_proto_goTypes = nil
	file_services_services_hotels_proto_depIdxs = nil
}
